### ISSUE TITLE
Speed up the build on Travis CI / Explore CircleCI

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#103]
Current builds are taking too long (20-30 mins). Would be great to speed it up!

Here is the history of build times: https://travis-ci.com/mobxjs/mobx.dart/builds

**Comment by pavanpodila** [comment]
The other option is we try out [CircleCI](https://circleci.com)

**Comment by pavanpodila** [comment]
We are making [some progress on CircleCI](https://circleci.com/gh/mobxjs/mobx.dart). Would love to get some experts chime in on the failing builds. @katis? @rrousselGit ? or others.

**Comment by rrousselGit** [comment]
It looks like there's a failing test. Sadly `test_coverage` doesn't report which one is failing

**Comment by pavanpodila** [comment]
Ya its not a failing test but test_coverage itself is acting up and becoming pretty unreliable. Can we go the route of straight up shell commands and gather coverage through that?

**Comment by pavanpodila** [comment]
One big advantage of CircleCI over Travis is the build times.

### 30 mins vs 3 mins!!

**Comment by rrousselGit** [comment]
> Ya its not a failing test but test_coverage itself is acting up and becoming pretty unreliable.

Are you sure about this? `test_coverage` never seem to report the failing test.
When I recently added it  in a project, I had to purposefully run `pub run test` before `pub run test_coverage` to have something readable.

This exception is exactly what I had when a test was failing with it.

**Comment by pavanpodila** [comment]
interesting. The tests are passing. For me its failing for "not able to find the `.test_coverage.dart` file"

**Comment by pavanpodila** [comment]
We now have passing tests/coverage from CircleCI. I will open the PR that migrates to Travis.

**Comment by pavanpodila** [comment]
Fixed in #112
