### ISSUE TITLE
Generate all.dart for tests

### ISSUE THREAD

**Issue by rrousselGit** [mobxjs/mobx.dart#104]
From a discussion with @katis on a closed PR.

I removed `all.dart` files for flutter tests on #43 as it seemed unneeded while causing maintenance issues (easy to not update it).

But @katis said:

> `test_coverage` generates it's own combined file. I've used the `all.dart` to run all unit tests with a single Dart VM launch which usually makes them run faster than every file opening their own separate VM.

In that case maybe we should ask `test_coverage` to extract the generator so that we can use it to generate `all.dart`.

If `all.dart` is generated, this would allow using `buid_test`, which makes a failing test if anything on the project haven't been generated. 
This would prevent from adding tests without updating the `all.dart`

**Comment by pavanpodila** [comment]
I have effectively deleted the all.dart file for the tests. I am instead using the "test all files in folder" approach

**Comment by pavanpodila** [comment]
I made that change in the recent pull #112
