### ISSUE TITLE
Create a PR to add Mobx to the state managements solutions list on flutter.io

### ISSUE THREAD

**Issue by rrousselGit** [mobxjs/mobx.dart#105]
Flutter has a nice page listing the available state management solutions: https://flutter.io/docs/development/data-and-backend/state-mgmt/options

This is something we can contribute to through https://github.com/flutter/website

**Comment by Rahiche** [comment]
I think an introduction article is missing for now

**Comment by thevpatel** [comment]
A medium article on todo app will be best introduction i believe.

**Comment by pavanpodila** [comment]
@sanketsahusoft or someone from his team is working on a nice article :-). I'll let him pitch in about it.

**Comment by buncismamen** [comment]
hello I've made the PR 
https://github.com/flutter/website/pull/2483

**Comment by pavanpodila** [comment]
Awesome @buncismamen ! thanks a lot

**Comment by pavanpodila** [comment]
Closing this as this has been merged into the flutter website
