### ISSUE TITLE
Package organization

### ISSUE THREAD

**Issue by katis** [mobxjs/mobx.dart#11]
Currently the repository deviates somewhat from the Pub package layout conventions (https://www.dartlang.org/tools/pub/package-layout#implementation-files).

The `lib/src/api` files should be in `lib/`, as those seem to be public files, `lib/src/core` should maybe be in `lib/src/` because they seem to be mostly private details.

Also, Dart's visibility rules are a bit different from other languages I've used before, since "private" means "private to the module". This means that a lot of code has to be in the same file if the classes need to use private methods from other classes. As an example, Flutters base widgets are in a [single file](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart).

**Comment by pavanpodila** [comment]
Yup we should stick to conventions as much as possible

Regards,

--
Pavan Podila

**Comment by katis** [comment]
I'm starting to work on this again now so we can hide the ugly details from users.

Should we go with a monorepo and host `flutter_mobx` in this repository as well? Could make maintenance easier. Also if we create the code generator at some point it needs a separate package as well.

**Comment by rrousselGit** [comment]
> . This means that a lot of code has to be in the same file if the classes need to use private methods from other classes. 

A solution to this is `part` directive

**Comment by pavanpodila** [comment]
> I'm starting to work on this again now so we can hide the ugly details from users.
> 
> Should we go with a monorepo and host `flutter_mobx` in this repository as well? Could make maintenance easier. Also if we create the code generator at some point it needs a separate package as well.

Yup agree on going with a **monorepo**. Totally makes sense. Also the `part` directive as @rrousselGit suggested will make the sharing of files easy.

**Comment by rrousselGit** [comment]
Indeed usually we want a single file although this is fine in multiple situations where the file becomes far too big. 

Many official examples are showcasing it:

- https://github.com/flutter/flutter/blob/75b737ff695afba5ec8b4e313c130c520b3651fb/packages/flutter/lib/src/material/animated_icons.dart
- https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/async.dart
