### ISSUE TITLE
assertion error while trying todo example

### ISSUE THREAD

**Issue by canewsin** [mobxjs/mobx.dart#117]
i copy paste todo example to a new proj i got above error > there are no observables detected in your builder

**Comment by pavanpodila** [comment]
Hope you have copied the **`*.g.dart`** files as well. These are the generated files that are required to make it work correctly.

**Comment by canewsin** [comment]
hi i had copied all files i think you have to correct AddTodoWidget because there is no observer in it and with out an observer so it throws an error  you have set an assert field in your code may be you have to correct your eg.

**Comment by pavanpodila** [comment]
Removed the observer from the `AddTodo` widget. Please get an update and try again.

**Comment by canewsin** [comment]
i already corrected that before posting this issue i just reported here so that you can correct your example 
 i was an advanced dart user so i don't get any problem but because lib is yours at-least example should be build-able for beginner friendly users

**Comment by pavanpodila** [comment]
Thanks for that @canewsin. Beginners are a very important audience for us.
