### ISSUE TITLE
Mobx codegen ignores stores with generic parametes

### ISSUE THREAD

**Issue by radzish** [mobxjs/mobx.dart#118]
Example:
```
import 'package:mobx/mobx.dart';

part 'test_store.g.dart';

class TestStore<T> = TestStoreBase<T> with _$TestStore<T>;

abstract class TestStoreBase<T> implements Store {
  //
}
```
is skipped, nothing is generated, no error in generator output

**Comment by radzish** [comment]
That was fast. Thanks!

Therefore I found another bug with new implementation. Try following:

```

**Comment by radzish** [comment]
That was fast. Thanks!

Therefore I found another bug with new implementation. Try following:
```
import 'package:mobx/mobx.dart';

part 'test_store.g.dart';

class StringStore extends TestStore<String> {}

class IntStore extends TestStore<int> {}

abstract class TestStore<T> = TestStoreBase<T> with _$TestStore<T>;

abstract class TestStoreBase<T> implements Store {
  @observable
  T data;
}
```

it will produce:

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'test_store.dart';

// **************************************************************************
// StoreGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names, unnecessary_lambdas, prefer_expression_function_bodies

mixin _$StringStore<T> on TestStoreBase<T>, Store {
  final _$dataAtom = Atom(name: 'TestStoreBase.data');

  @override
  T get data {
    _$dataAtom.reportObserved();
    return super.data;
  }

  @override
  set data(T value) {
    mainContext.checkIfStateModificationsAreAllowed(_$dataAtom);
    super.data = value;
    _$dataAtom.reportChanged();
  }
}
```

Please note that _$StringStore is generated instead of _$TestStore.
In example above, if I move concrete classes declaration to the bottom (or move out to another class) everything works fine though :) So I will use that workaround.

**Comment by gavv** [comment]
>  In example above, if I move concrete classes declaration to the bottom (or move out to another class) everything works fine though :) So I will use that workaround.

Thanks for the tip!

I can confirm, inheriting generic store works only if parent and child are in the same file and parent is placed before child.
