### ISSUE TITLE
generate .g.dart files in seperate folder 

### ISSUE THREAD

**Issue by canewsin** [mobxjs/mobx.dart#120]
consider to generated files to be in folder like gen/ or something like that because for 2 or 3 files it looks ok but if we had 30-40 files it becomes clumsy in a single folder

**Comment by rrousselGit** [comment]
You can configure this yourself through the `build.yaml` file.

See the package `build-config` on pub

**Comment by canewsin** [comment]
should i have to modify your lib's build.yaml i didn't any options for to output to another folder 

@rrousselGit 
give me some suggestion to how to do it

**Comment by wtoalabi** [comment]
I would also really love to know...
Awesome job by the way!
This package (pattern) is lit!!!

**Comment by hramnathnayak** [comment]
I use workspace setting on vscode to hide the *.g.dart files.

"files.exclude": {
    "**/*.g.dart": true
  },

**Comment by ozum** [comment]
Hi,

I'm using `json_serializable`s code generation and it's generated files has same names with mobx generated files. Unfortunately `json_serializable` output cannot be configured :(

How to change file names or file directory at least of generated files of mobx? @rrousselGit mentioned `build.yaml`, but I cannot find a way to do?

Thanks,

**Comment by pavanpodila** [comment]
@ozum I was thinking the build_runner merged the outputs from `mobx_codegen` and `json_serializable`. Isn't that happening ?

@rrousselGit might know this better than me though.

**Comment by rrousselGit** [comment]
> I was thinking the build_runner merged the outputs 

It does but won't rename classes to avoid name conflicts.

Unfortunately, there's not much you can do besides finding a way to remove the name conflict. But it can usually be done by moving some classes to another file.

**Comment by ozum** [comment]
@pavanpodila, yes build_runner merged the outputs, but as @rrousselGit stated, conflicts happen. Even generated into different files, there are other problems too. I opened another case asking how to use both together not to hijack this case with details of my particular problem.

Nonetheless, it would be good to know if renaming or separate folder is possible?
