### ISSUE TITLE
I know It might seem too early, but when can I expect Mobx state tree functionality???

### ISSUE THREAD

**Issue by DeepStyles** [mobxjs/mobx.dart#122]

**Comment by pavanpodila** [comment]
:-) Will take some time. We need to first research, breakdown the feature set and map it to the Dart ecosystem. I also need some expert insight from @mweststrate on this.

**Comment by sanketsahusoft** [comment]
Yes, along with @mattiamanzati :-)

**Comment by DeepStyles** [comment]
Cool, I guess meanwhile I will use Dependency Injection!!!!

**Comment by pavanpodila** [comment]
Closing this for now as its mostly discussion.

**Comment by yshean** [comment]
Any updates on this?

**Comment by pavanpodila** [comment]
This is not on the cards yet. I don't have a particular need for it, so not a priority for me. However I am happy to participate if someone else wants to pick this up.
