### ISSUE TITLE
Is there a pattern for getting stores to communicate and be persistent?

### ISSUE THREAD

**Issue by jasonlewicki** [mobxjs/mobx.dart#124]
Thanks for putting this package together. I use mobx for all of my webdev needs. I have a few questions:

Can stores be static? Such that changing from screen to screen keeps the observable data intact? Is there another way to do this?

What about stores talking to eachother? On the web dev side i use this pattern:
https://github.com/mobxjs/mobx-react/issues/524

is it possible to carry this over?

Thanks

**Comment by pavanpodila** [comment]
The general principle to keep the stores persistent across the screens, is the **"lift the state"**, which is to  keep the state outside as a singleton. Stores can communicate with each other via callbacks. You are better off keeping a higher level Store that orchestrates the communication by setting up the callbacks. This way the stores don't have to know about each other directly

**Comment by jasonlewicki** [comment]
@pavanpodila Thanks.

I'm trying to think of a way to convert the abstract store code i have into a singleton. 

**Normal store**
```dart
class ExampleStore = _ExampleStore with _$ExampleStore;
abstract class _ExampleStore implements Store {

  @observable
  bool isLoading = true;

}

```

**Singleton store**
``` dart

class ExampleStore = _ExampleStore with _$ExampleStore;
abstract class _ExampleStore implements Store  {

  @observable
  bool isLoading = true;

  static _ExampleStore _exampleStore;

  static _ExampleStore _getInstance() { 
    if (_exampleStore == null) 
        _exampleStore = new _ExampleStore._internal(); 
    return _exampleStore; 
  } 

  static final _ExampleStore instance = _getInstance();

  _ExampleStore._internal();
}

```

Is that right?

**Comment by jasonlewicki** [comment]
Hmm, maybe a singleton wrapper around the whole thing?

**Comment by jasonlewicki** [comment]
Ok got it:
``` dart

final ExampleStore exampleStore = ExampleStore.instance;
await bfStore.init();   

class ExampleStore {
  static ExampleStore _exampleStore;
  GlobalStore global;
  SplashStore splash;
  LoginStore login;

  static ExampleStore _getInstance() { 
    if (_exampleStore == null){
        _exampleStore = new ExampleStore._internal(); 
        _exampleStore.global = new GlobalStore(_exampleStore);
        _exampleStore.splash = new SplashStore(_exampleStore);
        _exampleStore.login = new LoginStore(_exampleStore);
    }
    return _exampleStore; 
  } 
  static final ExampleStore instance = _getInstance();
  ExampleStore._internal();
}

class GlobalStore = _GlobalStore with _$GlobalStore;
abstract class _GlobalStore implements Store {

  ExampleStore parent;
 
  @observable
  bool isLoading = true;

  _GlobalStore(ExampleStore exampleStore){
    parent = exampleStore;
  }

  @action
  void setIsLoading(bool isLoading) {
    this.isLoading = isLoading;
  }

```

**Comment by jasonlewicki** [comment]
Going to close, but if you have any tips as to how this should be be improved (I'm new to Dart), I'd be be much appreciated.

**Comment by pavanpodila** [comment]
@jasonlewicki Also look at the use of [Provider](https://pub.dartlang.org/packages/provider) to keep track of your singletons
