### ISSUE TITLE
Validate versions of mobx and mobx_codegen to avoid build_runner generation issues

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#127]
The versioning difference between the various packages can be a cause of problems, as pointed out by @thedejifab in #126. This happens if the `mobx_codegen` is out of sync with what is expected in the version of `mobx`.

### Potential solution

Perhaps, `mobx` and `mobx_codegen` should be lock-step in versioning. Also when running the `build_runner`, the generator should enforce it. This requires adding a version field to both `mobx` and `mobx_codegen`.

**Comment by kush3107** [comment]
Any updates on this?

I am unable to generated the .g files.

**Comment by pavanpodila** [comment]
Does this help: https://mobx.pub/getting-started ?

**Comment by kush3107** [comment]
Thanks @pavanpodila , I figured out the problem if I was doing the same the way as in the offical example it wasn't working for me so I had to manually search for the latest version of `mobx`, `flutter_mobx` and `mobx_codegen` and after that it worked fine for me.

**Comment by pavanpodila** [comment]
Ah. I think the [Getting Started](https://github.com/mobxjs/mobx.dart/edit/master/docs/src/getting-started/index.mdx) article should mention the versions explicitly then! Want to send me a PR?

**Comment by kush3107** [comment]
Yea sure I can do that.

**Comment by kush3107** [comment]
Hi @pavanpodila I just opened a PR - https://github.com/mobxjs/mobx.dart/pull/242

**Comment by pavanpodila** [comment]
Part of this was covered in the PR #295

**Comment by pavanpodila** [comment]
Doesn't seem necessary currently
