### ISSUE TITLE
Factories vs Builder functions

### ISSUE THREAD

**Issue by katis** [mobxjs/mobx.dart#13]
Should we use Dart factories instead of builder functions for the public API?

If we renamed `ObservableValue` to `Observable` and `ComputedValue` to `Computed`, made the constructor private and added a public factory like this:

```dart
class Observable<T> {
  Observable._(ReactiveContext context, String name, T initialValue) { ... }

  factory Observable(T initialValue, { String name, ReactiveContext context }) { .... }
}
```

Then the use would still be simple like with the builder function:

```dart
class MyStore {
  final value = Observable(10);
}
```

This is just a personal preference of mine though as I feel the factory would be more Darty.

**Comment by pavanpodila** [comment]
Our API is already providing it: `observable(10)`. For a factory the identifier would just become capitalized. Still not clear if we a function or a factory-constructor is better. Although since I am jaded by using MobX JavaScript, I am just leaning towards a function. 

How about we provide both for now and see what sticks ??

**Comment by pavanpodila** [comment]
Let's go the Dart way with **factories**. Although the API is different in JS, I think we should take the Dart convention.

**Comment by pavanpodila** [comment]
> We can just keep the builder function, I don't see the point in providing two ways to do things.
> Maybe in the future this whole point will be moot if we can create a [code generator](https://pub.dartlang.org/packages/source_gen) that does the same kind of magic as MobxJS annnotations. Then the use of builders would probably be rare any way.

I am still curious how source_gen would help

**Comment by katis** [comment]
Sorry, missed your messages.

I think it should be possible to use `source_gen` to have code like this:

```dart
part 'view_model.g.dart';

abstract class ViewModel {
  factory ViewModel() = _$ViewModel;

  @observable
  int counter;

  @action
  void increment() {
    counter++;
  }
}
```

generate `view_model.g.dart` like this:

```dart
class _$ViewModel extends ViewModel {
  Action() {
    _$increment = action(super.increment);
  }
  
  final _$counter = observable(0); // not sure how to handle initial value yet
  int get counter => _$counter.value;
  set counter(int value) => _$counter.value = value;
  
  Action _$increment;
  @override
  void increment() {
    _$increment();
  }
}
```

Then you could easily use ViewModel in reactive situations:

```dart
final vm = ViewModel();
autorun(() {
  print(vm.counter);
});
vm.increment();
vm.increment();
```

[`built_value`](https://medium.com/dartlang/darts-built-value-for-immutable-object-models-83e2497922d4) does this kind of magic.

**Comment by pavanpodila** [comment]
Wow this is beautiful. Love it. I definitely have to dig deeper into `source_gen` and understand its capabilities. From the looks, it is very promising and opens up a world of possibilities with some **meta-programming wizardry**.

Thanks for sharing a detailed example 💯
