### ISSUE TITLE
importing with alias causing partial to not generate correctly

### ISSUE THREAD

**Issue by jasonlewicki** [mobxjs/mobx.dart#130]
importing an observable type like this:
```dart
import 'package:example_flutter/models/event.dart' as model;
```

and declaring an observable:
```dart
@observable
ObservableList<model.Event> events = ObservableList<model.Event>();
```

causes the `.g` file to not be compiled correctly.

**Comment by pavanpodila** [comment]
Can you share the error or exception?

**Comment by jasonlewicki** [comment]
The error is shown on the store itself:

```
class ExampleStore extends _ExampleStore with _$ExampleStore
'_$ExampleStore.events' ('() → ObservableList<dynamic>') isn't a valid override of '_ExampleStore.events' ('() → ObservableList<Event>').dart(invalid_override)
```

**Comment by pavanpodila** [comment]
Verified its a valid bug. I think @katis might have some ideas. I'll try to research if it's a `build_runner` limitation

**Comment by pavanpodila** [comment]
Apparently, this is not a bug in `mobx_codegen` and seems to be due to `build_runner` not able to support aliased imports, as seen [here](https://github.com/dart-lang/json_serializable/issues/19) in the `json_serializable` package.

@jasonlewicki, for now please avoid using aliased imports in the file containing the `Store` classes.

**Comment by MisterJimson** [comment]
I feel like this issue should be reopened and labeled as being blocked by build_runner for now. Lots of people will run into it, should make the issue easy to find.

**Comment by shyndman** [comment]
Agreed.

I have a fix in mind for this actually, that should be fairly low impact to the codebase.

**Comment by shyndman** [comment]
Got everything sorted out in this commit https://github.com/mobxjs/mobx.dart/pull/309/commits/5cb95fa220b2e6dc32c018453de3a0d025790aa6
