### ISSUE TITLE
ObservableFuture.error incorrect type

### ISSUE THREAD

**Issue by t-artikov** [mobxjs/mobx.dart#131]
https://github.com/mobxjs/mobx.dart/blob/6442d82cc531f1ed8cc5185a699b88e0bb873a2b/mobx/lib/src/api/async/observable_future.dart#L98
I believe return type should be Object instead of T. The type of error and the type of value are not the same.

**Comment by pavanpodila** [comment]
You are right. Will fix this.

**Comment by pavanpodila** [comment]
This is now fixed and published on [pub](https://pub.dartlang.org/packages/mobx)
