### ISSUE TITLE
Flutter API

### ISSUE THREAD

**Issue by katis** [mobxjs/mobx.dart#14]
Last night I thought I'd try to use Mobx with Flutter and created a simple widget based on the design of mobx-react and Flutter's [ValueListenableBuilder](https://docs.flutter.io/flutter/widgets/ValueListenableBuilder-class.html):

```dart
import 'package:flutter/widgets.dart';
import 'package:mobx/mobx.dart';

void noOp() {}

class Observer extends StatefulWidget {
  const Observer({Key key, @required this.builder}) : super(key: key);

  final Widget Function(BuildContext) builder;

  @override
  State<StatefulWidget> createState() => _ObserverState();
}

class _ObserverState extends State<Observer> {
  bool _isBuildPending = false;

  Reaction _buildReaction;

  @override
  void initState() {
    super.initState();

    _buildReaction = Reaction(mobxContext, () {
      if (_isBuildPending) {
        return;
      }

      _isBuildPending = true;
      if (!mounted) {
        return;
      }

      setState(noOp);
    });
  }

  @override
  Widget build(BuildContext context) {
    _isBuildPending = false;
    Widget result;
    _buildReaction.track(() {
      result = widget.builder(context);
    });
    return result;
  }
}
```

usage:

```dart
class Greeter extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _GreeterState();
}

class _GreeterState extends State<Greeter> {
  final name = observable('Jane');

  @override
  Widget build(BuildContext context) => Observer(builder: (context) {
    return Text('Hello, ${name.value}');
  });
}
```

It does seem to work and could be a starting point for the `flutter_mobx` API. Probably the life cycle of widgets will bring all kinds of problems like in `mobx-react`.

**Comment by pavanpodila** [comment]
I think we can simply use a `reaction` that internally calls the `build` method. That way anything that is invoked in the `builder` method is tracked. I don't think we should use the internal `track()` method directly.

This is certainly the direction to take!

**Comment by pavanpodila** [comment]
Got it. We can also try to build a **custom scheduler** that will call the reaction only when there is a change. I think that will keep it clean and only rely on the public interface? I want to avoid using `track` directly unless we find that there is no other way.

We haven't exposed the scheduler yet from a `reaction`, which we will have to do first.

**Comment by pavanpodila** [comment]
Oh, I meant the scheduler in the _Reaction_ and not for Flutter. With a custom scheduler for a Reaction (which will have to be exposed in MobX), we can be efficient about calling `setState()`.

At this point, this is pure hypothesis but I believe it will lead us to the right solution.

**Comment by rrousselGit** [comment]
👋 I'm the author of https://github.com/rrousselGit/flutter_hooks, a port to Flutter of React hooks.

Considering mobx.js is creating mobx-react-lite using hooks, would that be worth considering to do the same with Flutter?

**Comment by pavanpodila** [comment]
Hello @rrousselGit ! Looks very interesting indeed. I'll have to dig a bit deeper to understand how it can simplify creating Flutter widgets for MobX. Any sample code I can look at to see a potential implementation of a flutter_hook for a mobx-observer widget?

**Comment by rrousselGit** [comment]
The example from the first post would become:

```
class Greeter extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final name = useObservable('name');
    return Text('Hello, ${name.value}');
  }
}
```

I don't fully understand `Observer` from the example yet, so converting it to hooks is out of my reach for now. 
But flutter_hooks offer a class version, which exposes the equivalent of `initState` and `build` for hooks. So I'd expect it to be pretty similar with just a few method rename.

**Comment by pavanpodila** [comment]
From an API standpoint it's clearly a winner. I am curious what @katis thinks. Personally I have few questions:

- Does it mean the Flutter app would have to depend on `flutter_hooks` in order to use `flutter_mobx`?
- Can we have a Widget that does not require the app to depend on `flutter_hooks`, yet give us an infrastructure for easier creation of an `Observer` widget?

**Comment by katis** [comment]
Seems that `mobx-react-lite` uses the same `reaction.track` based code as `mobx-react`:

```
// inside observer()
const wrappedComponent = (props: P, ref: React.Ref<TRef>) => {
  return useObserver(() => baseComponent(props, ref), baseComponentName)
}
```

```
export function useObserver<T>(fn: () => T, baseComponentName = "observed"): T {
    if (isUsingStaticRendering()) {
        return fn()
    }

    // forceUpdate 2.0
    const forceUpdate = useForceUpdate()

    const reaction = useRef(
        new Reaction(`observer(${baseComponentName})`, () => {
            forceUpdate()
        })
    )

    useUnmount(() => {
        reaction.current.dispose()
    })

    // render the original component, but have the
    // reaction track the observables, so that rendering
    // can be invalidated (see above) once a dependency changes
    let rendering!: T
    reaction.current.track(() => {
        rendering = fn()
    })
    return rendering
}
```

Right now I don't see how `flutter_hooks` would help with the actual implementation of an observable widget, we need to wrap the whole `build` method to track observable changes happening inside it.  Dart can't compose classes as easily as JS can functions.

Dart also can't implement the `useObservable()` hook for classes because there is no runtime reflection in Flutter.

But I can totally see myself using hooks in my own projects, so thanks for letting us know about `flutter_hooks`.

**Comment by rrousselGit** [comment]
Can you clarify a bit the following?

> Right now I don't see how flutter_hooks would help with the actual implementation of an observable widget, we need to wrap the whole build method to track observable changes happening inside it. Dart can't compose classes as easily as JS can functions.

`flutter_hooks` internally uses a custom `Element` which wraps the whole `build` method. So this is something that could be exposed fairly easily.

**Comment by rrousselGit** [comment]
Sounds good to me.  I will create a `didBuild` lifecycle on the Hook class, followed by a `useAsyncEffect` hook (and a `useDispose`).

From my understanding, that should cover the needs.

**Comment by katis** [comment]
Mobx will need a way to start and stop tracking separately to implement the hook. Now it always assumes that you provide a callback that is executed and changes inside are tracked.

**Comment by rrousselGit** [comment]
@pavanpodila I love the callable class syntax, this allows some pretty cool naming for hooks!

But realistically speaking, I do not think it is desired to ask users write the `try`/`finally`.

**Comment by pavanpodila** [comment]
@rrousselGit I meant this would be the wrapped code inside the builder. The end users will not be using the `try-finally` block. My bad, the example code shows it at the Widget level, but it would really be inside an internal Widget that wraps the useObserver. This is only to hide the start/end calls for tracking without the need for a `didBuild` hook. Not sure if it is feasible though.

**Comment by rrousselGit** [comment]
Similarly to the example here? https://github.com/mobxjs/mobx.dart/issues/14#issuecomment-451762737

Indeed that's possible. 

But then I would suggest to make your own kind of widget that has a custom `Element` with an overriden `performRebuild`. 

such that we have:

```dart
class Greeter extends ObserverWidget {
  @override
  Widget build(BuildContext context) {
    // 
  }
}
```

where `ObserverWidget` would be:

```
abstract class ObserverWidget extends HookWidget {
  const ObserverWidget({Key key}): super(key: key);

  @override
  createElement() => ObserverElement();
}

class ObserverElement extends HookElement {
  @override
  void performRebuild() {
    // track
  super.performRebuild();
   // end track
  }
}
```

**Comment by rrousselGit** [comment]
I'll merge `didBuild` life-cycle implementation in `flutter_hooks`. 
After some thoughts, this has many use-cases other than for mobx.

**Comment by pavanpodila** [comment]
I feel we should work on a non-trivial app to refine the API and smooth out any rough corners. I have been thinking of a few apps that we can build together and potentially also ship on the App Store 🤔 🦄 . That app will be the capstone example of MobX, with real-world use-cases.

Do you think that will help in arriving at the ideal API?

**Comment by rrousselGit** [comment]
Agreed.
A good starter would be https://github.com/brianegan/flutter_architecture_samples

At the very least, we'll want to contribute an example out there.

**Comment by katis** [comment]
@rrousselGit I think implementing hooks for disposable resources would be useful. Like `useAutorun`, `useReaction` etc.

I've experimented with the `useObserver` hook in my own app, and I don't really need much else, since my apps state is in a separate InheritedWidget store I inject with a hook where needed:

```
MyAppStore useMyAppStore() {
  BuildContext context = useContext();
  return InjectMyAppStore.of(context);
}
```

**Comment by katis** [comment]
@rrousselGit I'm not sure what you mean? Could you show an example?

**Comment by rrousselGit** [comment]
I wanted to remove the need for `Reaction` by making some widget specific logic similarly to how `InheritedWidget` works.

But after some thoughts, while this is technically possible, it would require a kind of widget (and not work with `Stateless/StatefulWIdget`), which defeats the whole point of not having to use `Reaction`.

**Comment by katis** [comment]
Yeah, I think `Observer` is "good enough", and Flutter has already established a pattern of state managing widgets with a `builder` function.

**Comment by pavanpodila** [comment]
I think we also need a **`Provider`** widget (subclass of `InheritedWidget`) that takes in a bunch of stores (as a `Map<String, Store>`) as input.

**Comment by rrousselGit** [comment]
Why a `Map<String, Store>` ?

This is not type safe and less performant than a `Provider<StoreSubclass>`



Anyway, I made such provider here: https://github.com/rrousselGit/provider


It should be a good source of inspiration

**Comment by pavanpodila** [comment]
I was going by the API in mobxjs :-). Your suggestion is much better. I think we should expose a **Provider** with those ideas, just to make it easy for our end users

**Comment by marcoms** [comment]
Provider seems very useful! Would be great to have it integrated with mobx.dart :smiley:

**Comment by rrousselGit** [comment]
I'm not sure if it makes sense to include this in mobx. 
There are no mobx specific requirements here.

**Comment by marcoms** [comment]
That's fair. So is the correct usage for Provider+MobX is something like the following?

```dart
final state = MyState();

class MyApp extends StatelessWidget {
  Widget build(ctx) {
    return Provider<MyState>(
      value: myState,
      child: MaterialApp(
        // ...
      ),
    );
  }
}

// Another file

class MyPage extends StatelessWidget {
  Widget build(ctx) {
    final state = Provider.of<MyState>(ctx);
    
    return Observer(
      builder: (ctx) {
        return Container(
          width: 20,
          height: 20,
          color: state.color,
        );
      ),
    );
  }
}
```

If I understand correctly, I should set `listen: false` to prevent MyPage from being rebuilt on changes, because I only need MyState in the Observer() block. Is that right?

**Comment by katis** [comment]
If your app has a single store, you could just write the InheritedWidget yourself, 1 less dependency:

```dart
// inject_my_store.dart
class InjectMyStore extends InheritedWidget {
  InjectMyStore(this._store, Widget child) : super(child: child);

  final MyStore _store;

  static MyStore of(BuildContext context) {
    final store = context.inheritFromWidgetOfExactType(InjectMyStore) as InjectMyStore;
    return store._store;
  }

  @override
  bool updateShouldNotify(InheritedWidget oldWidget) {
    if (oldWidget is InjectMyStore) {
      return _store != oldWidget._store;
    }
    return true;
  }
}

// my_store.dart
class MyStore extends _MyStore with _$MyStore {
  static MyStore of(BuildContext context) => InjectMyStore.of(context);
}

abstract class _MyStore implements Store {
  @observable
  foo = '';
}

// main.dart

void main() {
  final store = MyStore();
  runApp(InjectMyStore(store, RootComponent()));
}

class RootComponent extends StatelessWidget {
  build(BuildContext context) {
    final store = MyStore.of(context);
    return Container();
  }
}
```

**Comment by pavanpodila** [comment]
We need to start documenting all this on our site. This is going to be the first set of questions asked by anyone wanting to use MobX.

Also part of the 0.1 release #97. I am going to spend the next week just doing docs 🚀

**Comment by crizant** [comment]
> That's fair. So is the correct usage for Provider+MobX is something like the following?
> 
> ```dart
> final state = MyState();
> 
> class MyApp extends StatelessWidget {
>   Widget build(ctx) {
>     return Provider<MyState>(
>       value: myState,
>       child: MaterialApp(
>         // ...
>       ),
>     );
>   }
> }
> 
> // Another file
> 
> class MyPage extends StatelessWidget {
>   Widget build(ctx) {
>     final state = Provider.of<MyState>(ctx);
>     
>     return Observer(
>       builder: (ctx) {
>         return Container(
>           width: 20,
>           height: 20,
>           color: state.color,
>         );
>       ),
>     );
>   }
> }
> ```
> 
> EDIT: Just realized I don't need to assign it in the outer scope:
> 
> ```dart
> class MyPage extends StatelessWidget {
>   Widget build(ctx) {
>     return Observer(
>       builder: (ctx) {
>         final state = Provider.of<MyState>(ctx);
>         return Container(
>           width: 20,
>           height: 20,
>           color: state.color,
>         );
>       ),
>     );
>   }
> }
> ```

I think this is not very elegant, if you have more store, you will have to do this:
```
return Provider<AuthStore>(
      value: myAuthStore,
      child: Provider<ArticleStore>(
        value: myArticleStore,
        child: MaterialApp(
          // ...
        ),
      )
    );
```

It would be nice if we could have a single `Provider` to provides all stores at once,
like in `mobx-react` does.

**Comment by marcoms** [comment]
Personally I've switched to a single appState Store instance to consolidate everything. I figured it's not as dangerous since only the observed fields will trigger re-renders for Observers, right?

**Comment by em-ka** [comment]
@crizant: You can use the [Multiprovider](https://github.com/rrousselGit/provider#multiprovider).

**Comment by crizant** [comment]
> @crizant: You can use the [Multiprovider](https://github.com/rrousselGit/provider#multiprovider).

Thanks! how come I forgot to read the doc.

**Comment by rrousselGit** [comment]
Related to https://github.com/google/flutter-provide/issues/3

There's an on-going discussion about merging all the different InheritedWidget wrapper and making one official solution,  with the potential destination being `provider`

`provider` or not, this reinforces the fact that `mobx` should avoid providing its own implementation.

I'll keep you updated

**Comment by pavanpodila** [comment]
Great @rrousselGit. Definitely don't want any more duplicates from our end!

**Comment by pavanpodila** [comment]
Closing this issue as its getting into discussion mode :-)

**Comment by Timbabs** [comment]
Does mobx flutter know when to dispose of the store? Or do I have to explicitly call store.dispose()?

**Comment by pavanpodila** [comment]
The Store's lifetime is your responsibility, so you will have to call dispose when you see fit
