### ISSUE TITLE
Doesn't propagate if Store is inside Map

### ISSUE THREAD

**Issue by wiradikusuma** [mobxjs/mobx.dart#140]
I have the following:

	class AppConfig extends InheritedWidget {
		MyStore my = MyStore();

		// Populated somewhere, e.g. posts[o.id] = MyStore()
		Map<int, MyStore> posts = {};

		static AppConfig of(ctx) {
			return ctx.inheritFromWidgetOfExactType(AppConfig);
		}
	}

Called like this:

	AppConfig.of(ctx).my.increment();
	AppConfig.of(ctx).posts[someId].increment();

The 1st call will automatically update this:

	Observer(
		builder: (ctx) => Text(AppConfig.of(ctx).my.value.toString()),
	),

BUT NOT this:

	Observer(
		builder: (ctx) => Text(AppConfig.of(ctx).posts[someId].value.toString()),
	),

`someId` is valid and no error is produced. How do I make the 2nd version (`Map`) work?

**Comment by pavanpodila** [comment]
Use the `ObservableMap` instead of the Map

**Comment by wiradikusuma** [comment]
Thanks, it works! I always thought ObservableXXX only apply inside Stores.

**Comment by pavanpodila** [comment]
Observables can be anywhere in your Reactive State and can be used independent of Stores. The Store gives you a nice way to use annotations though

**Comment by wiradikusuma** [comment]
Sorry I reopen this issue, as it's closely related. 

Now that the above works with `ObservableMap`, inside `MyStore` I have the following:

	abstract class _MyStore implements Store {
		@observable
		var comments = ObservableList<Comment>();

		@action
		void addComment(Comment comment) {
			comments.add(comment);
		}

		@computed
		String get length => comments.length.toString();
	}

Calling this:

	AppConfig.of(ctx).posts[someId].addComment(comment);

Will trigger this:

	Observer(
		builder: (ctx) => Text(AppConfig.of(ctx).posts[someId].length),
	),

But NOT this:

	Observer(
		builder: (ctx) => _Comments(AppConfig.of(ctx).posts[someId].comments),
	),

What could be wrong? `comments` is `ObservableList`.

**Comment by pavanpodila** [comment]
MobX will notify only on changes to an observable. In your case the `comments` field is not changing, only its contents.

**Comment by wiradikusuma** [comment]
Thanks for your reply. But the documentation ( https://mobx.pub/api/observable#observablelist ) says:

> An ObservableList gives you a deeper level of observability on a list of values. It tracks when items are added, removed or modified and notifies the observers. Use an ObservableList when a change in the list matters.

Let me try recreating the list then and I'll get back to you.

**Comment by wiradikusuma** [comment]
You are right, I need to recreate the list. Thank you!
