### ISSUE TITLE
Difference between ObservableList and List?

### ISSUE THREAD

**Issue by dukaric1991** [mobxjs/mobx.dart#142]
Whats the difference between

```dart
@observable
  ObservableList<MatchClass> listOfMatches = ObservableList<MatchClass>();
```

and

```dart
@observable
  List<MatchClass> listOfMatches = [];
```

**Comment by rrousselGit** [comment]
`List` will not notify Mobx that a value has changed when you do:

```dart
listOfMatches[0] = match;
```


But both will work when you do:

```dart
listOfMatched = []
```

**Comment by pavanpodila** [comment]
+1 to what @rrousselGit mentioned. Additionally it is worth thinking of MobX as a system that reports change in values. 

* When you mark something as `@observable`, you are hinting your interest in the change in value for that field. So anytime that field changes value, MobX will notify the reactions.
* A plain `List<T>` does not have observability built in. If you change the items, MobX cannot know that the list items changed. However an `ObservableList<T>` is aware of such changes, like adding, removal, modification of an item at an index, etc. 
* Use an `@observable List<T>` when you are sure you are only interested in reference changes to the entire list. 
* Use `@observable ObservableList<T>` when you not only care about reference changes to the list but also changes in the contents (add/remove/update).

HTH.

**Comment by rrousselGit** [comment]
Additionally, note that you can do:

```dart
List<Foo> foo = ObservableList<Foo>()
```

**Comment by dukaric1991** [comment]
And whats the difference between 
```dart
ObservableList<Foo> foo = ObservableList<Foo>()
```
and
```dart
List<Foo> foo = ObservableList<Foo>()
```
?

**Comment by pavanpodila** [comment]
Using it as `ObservableList<T>` is preferred as you want to be explicit about the type of the list. If you want to hide the specific type, go with the `List<T>` approach. Although the consumers of your code may not know that an `ObservableList<T>` is being used. This is good to h ide that detail for your consumers, say a third party library that only works with `List<T>`.
