### ISSUE TITLE
Add singleton decorator in mobx_codegen

### ISSUE THREAD

**Issue by aurbina83** [mobxjs/mobx.dart#143]
Currently I'm doing this to refer to my state as a singleton which works pretty good, but like mobx for React, if it were to just default as a singleton, it's helpful to not have to drill down arguments from a stateful widget.
```
import 'package:mobx/mobx.dart';

// Include generated file
part 'Counter.g.dart';

// This is the class used by rest of your codebase
class Counter extends TCounter {
  static final Counter _singleton = Counter._internal();
  factory Counter() {
    return _singleton;
  }

  Counter._internal();
}

class TCounter = _Counter with _$Counter;

// The store-class
abstract class _Counter implements Store {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}
```

```
import 'package:mobx/mobx.dart';

// Include generated file
part 'Counter.g.dart';

// This is the class used by rest of your codebase
class Counter = _Counter with _$Counter;

// The store-class
@singleton
abstract class _Counter implements Store {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}
```

**Comment by pavanpodila** [comment]
Hi @aurbina83, the use of singletons is an application level concept and not necessary from the perspective of MobX. You can keep this behavior in a separate package and use it inside your app. Generally, you should not need such singletons as testing it becomes a challenge and your components will become more tightly coupled with this singleton.

**Comment by pavanpodila** [comment]
Closing this for now
