### ISSUE TITLE
How to share a state?

### ISSUE THREAD

**Issue by NarHakobyan** [mobxjs/mobx.dart#145]
please update the documentation to see how we can share state between widgets?

**Comment by buncismamen** [comment]
is the example not enought for that?

you put something in the store
then feed the widgets that need the state with it

**Comment by ozum** [comment]
@NarHakobyan maybe **Using Providers to avoid Singletons** part of https://mobx.pub/guides/stores page helps.

**Comment by NarHakobyan** [comment]
@ozum thanks, Generally I need to have singlton state which will be available in whole application

**Comment by NarHakobyan** [comment]
For example to store user info

**Comment by ozum** [comment]
I didn't use provider before, but AFAIK it provides same instance down the widget tree. This lets you use it like it is a singleton. If there are no other reasons other than access same instance down the widget tree, you may give it a try.

**Comment by pavanpodila** [comment]
closing it for now
