### ISSUE TITLE
Widgets throw exception when assigned as observers without passing an observable property

### ISSUE THREAD

**Issue by kholdunn** [mobxjs/mobx.dart#149]
I'm extending flutter widget as an atom which passing default store properties to the native widget. And I'm passing properties to the atom to override widget properties. 
In some cases, I want to override all (default) properties, so, the observer widget won't have any observable properties.

Please refer to the [discussion](https://github.com/mobxjs/mobx.dart/pull/111#issuecomment-481292454) 

thanks

**Comment by pavanpodila** [comment]
@kholdunn do note that the assertion will **only fail during debug time**. In the release mode you will face any exceptions.

**Comment by pavanpodila** [comment]
Hi @kholdunn, I have changed this behavior now. Instead of throwing an assertion error, it will only log to the console. The new version of [flutter_mobx](https://pub.dartlang.org/packages/flutter_mobx) is published as well.
