### ISSUE TITLE
how to persist state from one screen to another ?

### ISSUE THREAD

**Issue by kunaldodiya** [mobxjs/mobx.dart#152]
I come from redux background, and very much new to mobx. but i guess this is amazing.. though only one thing that i want to know is,

how can i persist state while navigating from one screen to another, for example I have two screen ScreenA where there is a button which has increment method binded, on pressing as usual it increments the counter, but when i go to ScreenB, the state become 0 again, but in redux as far as i know i get the last updated value

How can i achieve this thing ?

**Comment by kholdunn** [comment]
@kunaldodiya are you implementing singleton?

**Comment by kunaldodiya** [comment]
@kholdunn yes

**Comment by kunaldodiya** [comment]
I think there is already one issue created for this. closing this one.. 
https://github.com/mobxjs/mobx.dart/issues/128
