### ISSUE TITLE
Observer is not reactive

### ISSUE THREAD

**Issue by kunaldodiya** [mobxjs/mobx.dart#154]
Hi, i am not able to get changes whenever observer value changes if it not direct,

For example i have 2 stores,

UserStore has method clickMe() and AuthStore has property isClicked
if i do something like, 

UserStore.dart
```
var userStore = UserStore();

class TestScreen extends State<TestScreenState> {
@override
  initialState(){
    userStore.clickMe();
  }
}
```

AuthStore.dart
```
@observer
isClicked = false;

@action
clickMe(){
isClicked = true;
}
```

so, now i want to listen for isClicked changes but its always static to false;

how can i achieve this thing ???

**Comment by pavanpodila** [comment]
Hope you are running the `build_runner` tool as described in the Getting Started guide. If possible, please share the repo. Also make sure your sdk version if `>= 2.1.0-dev < 3.0.0`. Check that the `mobx_codegen` is at least **0.1.0** in the `.packages` file.

**Comment by kunaldodiya** [comment]
I have confirmed all above.. but still not able to get reactive data, i only get changes if event is trigger from current page, if i indirectly call an event for example, if i call an action getAuth() which is in AuthStore that will trigger another action user.getAuth() which is inside UserStore, then i can not listen to changes in UserStore but if i call both auth.getAuth() i get latest data, user.getAuth() i get latest data, that's weird

**Comment by kunaldodiya** [comment]
main.dart

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:example_app/lib/src/store/user.dart';
import 'package:example_app/lib/src/store/auth.dart';

void main() {

  runApp(
    MultiProvider(
      providers: [
        Provider<UserBloc>(value: UserBloc()),
        Provider<AuthBloc>(value: AuthBloc()),
      ],
      child: MyApp(),
    ),
  );
}

**Comment by rborkhuis** [comment]
Can you explain how you solved this issue?
Im having the same problem.
