### ISSUE TITLE
Feature request: ObservableKeyMap

### ISSUE THREAD

**Issue by matthewlloyd** [mobxjs/mobx.dart#156]
ObservableMap is very useful. It would be nice to have a version where only the specific keys accessed within the Observer widget get watched. For example, if the Map is storing a dictionary of settings, an Observer that is watching `settings['setting1']` does not need to react if the value at `settings['setting2']` is modified.

**Comment by pavanpodila** [comment]
You could achieve this with a minor tweak to your design: Keep the observable keys in a separate map? That way you are explicit about what can be observed vs the plain keys.

It's just a suggestion.

**Comment by pavanpodila** [comment]
Closing this as there is no other feedback here
