### ISSUE TITLE
initState in mobx

### ISSUE THREAD

**Issue by kaarimtareek** [mobxjs/mobx.dart#157]
How can i fetch data from api first time the widget is built? 
the problem is i can only access the app state in the build method because of context parameter 
i want to do it in the initState , how can i achieve that??
`

class NewsPage extends StatefulWidget {
  final String catId;

  const NewsPage({Key key, this.catId}) : super(key: key);

  @override
  _NewsPageState createState() => _NewsPageState();
}

class _NewsPageState extends State<NewsPage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    AppState appState = AppStateProvider.of(context).appState;
    appState.fetchNewsUi(widget.catId);
    return Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(),
        body: Observer(builder: (context) {
          return appState.newsCatListModel.status == FutureStatus.pending
              ? Center(
                  child: CircularProgressIndicator(),
                )
              : appState.newsCatListModel.value.length == 0
                  ? Center(
                      child:
                          Text('No News Found', style: TextStyle(fontSize: 30)),
                    )
                  : ListView.separated(
                      shrinkWrap: true,
                      itemCount: appState.newsCatListModel.value.length,
                      separatorBuilder: (_, index) {
                        return Divider(
                          color: Colors.black,
                        );
                      },
                      itemBuilder: (_, index) {
                        return ListTile(
                          leading: Icon(
                            Icons.open_in_new,
                            size: 30,
                          ),
                          title: Text(appState.newsCatListModel.value
                              .elementAt(index)
                              .englishdescription),
                          subtitle: Text(appState.newsCatListModel.value
                              .elementAt(index)
                              .newsdate),
                          onTap: () {
                            Navigator.push(context,
                                MaterialPageRoute(builder: (context) {
                              return DetailsNews(
                                  newsCategoryModel: appState
                                      .newsCatListModel.value
                                      .elementAt(index));
                            }));
                          },
                        );
                      },
                    );
        }));
  }
}
`

**Comment by pavanpodila** [comment]
Very valid point @kaarimtareek. If we take a step back here, it looks like the store you want to work with has a lifetime dependent on the Widget's lifecycle. So why not create the `Store` instance in the `initState` of the `StatefulWidget` and dispose when done. You can provide this store for the sub-tree of the Widget. Is that the case?

If the Store lives longer than the Widget than someone else can trigger the operation on the `Store` before transitioning into the widget. That would behave exactly like the way you want, invoke some `Store` operation before Widget is rendered. 

Let me know if any of the above works for you.

**Comment by kaarimtareek** [comment]
I have already one instance of the **store** in the inherited widget , and creating multiple instances will lead to spread out the info of the store in multiple instances , so i think the second solution is more practical ,and another solution crossed my mind which is ,declare one instance  of the store at the store file and make it global , it may be not the best solution but i think it will work, i'll try both solutions and see how it'll go . 
Thanks for the amazing plugin by the way @pavanpodila

**Comment by pavanpodila** [comment]
If you use the [provider](https://pub.dartlang.org/packages/provider) package, you can get the store at all levels in the widget tree.

**Comment by pavanpodila** [comment]
Closing this out for now
