### ISSUE TITLE
Suggestions to improve 'Getting Started' Page

### ISSUE THREAD

**Issue by Dermotholmes** [mobxjs/mobx.dart#163]
The beginning of the 'Getting Started' document seems a little confusing to me as
- it's unclear if the direction is to start with a new flutter project or get a starting file from somewhere, and
- if the main.dart file contents should be replaced completely
-- if so, it seems this removes `main()` for most of the tutorial meaning the project can only be run at the end? If this is correct the first code block is not useful (it gets replaced at the end of the tutorial and is never run by the student) and potentially adds more confusion?

To remedy this, I'm suggesting instructions are made more explicit e.g. under the following headings...

> **Prepare**
> Before starting this tutorial make sure you have flutter [installed](https://flutter.dev/docs/get-started/install) and know how to [create a new flutter project](https://flutter.dev/docs/get-started/test-drive). 
> 
> **Tutorial setup**
> 1. Create a new flutter project
> 2. Replace the contents of the main.dart file with ... etc 
> 3. ...etc
> 
> **Install Dependencies**
> ...etc
> 

I'm happy to write this up better and send in a PR, just want to make sure I'm not misunderstanding the intention of that first code block?

P.s. I've also noted #73

**Comment by pavanpodila** [comment]
Hi @Dermotholmes those are very good points and I would be happy to look at your PR. Please send it over. If it removes the confusion, that would be a winner!

**Comment by Dermotholmes** [comment]
No worries, have sent through a suggestion https://github.com/mobxjs/mobx.dart/pull/170
