### ISSUE TITLE
[Question]What is the difference between a method with and without @action annotation?

### ISSUE THREAD

**Issue by thphuc** [mobxjs/mobx.dart#169]
Hi @pavanpodila again.

As the title, can you explain the difference?
I tried both approaches (with @action and without @action), they both work.

Thanks.

**Comment by pavanpodila** [comment]
I think this section will explain it better: https://mobx.pub/concepts#actions

In short, **actions** are meant to wrap mutations on observables. They ensure the notifications are only fired when an action completes. It gives you a nice semantic boundary for describing the mutations as well.
