### ISSUE TITLE
Is observable class too reactive?

### ISSUE THREAD

**Issue by alphamikle** [mobxjs/mobx.dart#171]
Hi there! Im intresting in question:
If i make observable class, like this -

`
  @observable
  CartModel openedCart = CartModel();
`

then, in action i change some props in openedCart, like

`
@action
changeCartTitle(String newTitle) {
  this.openedCart.title = newTitle;
}
`

Is this been reactive? Or i must do something like this:

`
@action
changeCart(CartModel newCart) {
  this.openedCart = newCart;
}
`

**Comment by pavanpodila** [comment]
if the `title` is an observable, it will be reactive, else the second option works.

**Comment by alphamikle** [comment]
@pavanpodila ok thanks, and can you answer, do it observable too:

`@observable
CartModel openedCart = CartModel();

@action changeCart(String someString) {
  var oldCart = this.openedCart;
  oldCart.someProp = someString;
  this.openedCart = oldCart;
}`

? or i must paste to abstract action only new modified classes?

**Comment by pavanpodila** [comment]
Use actions to encapsulate the mutations to observables. They give you a semantic way to naming those mutations and makes it easier to read the code
