### ISSUE TITLE
Mobx incorrectly believes I'm mutating state 

### ISSUE THREAD

**Issue by smkhalsa** [mobxjs/mobx.dart#175]
I have a store with the following state:

```
  @computed
  double get progress {
    if (duration == Duration.zero) return 0;
    return currentTime.inMilliseconds / duration.inMilliseconds;
  }
```
where `currentTime` and `duration` are both of type `Duration`.

When I try calling the progress property from within my Observer widget, I get an error with the following message:

> Side effects like changing state are not allowed at this point. Please wrap the code in an "action". Tried to modify: _PlayerStore.duration

**Comment by pavanpodila** [comment]
Somewhere in your code path you are mutating `duration`, which is why you are seeing this. Please trace the path to ensure

**Comment by smkhalsa** [comment]
@pavanpodila oops, you are correct. Thank you for the quick response. Closing now.
