### ISSUE TITLE
Should Store interface have a `dispose` method?

### ISSUE THREAD

**Issue by rrousselGit** [mobxjs/mobx.dart#176]
This is about the `Store` class from: https://github.com/mobxjs/mobx.dart/blob/5619ed2e21d717072da50febe9615fe2e6aee8e2/mobx/lib/src/api/annotations.dart#L25

This class is used as a base class for all custom mobx stores. As such, it is logical for libraries built on the top of `Mobx` to use the `Store` interface for object constraints.

Example:

```dart
class Foo<T extends Store> {
  // TODO: do something Mobx specific with T
}
```

At the same time, while many stores don't need to be disposed of, many do due to internal reactions like so:

```dart
class MyStore implements Store {
  ReactionDisposer _disposer;

  MyStore() {
    _disposer = when(something);
  }

  void dispose() {
    _disposer();
  }
}
```

____

The problem is, if library makers want to interact with stores (for example controlling when they are created/disposed), then these libraries won't be able to correctly dispose of stores with internal reactions.

So if `Store` looked more like this:

```dart
abstract class Store {
  void dispose() {}
}
```

That would allow libraries to make something like this:

```dart
class Example<T extends Store> extends StatefulWidget {
  const Example({Key key, this.builder}) : super(key: key);

  final T Function() builder;

  @override
  _ExampleState<T> createState() => _ExampleState<T>();
}

class _ExampleState<T extends Store> extends State<Example<T>> {
  T store;

  @override
  void initState() {
    super.initState();
    store = widget.builder();
  }

  @override
  void dispose() {
    store.dispose();
    super.dispose();
  }
}
```

Where this class handles both creation and cleaning up of a `Store`.

This is something that I'd like as an attempt to solve https://github.com/mobxjs/mobx.dart/issues/161 with `provider`.

**Comment by pavanpodila** [comment]
Totally agree @rrousselGit. PR ?
