### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [mobxjs/mobx.dart#18]
Hi Team !
I manage Awesome Flutter https://github.com/Solido/awesome-flutter 11000 stars.
I'd be really happy to have a slot for MobX in the state management section.
Please send a Request and you'll be added !

**Comment by pavanpodila** [comment]
That would be awesome @Solido. Will send one tomorrow

**Comment by pavanpodila** [comment]
@Solido I've sent in the PR. Please review. Closing this for now. Feel free to reopen if there are any changes needed.
