### ISSUE TITLE
Please at least add a changelog file or Github Release so we will know which part should I care

### ISSUE THREAD

**Issue by bang88** [mobxjs/mobx.dart#180]

**Comment by pavanpodila** [comment]
Agree @bang88. The changelog is under the mobx project: https://github.com/mobxjs/mobx.dart/blob/master/mobx/CHANGELOG.md. I'll be going and backfilling the previous versions as well for a history.

**Comment by bang88** [comment]
@pavanpodila Thank you. By the way how can we use the dispose method. I have code snippet can you help me out what should I add to dispose method.

```dart

abstract class _AppLineStore with Store, AppBaseStore<AppLineEntity>  {
  static ObservableFuture<AppLineEntity> emptyResponse = ObservableFuture.value(null);
  @observable
  ObservableFuture fetchFuture = emptyResponse;

  AppLineEntity data;

  dynamic originalRes;


  @computed
  HttpResponse<AppLineEntity> get raw => HttpResponse.fromJson(originalRes, data);

  @computed
  bool get hasData =>
      fetchFuture != emptyResponse && fetchFuture.status == FutureStatus.fulfilled &&
      raw != null;
  
  @observable
  bool loading = false;

  @action
  Future<AppLineEntity> getLine( AppLineParams params ) async {
    data = null;
    loading = true;
    try {
      final future =
          dio.get('/APP/Line', queryParameters: params.toJson());
      fetchFuture = ObservableFuture(future);
      final d = (await future).data;
			originalRes = d;
      data = AppLineEntity.fromJson(d['body']);
    } catch (e) {}
    loading = false;
    return data;
  }
  @override
  void dispose() {
    fetchFuture = emptyResponse;
    data = null;
    originalRes = null;
    loading = false;
  }
}

```

**Comment by pavanpodila** [comment]
The `dispose()` is most useful to dispose the reactions you setup in your store. Typically you may have some autorun() or reaction() setup in the constructor of the Store. To ensure they are cleaned up with no memory leaks, you should dispose them in the `dispose` method. HTH. 

In your case, you don't have to reset the fields like the way you have done in the dispose(). They will get cleaned up by the dart VM automatically. The dispose is mostly for proper cleanup of resources that you create in your Store, such as reactions, files, network connections, etc.

**Comment by bang88** [comment]
Thank you very much
