### ISSUE TITLE
Doesn't work with latest flutter snapshot in the master channel 

### ISSUE THREAD

**Issue by phtechgit** [mobxjs/mobx.dart#183]
I ran "flutter upgrade" and upgraded to 1.6.7-pre.45 (master channel)  and it broke mobx. There were issues related to some listener and interceptor api changes.

**Comment by thphuc** [comment]
Same here

**Comment by thphuc** [comment]
@phtechgit You can revert back to older version of Flutter in the meantime, by running this command: 

> flutter version 1.6.6

**Comment by gandhiwiria78** [comment]
thanks , back to old version flutter

**Comment by pavanpodila** [comment]
Master branch of flutter is in a flux and might be a temporary glitch.

**Comment by pavanpodila** [comment]
Dup of #184
