### ISSUE TITLE
Streams example 

### ISSUE THREAD

**Issue by wstrange** [mobxjs/mobx.dart#191]
This is related to #113  .  As a novice, it's not clear to me how to integrate streams using MobX.

The samples provided typically return a `Future<List>`- but things like FireStore often return a `Future<Stream<List>>`.

How should I structure my mobx application to use Streams? Should I just use a StreamBuilder?

**Comment by pavanpodila** [comment]
Ya, we need to build the example for that and other collections like `ObservableSet` and `ObservableMap`. Until then, can you [take a look at the tests](https://github.com/mobxjs/mobx.dart/blob/master/mobx/test/observable_stream_test.dart) to give some hints?:

**Comment by pavanpodila** [comment]
You can see this example here: https://github.com/mobxjs/mobx.dart/tree/master/mobx_examples/lib/random_stream.

Closing it for now.
