### ISSUE TITLE
how does annotation like @observable work in flutter?

### ISSUE THREAD

**Issue by weivea** [mobxjs/mobx.dart#196]
https://flutter.dev/docs/resources/faq#does-flutter-come-with-a-reflectionmirrors-system

**flutter.dev/docs** says:
Does Flutter come with a reflection/mirrors system?
Not at this time. Because Flutter apps are pre-compiled for production, and binary size is always a concern with mobile apps, we disabled dart:mirrors. We are curious what you might need reflection/mirrors for—please let us know at flutter-dev@googlegroups.com.

**Comment by pavanpodila** [comment]
You are right, the `dart:mirrors` package is not supported for Flutter to enable cross-platform targeting. We use the [`mobx_codegen`](https://pub.dev/packages/mobx_codegen) package to support annotations. This internally used [`source_gen`](https://pub.dev/packages/source_gen) and [`build_runner`](https://pub.dev/packages/build_runner) to accomplish the task.
