### ISSUE TITLE
Stack traces inside of Observers get eaten

### ISSUE THREAD

**Issue by izik1** [mobxjs/mobx.dart#197]
Title, the stack trace from any error produced inside of an `Observer` has its stack trace erased up until where the Observer throws it again.

ninja edit: This is made a lot more difficult by https://github.com/dart-lang/sdk/issues/10297, which says:
>You can't rethrow in a new stack frame, and we have no intention of making that possible. If you want to rethrow, you must do it inside the catch block. That is the only scope where the currently captured stack trace can be used in that way.

**Comment by abonander** [comment]
This rethrow outside `_reaction.track()` makes the emitted stacktrace useless: https://github.com/mobxjs/mobx.dart/blob/master/flutter_mobx/lib/src/observer.dart#L76

The language team appears to have no interest in making this pattern work: https://github.com/dart-lang/sdk/issues/10297#issuecomment-108365267

It's unclear to me why `_reaction.track()` needs to eat the exception in the first place; perhaps for this usage it could be overridden to allow exceptions to propagate outside the closure.

**Comment by pavanpodila** [comment]
That's a good point @abonander. I'll submit a PR today removing the catch and instead rethrowing it. I'll request your review so you can see if this would help in not swallowing the exceptions and yet be consistent.

We could also use the `disableErrorBoundaries` property to configure it but that requires we do it per-Observer using a custom `ReactiveContext`. This is an alternative that is possible to hide this behavior behind a flag.

**Comment by pavanpodila** [comment]
Please take at look at this PR: https://github.com/mobxjs/mobx.dart/pull/198

**Comment by pavanpodila** [comment]
This is now published: [flutter_mobx 0.2.2](https://pub.dartlang.org/packages/flutter_mobx)
