### ISSUE TITLE
Add spying and tracing capability

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#20]
Possibly have some integration with Observatory. Not sure if we can build plugins for Observatory which are MobX specific but worth exploring.

**Comment by katis** [comment]
I'm not sure, but I think you can interact with Chrome debugger and Observatory with https://api.dartlang.org/stable/2.1.0/dart-developer/dart-developer-library.html

**Comment by pavanpodila** [comment]
Done with #451
