### ISSUE TITLE
Adding an item to observable list not triggering computed that iterates over list.

### ISSUE THREAD

**Issue by omerman** [mobxjs/mobx.dart#203]
Hi,
I have this code

```
..
@observable
List myList;
..

@computed
List get something() {
return this.myList.map(fn).toList();
}
```

I set up an Observer that tracks the `something` compted.
it doesnt receive a change once I add an item to the list. it works only if I build a new list.

Not sure if this is a bug or not.

Help?

Thanks in advance!

**Comment by izik1** [comment]
I believe you're looking for an `ObservableList` https://pub.dev/documentation/mobx/latest/mobx/ObservableList-class.html

**Comment by omerman** [comment]
@izik1 
First of all thank you for your response.

I'm afraid that it's not a solution.
Also the specific example only works because the first item was already initialised..
the reason the autorun is triggered is because the item is modified using `list[index]`.
There is no example of `list.add(item)`..

**Comment by izik1** [comment]
the following should work, no?
```dart

@observable
ObservableList<int> list = ObservableList.of([]);

@computed
List get something() {
return this.myList.map(fn).toList();
}

@action
addToList(int number) => list.add(number);
```

**Comment by omerman** [comment]
Unfortunately it doesn't..

**Comment by pavanpodila** [comment]
I just tried it with an `Observer` and it worked just fine. Can you share the `Store` and `Widget` code?

**Comment by omerman** [comment]
@pavanpodila 
Hi, here is an example.

https://github.com/omerman/mobx-dart-issue-203

**Comment by pavanpodila** [comment]
In [this line](https://github.com/omerman/mobx-dart-issue-203/blob/master/lib/store/index.dart#L13), you should change to:

```dart
@observable
ObservableList<ListItem> list = ObservableList.of([ListItem(path: 'path1', anotherThing: 'anotherThing1')]);
```

let me know if that fixes it. Essentially, the plain `List` is not going to notify MobX whenever you add an item. An `ObservableList` will do it.

**Comment by omerman** [comment]
It did work.. and now I saw my problem in my codebase..

I had this code:

```
  @observable
  List<Route<T>> routes;

  _Router([this.routes]) {
    if (this.routes == null) {
      this.routes = ObservableList.of([]);
    }
  }
```

since I didn't change the type of `routes` member to be ObservableList,
I did something like this `new Router([...])` which made my main use case not to work, since I supplied `Router` with a plain `List` .

Thank you both @pavanpodila @izik1
