### ISSUE TITLE
Using 'with Store', the method cannot jump

### ISSUE THREAD

**Issue by huang-weilong** [mobxjs/mobx.dart#204]
My dependent version:
```yaml
dependencies:
mobx: 0.2.1+1
flutter_mobx: 0.2.3+1

dev_dependencies:
mobx_codegen: 0.2.1+2
build_runner: 1.5.2
```
I create a Store:
```dart
import 'package:mobx/mobx.dart';

part 'counter.g.dart';

class Counter = CounterBase with _$Counter;

final Counter counter = Counter();

abstract class CounterBase with Store {
 @observable
 int count = 0;

 @action
 void add() {
  count++;
 }
}
```
When I want to see where this method is used by Ctrl+left mouse button, it doesn't work:
![image](https://user-images.githubusercontent.com/37101820/59834472-a2e94300-937a-11e9-98ba-607dcac9f2dd.png)

If you replace `abstract class CounterBase implements Store` with `abstract class CounterBase with Store` it is normal
But using implements will get an error:
![image](https://user-images.githubusercontent.com/37101820/59834905-5e11dc00-937b-11e9-893b-ea2d90140fa9.png)
Even if I add the following code:
```dart
@override
void dispose() {}
```
This does not generate a `.g` file

So I want to confirm that the `0.2.1+1` version can only use `xxx with Store`, and the method can't jump? Is there a solution?

**Comment by pavanpodila** [comment]
Ya we changed from an interface to a mixin for the `Store`. This allows us to keep adding more base level methods like `dispose` / `toString` etc. later on without affecting the user code.

So please use the mixin based Store.
