### ISSUE TITLE
@observable should imply @action for the setter

### ISSUE THREAD

**Issue by csells** [mobxjs/mobx.dart#206]
It seems counter-productive and unintuitive to have a runtime exception when calling a setter on an @observable and ask people to write custom setFoo @action methods when the setter on the @observable is already being generated and can produce the correct @action behavior.

**Comment by csells** [comment]
It does seem like ReactiveConfig is made to allow me to change this policy:

MyApp() {
    // allow @observable setters to run
    mainContext.config = ReactiveConfig.main.clone(enforceActions: EnforceActions.never);
}

Unfortunately, there's a bug in the clone method where enforceActions is a bool instead of an instance of EnforceActions, so I can't actually run this code until that bug is fixed.

I do still wonder why the default for enforceActions is EnforceActions.observable, which causes exceptions to be thrown when the @observable setter is called. Is this a purity thing?

**Comment by csells** [comment]
Updating to the latest version solves this type problem but in the current version, while I am allowed to write the correct code to change the policy, it still fails at run-time:

```dart
MyApp() {
    // allow @observable setters to act
    mainContext.config = ReactiveConfig.main.clone(writePolicy: ReactiveWritePolicy.always);
}
```

A comment inside the code makes it clear that such a change in policy can't be allowed anyway:

```dart
void enforceWritePolicy(Atom atom) {
    // Cannot mutate observables inside a computed. This is required to maintain the consistency of the reactive system.
```

**Comment by pavanpodila** [comment]
The strict-mode message is a vestige from the MobX.js world. This should be corrected to the right jargon of MobX.dart. If you want to avoid this exception, you could set it to `ReactiveWritePolicy.never`, but I think based on our discussion, we should be generating the correct action-wrapper inside the setters.

**Comment by csells** [comment]
Ah. "strict-mode" must be the "don't ever allow observables to change", which is set with ReactiveWritePolicy.always. I read "always" as meaning "always allow" instead of "always throw" aka "strict-mode". After RTFM, I was able to get to the correct code on the latest version:

```dart
MyApp() {
    // allow @observable setters to act
    mainContext.config = ReactiveConfig.main.clone(writePolicy: ReactiveWritePolicy.never);
}
```

I am curious, however, if the generated setter for an @observable should write the change in the same kind of transaction that an action is wrapped it. What protections/semantics does it provide? Are they important for a setter? Reading the code, it doesn't seem so:

```dart
/// Internally MobX uses a 2-phase change propagation that ensures no unnecessary computations are performed.
```

That doesn't seem to apply in the setter case.

**Comment by pavanpodila** [comment]
The role of Actions becomes pivotal when you have observing reactions. If an action modifies a set of observables, it will only notify at the end of the action. This keeps the changes atomic and resulting in fewer notifications as well. It is also a performance optimization to avoid a noisy/chatty reactive system.

If a setter is called on its own, it can seem like an overhead to wrap in an action. 
> One possible solution is to take in an argument for the `@observable` annotation to make setters as actions. 

We haven't done this for all setters, as it adds unnecessary action wrapper and also encourages stray mutation of observables. However, I do see your point of convenience and DX getting compromised with a manual action wrapper.

@rrousselGit and @csells does that sound like a possible option?

**Comment by csells** [comment]
I definitely see the need for a global policy. I can see some developers who would want "strict mode", but I think it should be opt-in instead of opt-out. Perhaps a different default for the global write policy and then an argument to @observable to override the policy on a case-by-case basis? In that case, the argument to @observerable would default to follow the global policy.

**Comment by pavanpodila** [comment]
If I understand correctly, we should default to an _action-wrapper_ for all setters and have a _per-observable_ setting to **not have this wrapper**?

**Comment by pavanpodila** [comment]
In the latest update, I removed the "strict-mode" text in the exception 👍

**Comment by csells** [comment]
> If I understand correctly, we should default to an _action-wrapper_ for all setters and have a _per-observable_ setting to **not have this wrapper**?
> 
> The current default is set to `ReactiveWritePolicy.observed`, which means it will throw an exception if a mutation happens outside an action when that value is being observed by a reaction.

I was thinking about the run-time policy, but you're really asking about the compile-time policy. At compile-time, I think we should generate the action-wrapper by default in the codegen and provide an argument to @observable to turn it off as an optimization if you really know what you're doing.

**Comment by pavanpodila** [comment]
At runtime (in release mode) this won't be checked as this policy check is purely for debug-mode. We can do the action-wrappers by default with a setting to override on a case-by-case basis. I am wondering if that complicates the behavior?

**Comment by csells** [comment]
The simplest is to do away with the write policy and always use the action-wrappers.

**Comment by pavanpodila** [comment]
@csells, I have added this in [this commit](https://github.com/mobxjs/mobx.dart/commit/dcaa7d4e62a4b504a812778a7234f48d6d5d5103) and published as [`mobx 0.3.2 and mobx_codegen 0.3.2`](https://pub.dev/packages?q=mobx).

You can also see the simplification of the [`todo.dart`](https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/lib/todos/todo.dart) file where a `markDone()` action is no longer needed. 

Let me know if this is better.

**Comment by csells** [comment]
This is better. Can you apply this same logic to the observable collections? The semantics should be the same and the update simplifies the creation of data models with collections in them as well. 

As an example, in [my own Todo sample update](https://github.com/csells/mobx_fun/tree/master/lib/todo), I'm able to remove the addTodo and removeTodo methods from TodoList, using the ObservervableList directly from my AddTodo widget.

**Comment by pavanpodila** [comment]
I'll see how I can do this without sprinkling the conditional logic over all collection methods. Will think this over.
