### ISSUE TITLE
set value in Textfield from store

### ISSUE THREAD

**Issue by namaye** [mobxjs/mobx.dart#207]
Hi guys.
I have a `TextField `in my screen. The `store `fetches data from an Api. And to set the data to the `TextField `I am doing it like this:

                     Observer(
                          builder: (context) {
                            _servingQuantityController.text = store.servingQuantity;
                            return TextField(
                              controller: _servingQuantityController,
                              keyboardType: TextInputType.number,
                              style: TextStyle(fontWeight: FontWeight.bold),
                              decoration: InputDecoration(
                                border: UnderlineInputBorder(
                                  borderSide: BorderSide(color: Colors.grey),
                                ),
                              ),
                              onSubmitted: (val) =>
                                  store.setServingQuantity(val),
                            );
                          },
                        )

This does work, but the cursor moves to the beginning whenever I click it. Is there any other way to do this

**Comment by pavanpodila** [comment]
Please ask these questions on Gitter instead: [![Join the chat at https://gitter.im/mobxjs/mobx.dart](https://badges.gitter.im/mobxjs/mobx.dart.svg)](https://gitter.im/mobxjs/mobx.dart?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by namaye** [comment]
Sorry for the inconvenience. I am a newbie , i didnt knew about gitter. As the MobX version of dart is relatively new, whenever i ask these questions in stackoverlow I don't get any response. That's why I asked this here. Also thank for closing this.

**Comment by pavanpodila** [comment]
No worries @namaye

**Comment by ramsestom** [comment]
@namaye 
Seen on gitter that you found a solution for this but you didn't share this solution. So what is it? Because I have the exact same issue.

**Comment by marlls1989** [comment]
When you come from google, you land at this page. Please provide a link to the solution instead of simply saying to to some other site.

**Comment by Gerard-CK** [comment]
I have the exact same comment as @ramsestom and @marlls1989 above. Why not post the solution here?
So I did my own experimenting and came up with this:
Instead of using the TextEditingController text property, use the value property instead. It has an optional parameter that lets you specify where the cursor should be.

So instead of:
```_servingQuantityController.text = store.servingQuantity;```

do

```
_servingQuantityController.value = TextEditingValue(text: store.servingQuantity, selection: TextSelection.collapsed(offset: store.serviceQuantity.length - 1));
```

I hope this helps somebody.
