### ISSUE TITLE
Build a slick website showcasing the power of mobx.dart

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#21]
This is the marketing site + docs. I am thinking a site in [Gatsby](https://www.gatsbyjs.org/) would be good and easy to maintain over time.

**Comment by pavanpodila** [comment]
This is also a good time to revisit the logo, if needed

**Comment by rrousselGit** [comment]
FWIW docs.flutter.io is actually generated from dartdoc

**Comment by chimon2000** [comment]
Also important to note that flutter.io uses Jekyll.  

dartdoc seems like a good candidate if the idea is to maintain a consistent stack, generate documentation from comments, and minimize customization.  With the other options mentioned, documentation becomes a bit more explicit.  On the flipside, classes can potentially become quite [large](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_view.dart) when filled with examples & documentation.

**Comment by chimon2000** [comment]
@pavanpodila 

I have been building a site based off of the README updates, take a look at what I have so far:

https://well-cruiser.glitch.me/

Important things to note here is that this is 100% generated from README's so there is no need to fudge with any extra technologies (Gatsby, Vuepress, Docusaurus, etc.)

**Comment by pavanpodila** [comment]
@chimon2000 This looks great! Can we do any tweaks in theming and formatting?

**Comment by chimon2000** [comment]
Yes. I have not played around with the styling too much but it shouldn't be terribly hard. I will submit a PR.

The default styling is based off [Medium.css](https://github.com/lucagez/medium.css)
