### ISSUE TITLE
ObservableList does not call an observer when using map.

### ISSUE THREAD

**Issue by dotneet** [mobxjs/mobx.dart#211]
Please let me know if this is an expected behavior.

```dart
main() {
  var list = ObservableList<int>();
  list.add(1);
  reaction((_) {
    List<int> tmp = list.map((item) => item);
    return tmp[0];
  }, (msg) {
    print('not work');
  });
  reaction((_) => list[0], (msg) {
    print('work');
  });
  list[0] = 2;
}
```

**Comment by pavanpodila** [comment]
`map` returns an iterable, so you need a `toList()` to read the first element. Like so:

```dart
      List<int> tmp = list.map((item) => item).toList(growable: false);
      return tmp[0];
```

It should work with that change. Without the `toList()` you would have got a compile error:

```
error: The operator '[]' isn't defined for the class 'Iterable<int>'.
```

**Comment by dotneet** [comment]
Thank you! It works!
Curiously the command line version of dart did not display any errors.

**Comment by pavanpodila** [comment]
Strange, it shows errors for me in the editor itself

**Comment by rrousselGit** [comment]
The issue is that it's not a field, but a reaction that received the Iterable.
And reactions accepts just about everything. 

Maybe it'd make sense for Mobx to traverse iterables too.

**Comment by pavanpodila** [comment]
His code was accessing the first element: `tmp[0]`, which was already in error for me.

MobX does not do eager traversals. Its lazy and only creates an iterator relying on the ListMixin<T>. If you do a toList/forEach it will start observing. This was the semantics which was implemented by @katis

**Comment by rrousselGit** [comment]
It seems like the code has been edited. The original code did:

```dart
reaction((_) => list.map((item) => item), (msg) {
    print('not work');
  });
```


I'm not sure what's the best here. But that looks like an easy mistake.

**Comment by pavanpodila** [comment]
Aha...didn't know that part. I saw this issue after the edits then

**Comment by dotneet** [comment]
Thank you for discussing a lot for this issue.
It would be great if Mobx supports iterator and more methods.
I've test some code before I post this issue.
`List#forEach()` and `Map#values` cause same problem.

Adding a note about this issue to README.md would help a lot of developers.

**Comment by pavanpodila** [comment]
MobX does support those methods but you do have to use `toList()`. This was needed to support all of the iterator related methods as that's the semantics followed by dart as well. Dart and MobX are lazy iterators.

**Comment by rrousselGit** [comment]
Would an assert make sense?

```dart
assert(result is! Iterable || result is Map || result is List);
```

**Comment by pavanpodila** [comment]
Thing is the iterable methods are all on the `ListMixin<T>` and not overridable
