### ISSUE TITLE
Example of unit testing on MobX stores

### ISSUE THREAD

**Issue by namaye** [mobxjs/mobx.dart#212]
Is there any good examples on unit testing of MobX store?

**Comment by pavanpodila** [comment]
I am working on the example and also a guide. The example code will be put out soon.

**Comment by pavanpodila** [comment]
Take a look here: https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/test/todos_test.dart

Feel free to suggest if you see any specific type of test case missing.

**Comment by vandadnp** [comment]
I believe the up to date URL is: https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/test/widget_test.dart
