### ISSUE TITLE
A brand new design for the documentation site

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#214]
Create a set of wireframes for a new design of the documentation site

**Comment by irdevp** [comment]
![Web 1920 – 1@2x](https://user-images.githubusercontent.com/47428695/74996955-bb42bd80-5433-11ea-98a3-35fc632d6f3e.png)
Home Page

**Comment by pavanpodila** [comment]
This is cool stuff @irdevp. Would love to see an overall theme that we can use for home page and for docs. How about we try out Figma? Its free for upto 3 projects and 2 editors. Both of us can collaborate on that ? Let me know if you find this interesting.

**Comment by irdevp** [comment]
I'm very interested

**Comment by pavanpodila** [comment]
Just sent an invite to you on Figma. Once you accept, can you recreate your design over there? We can collaborate much better that way

**Comment by irdevp** [comment]
yep

**Comment by giri-jeedigunta** [comment]
I would love to collaborate on this too count me in :D

**Comment by pavanpodila** [comment]
closing it as we have updated to docusaurus
