### ISSUE TITLE
Write a set of examples for the public API

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#22]
This has been [requested already](https://github.com/mobxjs/mobx.dart/issues/4) but want to make this an explicit task.

These examples will also show up on the [pub site](https://www.dartlang.org/tools/pub/package-layout#examples), which is a great introduction to MobX.

**Comment by katis** [comment]
This is also needed to make sure that the library exports everything needed, in master the exports are missing things like `ObservableValue` and other core stuff :(

**Comment by pavanpodila** [comment]
I am still thinking the _least-friction-API_ is with the _builder-functions_. Thus `observable(10)`, instead of `ObservableValue(10)`. Still torn what is the right approach here.
