### ISSUE TITLE
FR: Add variant of reaction<T>() where previous value is also supplied to effect

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#222]
I was wondering if you might consider adding a variant of `ReactionDisposer reaction<T>` whose `effect` accepts the previous value of the `predicate`, as well as the new one.

If not, no big deal. I'll just go ahead and write it on my end.

And I'm really liking the library, so thanks. :)

**Comment by shyndman** [comment]
Actually...this isn't really what I want. I have to keep thinking about it. :)

**Comment by pavanpodila** [comment]
No worries, let me know how we can improve this library.

**Comment by smkhalsa** [comment]
@pavanpodila I do need this functionality. Is there currently any way to get the previous value in a reaction? Of course, I could keep track of this manually, but it would be nice to have it included in the reaction callback.

**Comment by pavanpodila** [comment]
This will be a breaking change on the signature for the reactions. I'll have to do it in the next major release. Will need to think if that's the right approach though

**Comment by smkhalsa** [comment]
@pavanpodila, maybe we can add an "observe" function [similar to in mobx.js](https://mobx.js.org/refguide/observe.html#observe) which provides access to both the new and previous value.
