### ISSUE TITLE
Set.removeWhere in Atom

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#223]
Hi again,

I was curious about this function in `atom.dart`

```dart
void _removeObserver(Derivation d) {
    _observers.removeWhere((ob) => ob == d);
    if (_observers.isEmpty) {
      _context._enqueueForUnobservation(this);
    }
  }
```

Why the `removeWhere`? In what cases would there be more than one equal entry in a `Set`?

**Comment by pavanpodila** [comment]
Good catch. There is no need for it! Some of this code was ported from the JavaScript side where such a call was used. I've removed it with the much simpler:

```dart
_observers.remove(d);
```

This will part of the next version update. Thanks!

**Comment by shyndman** [comment]
Huzzah!

**Comment by shyndman** [comment]
Also, I can't find your email anywhere. Can you shoot me an email?

**Comment by pavanpodila** [comment]
It's on pub page for the mobx package 🙃
