### ISSUE TITLE
Simplify Store creation with the @store annotation

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#225]
Based on the discussion in #217, we can simplify the Store creation with the use of an annotation: `@store`.

The ideal way given the code-gen constraints is to have something like this:

```dart
part 'counter.g.dart'; // This file will contain the _$Counter mixin

@store
class Counter with _$Counter {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }

}
```

The generated code will be as before with some slight changes on the mixin declaration:

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'counter.dart';

// **************************************************************************
// StoreGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names, unnecessary_lambdas, prefer_expression_function_bodies, lines_longer_than_80_chars

mixin _$Counter on Counter {
  final _$valueAtom = Atom(name: '_Counter.value');

  @override
  int get value {
    _$valueAtom.context.enforceReadPolicy(_$valueAtom);
    _$valueAtom.reportObserved();
    return super.value;
  }

  @override
  set value(int value) {
    // Since we are conditionally wrapping within an Action, there is no need to enforceWritePolicy
    _$valueAtom.context.conditionallyRunInAction(() {
      super.value = value;
      _$valueAtom.reportChanged();
    }, _$valueAtom, name: '${_$valueAtom.name}_set');
  }

  final _$_CounterActionController = ActionController(name: '_Counter');

  @override
  void increment() {
    final _$actionInfo = _$_CounterActionController.startAction();
    try {
      return super.increment();
    } finally {
      _$_CounterActionController.endAction(_$actionInfo);
    }
  }
}

```

@rrousselGit, can you confirm this is doable?

**Comment by rrousselGit** [comment]
It's not.
We need that `class Foo = Base with $Generated`. 

Mixins naturally don't override members of a class, which mobx needs to do for custom getter/setter

**Comment by pavanpodila** [comment]
Ah. So we are not really saving much, but the `@store` annotation is a good start.

**Comment by rrousselGit** [comment]
That's a lot more reasonable yes.

If we're going for tmsuch change, would it be possible to force `_$Base` to be `_$BaseStore`?

That would allow:

```
class Foo = Base with _$BaseStore, _$AnotherGeneratedMixin
```

**Comment by pavanpodila** [comment]
That might be a problem if you are defining multiple stores in the same file.

**Comment by csells** [comment]
Certainly requiring less code from the user is better, if we can do it. If we make any of these changes, I'm concerned with continued compatibility with other code generators, specifically [@JsonSerializable](https://pub.dev/packages/json_serializable).

**Comment by unimonkiez** [comment]
I wish mobx didn't have all this boilerplate on dart (talking about code gen and abstract classes).

Is there a road map for dart language and specifically a proposed feature that helps with this issue? Maybe we can speed things up. 🤔

**Comment by csells** [comment]
I'd like to see support in Dart for something that reduces the boilerplate here, too, @unimonkiez. How would you like it to work?

**Comment by unimonkiez** [comment]
Like mobx for javascript, for example
**Suggested**
```dart
import 'package:mobx/mobx.dart';

class CounterBase {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}
```
Instead of this (**Current**)
```dart
import 'package:mobx/mobx.dart';

part 'counter.g.dart';

class Counter = CounterBase with _$Counter;

abstract class CounterBase with Store {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}
```

**Comment by csells** [comment]
What features in Dart do you think we oughta have to enable that?

**Comment by rrousselGit** [comment]
Decorators that do something besides just purely meta-data

That would remove the need not only for the `class Counter = CounterBase with _$Counter;` but also the code-generator entirely.

**Comment by unimonkiez** [comment]
@csells I'm new to dart so I'm not sure, but I do know mobx for javascript uses [es6 proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) for achieving this clean code.

**Comment by csells** [comment]
I'm relatively new to Dart, too. The normal way to implement such functionality it via reflection at run-time, which we've stripped out of Dart to make it run as fast as the wind on mobile devices (and it does). The code generation solution, which uses type information at compile-time, is slightly less usable for far more efficient.

**Comment by rrousselGit** [comment]
es6 proxies aren't required. They could be useful for lists/maps. But overall that's not the issue.

MobxJS relies mostly exclusively on es5 decorators and without using anything that needs reflection.

As long as Dart offers a way for 3rd party objects to know when a getter/setter is called, mobx should be able to use that to remove the code-generator.

**Comment by unimonkiez** [comment]
@rrousselGit [Proxies are required](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#proxy-support).
@csells Then maybe automatic code generation / modification at build time.

**Comment by rrousselGit** [comment]
Proxy is used for maps and lists, not stores. Mobx.dart made a custom ObservableList/ObservableMap instead of Proxy.

**Comment by unimonkiez** [comment]
> Proxy is used for maps and lists, not stores. Mobx.dart made a custom ObservableList/ObservableMap instead of Proxy.

So what's stopping mobx.dart from ditching code gen and having nice api?

**Comment by pavanpodila** [comment]
It's mostly as @rrousselGit pointed out: for custom getter/setter injection on the observable fields. This is how we know track fields during reads and report changes during writes. This is mostly achieved with the annotations (aka decorators). However annotations in dart are pure metadata with no runtime logic (which is why we need code-gen for generating the runtime logic). If it behaved like decorators in JS, we would have got the behavior like you wanted.

One other case is for the use of actions, which also wrap the methods within a transaction. That too can be achieved with a decorator.

> **Bottomline**: If Dart's annotations behaved like decorators in JS, we can avoid all the boilerplate

**Comment by rrousselGit** [comment]
> One other case is for the use of actions, which also wrap the methods within a transaction. That too can be achieved with a decorator.

If you're thinking of:

```dart
final foo = action(() => {});
foo();

final bar = action((int a) => {});
bar(42);
```

Then that's not possible either. 


We can technically implement such `action`, using callable classes + noSuchMethod + Function.apply.
But that will never work type wise, so we always end up with a cast error instead. 

There's no way in dart to return a function that works for "any" function.

**Comment by shyndman** [comment]
Just putting it out there, but maybe a subclass will do the trick?

```
// User declares the private class
@store
class _Counter {
  @observable
  int value = 0;
}

// Generator produces a public subclass
class Counter extends _Counter {
  // mobx stuff...
}
```

**Comment by rrousselGit** [comment]
@shyndman  It's considered bad practice.
The main issue is that it will confuse toolings.

Things like "go to definition", dartdoc, or refactorings like "rename" will break.

Although it's technically possible to correct these with a custom analyzer plugin.

**Comment by shyndman** [comment]
Aren't those problems with the existing approach as well (at least in VSCode)? Jump to definition goes to the generated code first, and doc comments don't appear to be inherited.

I'm not sure about renaming though. It should work alright in either case.

**Comment by shyndman** [comment]
Thoughts @rrousselGit, @pavanpodila?

**Comment by pavanpodila** [comment]
@shyndman I am ok generating a public class via the codegen. However as @rrousselGit pointed out, there might be some sanity issues due to the hidden nature of the public facing class. Ideally these public facing classes should be in user-land. 

I think this is also a viable approach. If we do need to make some changes, we could do that by extending the generated class.

```dart

// counter.dart
@store
class _Counter {
  @observable
  int value = 0;
}

class CustomCounter extends Counter {
  // more customization if needed
}
```

```dart
// counter.g.dart
// Generator produces a public subclass
class Counter extends _Counter {
  // mobx stuff...
}
```

@shyndman Do you want to take a stab at creating this version of the codegen ? I really like the ergonomics of `@store` that is enabled by this approach ❤️ .

**Comment by shyndman** [comment]
Oh, apologies @rrousselGit. I misunderstood. Go-to-definition and renaming of the _classes_. Got it. I had fields in my head.

@pavanpodila, sure. I assume that this new approach should exist in addition to the existing one?

**Comment by pavanpodila** [comment]
@shyndman I think it would be good to try this out on a branch and see how it works for various use cases. If it works for a majority of the cases (barring the one for tooling), we could pull this into master as an experimental option

**Comment by shyndman** [comment]
sg.

That first PR is only tangentially related. Just getting my feet wet.

**Comment by hramnathnayak** [comment]
@pavanpodila @rrousselGit @shyndman  This is exciting ... as mentioned on #129 I have been looking for ways to be able to generate the code in the @Store as well ( currently abstract class X with Store) from an open api specification exposed by the swagger tool and at the same time allow for more customizations for @computed properties but keep this generated @Store code separate . This change I believe will allow me to do that.

//Generate the @store from an open API specification using the swagger codegen or openapi codegen //https://github.com/OpenAPITools/openapi-generator
// counter.dart
@store
class _Counter {
  @observable
  int value = 0;
}

// This class can be moved to its own file and separated from the generated @Store
class CustomCounter extends Counter {
  // more customization if needed
}


// counter.g.dart
// mobx Generator produces a public subclass
class Counter extends _Counter {
  // mobx stuff...
}

**Comment by pavanpodila** [comment]
Looks there is some merit to creating a public class inside the generated file (*.g.dart) ? Agree it may not be a good practice but if there are real benefits, we should push this forward

**Comment by shyndman** [comment]
Great. I'll have a PR by EOD.

**Comment by pavanpodila** [comment]
We have it working now. Need to iron out last few kinks. #248, #271, #272, #273, #274. We will pick rest of the issues in separate ones.
