### ISSUE TITLE
Add error handling and recovery

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#23]
This will be mostly inspired from [MobX](https://mobx.js.org).

**Comment by katis** [comment]
Found the PR that added better error handling in Mobx JS https://github.com/mobxjs/mobx/pull/736

**Comment by pavanpodila** [comment]
There is still more work on this such as:

- Disabling the error boundary at the global level
- Adding global `onReactionError` hook

**Comment by pavanpodila** [comment]
Some of this is being handled in #33

**Comment by pavanpodila** [comment]
Completed as part of #33
