### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by jascodes** [mobxjs/mobx.dart#231]
I reckon this is very new project, so was wondering what you guys think about performance at this stage. Is too worse or at par from other solutions? Should I use this in production application.

Thx

**Comment by pavanpodila** [comment]
Hi @jascodes, we haven't run perf benchmarks yet against other frameworks yet. However folks who are using in production have not complained (yet). That said, we have ported the code in such a way that it retains all the performance characteristics of the JS version of MobX. 

I would love to hear your views on how to make some realistic performance tests, which can prove this out.

**Comment by jascodes** [comment]
I rearly write tests myself :P So wrong guy to ask.

Thx for getting back and for the awesome package which I will report back after trying out in my production app(just gonna wing it).

Thx
