### ISSUE TITLE
ObservableSet reports change whether or not a mutation took place

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#232]
Example: https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/api/observable_collections/observable_set.dart#L65

Is that intentional?

**Comment by pavanpodila** [comment]
Again a great find @shyndman. Can you please go through rest of the collection code to ensure we are not reporting unnecessarily? How about a PR 👍 ?

**Comment by shyndman** [comment]
Sure! I'll take a look tomorrow.

**Comment by pavanpodila** [comment]
Fixed some of those methods, esp. `add` and `remove`. I think we are covered for now. Let me know if you find others.

**Comment by shyndman** [comment]
Nice! Thank you.

I think this requires a bit of discussion.

List already does a value comparison in `operator []=`, here:
https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/api/observable_collections/observable_list.dart#L88

Map doesn't do comparison with the previous value, but could:
https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/api/observable_collections/observable_list.dart#L88

But which is right? Which behavior is least surprising to a user of an API? 

An equality comparison can be an expensive, and does the user expect that one is taking place during `[]=`? Or do they not even care, because it's more important to minimize the reporting of change to the context?

**Comment by pavanpodila** [comment]
I think we should make this consistent for now. Equality comparison can be plugged in as a comparer in a later release. Thanks for pointing this out! Keep going 😄

**Comment by pavanpodila** [comment]
All these changes are now in master and pushed the latest pub release [0.3.4](https://pub.dev/packages/mobx).

**Comment by shyndman** [comment]
If that's the plan, I want to give that detail some attention in the class comments. It makes ObservableList and ObservableMap a slightly different data structure. I'll send a PR tomorrow.
