### ISSUE TITLE
Can state changes be reported centrally?

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#233]
This may be a requirement of #20, but I'm wondering — can state change reporting be centralized in some way so that it can be easily observed globally (or...within a specific context).

I can't see any way to do this at the moment with generated code. Atoms simply don't provide enough information to the context.

I could model everything with actual `Observable` instances, and have them wired up to report change as I see fit, but I feel like that hurts the usability somewhat — I like how your codegen works, and it'd be cool if I had a little bit more control.

**Comment by pavanpodila** [comment]
For spying we will be building it by injecting specific spy functions in various places. For the most part, we will model the approach taken by mobx.js

**Comment by shyndman** [comment]
OK, cool. I'll figure something out on my own. Thank you.
