### ISSUE TITLE
Initialize asynchronous values

### ISSUE THREAD

**Issue by gaku-sei** [mobxjs/mobx.dart#237]
Is there a simple way to initialize observable fields asynchronously?

I have a simple form that has to be pre-filled with data coming from the storage:

```dart
abstract class _FormStore with Store {
  @observable
  String value = "";

  @action // Is the decorator even needed here?
  Future init() async {
    final prefs = await SharedPreferences.getInstance();

    value = prefs.getString(key);
  }
```

In my stateful widget containing the form, I have the following code:

```dart
  _FormState() {
    formStore.init().then((_) {
      textFieldController.text = formStore.value;
    });
  }
```

It works but I feel like it's a very "hacky" solution. Is there a better way to handle this kind of cases?

**Comment by yaymalaga** [comment]
In general I use the initstate method to call the asynchronous function. However, as you can't use await there, you could also create a constructor and call the async function directly.

The decorator is necessary as you are modifying an observable. You can also pass the controller to the function so when it finishes it can update the text. Moreover, you can make use of a loading progress bar, so you show the UI once the data is already retrieved.

**Comment by MaikuB** [comment]
May not be too your liking but I call `await SharedPreferences.getInstance()` as part of `main()` and then pass the instance to where it's needed. An example can be found  [here](https://github.com/MaikuB/flutter_app_templates/blob/master/material_bottomnavigation_provider_mobx/lib/main.dart)

**Comment by afrish** [comment]
This is a very common scenario. I have multiple stores that I'm trying to migrate to MobX, but many of them need to be initialized asynchronously, like reading persistent state from a local mobile database. Is the approach descirbed above the best here? Does it mean I'm basically creating an empty store first (which is inconsistent at this point) and only then I'm able to apply the data via an action? I cannot believe nobody had this problem, it must have been already solved somehow
