### ISSUE TITLE
mobx won't generate types generated by other generators

### ISSUE THREAD

**Issue by VadimOsovsky** [mobxjs/mobx.dart#246]
the generator replaces all types generated by other generators like `final CustomGeneratedClass foo` with `final dynamic foo`

e.g.
`File` comes generated by the Moor library from `FilesTable`
```
  @observable
  List<File> currentFiles;
```
is generated to
```
  @override
  List get currentFiles {
    _$currentFilesAtom.context.enforceReadPolicy(_$currentFilesAtom);
    _$currentFilesAtom.reportObserved();
    return super.currentFiles;
  }
```

**Comment by pavanpodila** [comment]
This appears to be a limitation of `build_runner` / `source_gen` where it is not able to resolve the types  and thus falls back on `dynamic`.

**Comment by VadimOsovsky** [comment]
@pavanpodila any solution so far?

**Comment by pavanpodila** [comment]
Can you try an approach like this: https://mobx.pub/guides/output#wrap-dartui-types-to-avoid-code-gen-issues

**Comment by shyndman** [comment]
@VadimOsovsky, this should now be fixed. Please re-open if this is not the case.

**Comment by dyardy** [comment]
Was there a resolution to this problem? (that mobx won't generate code based on other generated code) i.e. drift(moor) with mobx

**Comment by fzyzcjy** [comment]
What about moving that custom type to a new file
