### ISSUE TITLE
Enforce ObservableMap key type

### ISSUE THREAD

**Issue by Vardiak** [mobxjs/mobx.dart#253]
In the definition of the [] operator on an ObservableMap, the type of the key is not forced and can be any object, which can cause problems at runtime after a refactoring.

```
  @override
  V operator [](Object key) {
    _context.enforceReadPolicy(_atom);

    _atom.reportObserved();
    return _map[key];
  }
```

**Comment by pavanpodila** [comment]
Good point 👍. Would you be able to send in a PR ?

**Comment by shyndman** [comment]
Closing alongside PR.
