### ISSUE TITLE
Final decision on integration between MobX and fluter_hooks

### ISSUE THREAD

**Issue by PavelPZ** [mobxjs/mobx.dart#255]
I mentioned a few topics regarding integration with @rrousselGit [flutter_hooks](https://github.com/rrousselGit/flutter_hooks) package, e.g.
* https://github.com/rrousselGit/flutter_hooks/issues/83
* https://github.com/mobxjs/mobx.dart/issues/70
* etc.

Some of them are already closed, others are still open, I am not well oriented in them. 

What is the final decision on this integration?

**Comment by rrousselGit** [comment]
That's in my todo-list but it's low in priority.

If you need it, consider making a PR on `flutter_hooks` repository.
Alternatively, I'll work on it during Q4.

**Comment by frank06** [comment]
I'm very interested in this!  Any updates?

**Comment by rrousselGit** [comment]
First, I must finish the v4.0.0 of provider
Then I'll tackle things about flutter_hooks

It's low in priority though. There are more important features that `flutter_hooks` needs, like an eslint-like plugin to warn of mistakes; a debug tool; refactoring; ...

**Comment by frank06** [comment]
Thank you @rrousselGit for such awesome tools. I particularly enjoy hooks as it dramatically removes boilerplate. I had a look at that branch and it's too complex for my Flutter internals knowledge at the moment. I will level up and try to help you with that.

**Comment by PavanGangireddy** [comment]
I'm very interested in this! Any updates?

@rrousselGit
