### ISSUE TITLE
Observer is suppressing Flutter exceptions in its Reaction

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#259]
I ran into an issue where `_ObserverState._invalidate` was throwing, but I wasn't finding out about it because it was being suppressed by the Observer's reaction. It resulted in a bug that was a little tricky to track down.

Maybe `Observer.createReaction` should provide an `onError` when it creates the reaction? Something that logs?

**Comment by pavanpodila** [comment]
Agree on adding an `onError` parameter. Can we take this up in a PR ?

**Comment by shyndman** [comment]
👍

**Comment by shyndman** [comment]
Do you think that maybe we should rethrow the error in this specific instance? It does indicate a pretty major problem. Enough that Flutter threw the error in the first place.

**Comment by pavanpodila** [comment]
Ya rethrow is not going to give you the stack trace. Also rethrows only work inside a catch clause making it difficult surface the error from a different location. I tried this in the past with not much success.

**Comment by pavanpodila** [comment]
I think our best bet is to use `onError` and probably use a default reporter at the application layer.

**Comment by shyndman** [comment]
Closed via #285
