### ISSUE TITLE
Consider naming Observers indicating the location of the constructor invocation

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#262]
We were having some trouble figuring out which Observers were which, based on their default names (`Observer@{id}`), so we came up with an alternate way of naming them that indicates where the Observer is created.

We've found it useful. Just putting it out there.
```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_mobx/flutter_mobx.dart' as mobx;
import 'package:mobx/mobx.dart';

/// Returns a new MobX [Observer].
///
/// If [name] is not specified and asserts are enabled, the returned
/// [Observable] will be named in a way indicating the source location of the
/// caller.
mobx.Observer Observer({
  @required WidgetBuilder builder,
  Key key,
  ReactiveContext context,
  String name,
}) {
  assert(() {
    name ??= 'Observer\n${StackTrace.current.toString().split('\n')[2]}';
    return true;
  }());

  return mobx.Observer(
    key: key,
    builder: builder,
    context: context,
    name: name,
  );
}
```

**Comment by pavanpodila** [comment]
How does the name look like ?

**Comment by shyndman** [comment]
It's a stack frame. You can even click it in VSCode.

**Comment by shyndman** [comment]
Takes you right to where the `Observer` was constructed.

**Comment by shyndman** [comment]
It's a little weird, I admit, but I thought it was sort of cool so I wanted to put it out there.

**Comment by pavanpodila** [comment]
Neat idea, let's do it in a PR!

**Comment by Solido** [comment]
The fact that you can navigate using the tooling make this mandatory !

**Comment by pavanpodila** [comment]
When can we get this :-)

**Comment by shyndman** [comment]
I'm a little tied up, but that snippet is basically the entire PR. You can go ahead and commit it. I don't mind. :)

**Comment by pavanpodila** [comment]
Apologies, I don't indulge in plagiarism, even when allowed :-)... take your time, this 3-pointer is all yours

**Comment by pavanpodila** [comment]
Pushed to master in this commit: 46b0ee9. Let me know if it looks good

**Comment by shyndman** [comment]
I don't think that will work, because two frames up the stack is `initState()`. That's what calls `createReaction()`.

**Comment by pavanpodila** [comment]
Ah so we do need a subclass?

**Comment by shyndman** [comment]
yeah, or a wrapping function like I have above.

Haven't tried it, but this might work for the subclass
```dart
String _defaultObserverName() {
  String name;
  assert(() {
    name ??= 'Observer\n${StackTrace.current.toString().split('\n')[3]}';
    return true;
  }());
  return name ?? 'Observer';
}

class HelpfulObserver extends Observer {
  HelpfulObserver({
    @required WidgetBuilder builder,
    Key key,
    ReactiveContext context,
    String name,
  }) : super(
          key: key,
          builder: builder,
          context: context,
          name: name ?? _defaultObserverName(),
        );
}
```

**Comment by shyndman** [comment]
Actually, changing Observer's constructor might not work. Subclass should work though.

**Comment by pavanpodila** [comment]
I would prefer to do this in the constructor so there is no switching between one type of Observer over other. It would just work without any change from the developer. If we relax two constraints we could pull it off:

- Remove the const constructor constraint, so no `const Observer()`
- Make the `name` field non-final

With that, I can then do:

```dart
  Observer({@required this.builder, Key key, this.context, name})
      : assert(builder != null),
        super(key: key) {
    this.name = name ?? _defaultObserverName(context);
  }

```

Thoughts, @shyndman, @rrousselGit ?

**Comment by shyndman** [comment]
To me that seems like a reasonable trade-off, since the field is effectively final.

**Comment by pavanpodila** [comment]
Ya, I've checked this code into master. I do feel this is very useful and should be in. Will publish a new version on pub

**Comment by pavanpodila** [comment]
`0.3.1` is up with this change: https://pub.dev/packages/flutter_mobx

**Comment by shyndman** [comment]
Nice. Closing this off.
