### ISSUE TITLE
@store annotated classes cannot reference other @stores

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#268]
If a `@store` references other stores in its `@observable`s, return types, or parameter types, their types are not recognized and get generated as dynamic.

For example
```dart
@store
class _Car {
  @observable
  Engine engine;
}

@store 
class _Engine {
  @observable
  int pistonCount;
}
```
is generated as
```dart
class Car extends _Car {
  dynamic get engine { ... }
  set engine(dynamic value) { ... }
}
```
Which makes sense — the analyzer can't analyze a type before it's been generated.

That said, we can get around this by looking directly at the AST, and using the type name the user wrote.

_Unfortunately_, the `build` package doesn't make this easy on us. `CompilationUnit` (the AST root) isn't exposed by the `Element` in this environment...but that doesn't mean we can't re-compute it.

In essence, the solution might be something like this (for the example above):
```dart
// element is the FieldElement

// Parse the file, without resolving types (we'd cache this tree)
final result = parseFile2(
  path: element.source.fullName,
  resourceProvider: element.session.resourceProvider,
  featureSet: FeatureSet.fromEnableFlags([]),
);

// Find the AST node belonging to the element we're evaluating. If it's a field, 
// this will find a SimpleIdentifier node.
final nameNode = NodeLocator(element.nameOffset).searchWithin(result.unit);

// Walk up the ancestry to find the node that contains type information
final variableNode =
    nameNode.thisOrAncestorMatching((node) => node is VariableDeclarationList);

// Grab the type, as the user wrote it. If it works, it works, if it doesn't, it 
// doesn't. Their problem.
variableNode.type.toString(); // "Engine"
```

It won't be a ton of code, and I'd be surprised if there was a noticeable performance difference (parsing is cheap). But it's your call whether or not it's worth it.

Oh, and notably, this will resolve problems encountered with `dart:ui` types as well.

**Comment by pavanpodila** [comment]
Let's give it a shot. Hard to predict the perf impact unless we actually do it. Few questions:

- How will this work with the `build_runner`
- Where do we plugin this code and on what conditions

**Comment by shyndman** [comment]
> How will this work with the build_runner
It _should_ just work. I have something basic running locally.

> Where do we plugin this code and on what conditions
Any time we care about the type of something, and find that it's `dynamic`, we'd perform this second style of lookup.

If that sounds good, I'll throw together a strawman.

**Comment by pavanpodila** [comment]
Sounds good. Strawman awaited!

**Comment by shyndman** [comment]
This is the start of the general idea, unpolished and unoptimized:
https://github.com/mobxjs/mobx.dart/commit/6da968e75f63b1c69494f113a6fc04f87c78a3f2

One hiccup is I'd like to impose an additional restriction on how stores are declared, to avoid complexity. You won't be able to write this:

```dart
@store
class _Car {
  @observable
  var engine = Engine(); // No. Type inference won't cut it
}
```

A type annotation will be required:
```dart
@store
class _Car {
  @observable
  Engine engine = Engine(); // This is good
}
```

**Comment by pavanpodila** [comment]
That's fine. Let's make it work and then we can relax constraints later

**Comment by pavanpodila** [comment]
Also we can throw an error for such declarations

**Comment by shyndman** [comment]
You take a look at the code? Thoughts?

**Comment by pavanpodila** [comment]
Not yet. Away from computer right now

**Comment by shyndman** [comment]
kk

**Comment by shyndman** [comment]
I guess I'm looking for a bit of high-level feedback on the code before I go further (because the basics do work). 

Does it seem weird to you? Too complicated? Any concerns?

**Comment by hramnathnayak** [comment]
@shyndman I gave the @store option a quick try last night... I had the store generated with the json serialization option... The named constructor generated (Mystore.fromJson) called the default super class constructor and it gave a compilation error...

Posting this from my phone... But I will post some code snippets later today if you need more clarification on what I am referring to...

Thank you for the awesome work in getting this ready to test ...  I can help test and provide feedback...

**Comment by shyndman** [comment]
Thanks @hramnathnayak . That's a new one. I'm putting together a PR right now.

**Comment by shyndman** [comment]
Check this out: https://github.com/mobxjs/mobx.dart/commit/8a761ec5826f6fdd4e28a58abedd6a9884e11d81

I think that's it. Shows support for prefixed types (ui.Color), nested generics, type parameter bounds. Just need to add some comments and an AST cache.

**Comment by hramnathnayak** [comment]
@shyndman Since we need the named constructor MyStore.fromJson to return an instance of MyStore we will need the constructor declared as a factory constructor. Also using super to call the private class constructor give me a compilation error. I believe we need to use arrow with the explicit name of the private class named constructor something like below on the generated class.

`factory MyStore.fromJson(Map<String, dynamic> json) => _MyStore.fromJson(json);`

**Comment by shyndman** [comment]
Hm, interesting. Let me think about it for a few.

**Comment by shyndman** [comment]
Mind filing a separate issue?
