### ISSUE TITLE
@store annotation with JsonSerializable Generated class named constructor issue

### ISSUE THREAD

**Issue by hramnathnayak** [mobxjs/mobx.dart#277]
when using the @store annotation and @JsonSerializable() on the private class the named constructor on the generated class should be declared a factory constructor as we need it to return an instance of the store. Also using super.fromJson gives a compilation error.

@shyndman sorry about hijacking the other thread and thank you for the awesome work. here is a separate thread for tracking the named constructor issue.

**Comment by shyndman** [comment]
No problem on the hijack. :)

OK...so this one could be a problem with this `@store` approach. I can't see a clean way through. I'm going to keep thinking about it.

**Comment by shyndman** [comment]
The only way I can see to do this is something like this, but I don't like it:

```dart
factory MyStore.fromJson(json) {
  _MyStore tmp = _MyStore.fromJson(json);
  // Copy each property from tmp into a new store of the correct type
  return MyStore(
    foo: tmp.foo,
    bar: tmp.bar,
  );
}
```
But that's pretty crappy.

I feel like `@store` style might be dead in the water.

**Comment by shyndman** [comment]
Any ideas @pavanpodila?

**Comment by pavanpodila** [comment]
Can we do some forced casting for the time being ?

**Comment by shyndman** [comment]
Unfortunately not, because the `@JsonSerializable` factory is creating an instance of the private class, but we require an instance of the public one. Cast will fail.

**Comment by pavanpodila** [comment]
I think we will have to leave out this use case. Don't see a solution right now.

**Comment by shyndman** [comment]
Are we still convinced that `@store` is an acceptable path? We could always pull it out.

**Comment by pavanpodila** [comment]
Yes, I think `@store` is viable. One small tweak we can do for now is to use `@store` for mixin based code:

```dart
class Counter = _Counter with _$Counter;
@store
class _Counter {}
```

Not a big saving but removes the need for a `Store` type

**Comment by hramnathnayak** [comment]
@shyndman @pavanpodila  Could we use dart extensions to solve our issue with returning instance of the original class with the factory constructor for MyStore.fromJson ?
https://youtu.be/D3j0OSfT9ZI

**Comment by pavanpodila** [comment]
Not sure, but worth a shot. I think you can try this in your application code. If it works, we can pull it into mobx

**Comment by hramnathnayak** [comment]
I guess if we are taking the direction if repurposing the @store annotation for auto inferring as mentioned in #219 and remove the @store in its current form as mentioned in #347 I guess we could close this issue.

**Comment by shyndman** [comment]
Thanks @hramnathnayak. Sorry this didn't work out.
