### ISSUE TITLE
Can I do autorun in builder?

### ISSUE THREAD

**Issue by jascodes** [mobxjs/mobx.dart#289]
I have provider object (mobx store) in builder function. I want to monitor that. Right now in store constructor I have autorun wired up. Is doing inside widget possible?

Thx

**Comment by pavanpodila** [comment]
If you have a `StatefulWidget`, you could do in the `initState()`

**Comment by jascodes** [comment]
@pavanpodila Thx for getting back, but can I get store from provider in initState?
Only way I guess right now might be with binding after layout render. https://pub.dev/packages/after_layout

**Comment by pavanpodila** [comment]
Ah yes, I forgot about that. @rrousselGit can we pull a `Store` from `Provider` inside `initState`?

**Comment by rrousselGit** [comment]
```dart
Provider(
  builder: (_) => MyStore(),
  dispose: (_, store) => store.dispose(),
)
```


As for obtaining the store inside `initState` you can do:

```dart
initState() {
  Provider.of<MyStore>(context, listen: false);
}
```

**Comment by jascodes** [comment]
Thx a bunch guys!! really helpful.
