### ISSUE TITLE
Move to monorepo

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#29]
This will house various packages and make it easy to maintain:

### Core
- **mobx.dart** (primary project)
- **flutter_mobx** (flutter bindings)
- **mobx_generator** (will contain code generator. Name is not final)
- **flutter_mobx_hooks** (hooks driven state management)
- **website** (public facing website, possibly hosted on github.io.)

### Experimental

- **mobx_observatory** (_experimental_ tool for visualizing the internals of MobX as it runs an app. This will be possible if we run a tiny _web-server_ with _web-socket_ that posts messages when various events occur inside MobX. It will also expose a `localhost` url that can be opened in Chrome to see the visualization. The visualization itself can be built with React 🤓. Think of this as the Observatory for MobX )

**Comment by rrousselGit** [comment]
I can potentially help for the flutter sides if needed. 😄

**Comment by pavanpodila** [comment]
Awesome @rrousselGit. I think this will speed up the move to monorepo as well. Ideally this code should live in the **`flutter_mobx_hooks`** project. 

🤔 One other option is you can create the hooks code in a separate folder to get started. Once you have something work, we can extract it out to `flutter_mobx_hooks`. 🤔

**Comment by katis** [comment]
I can try to tackle this after work. [`mono_repo`](https://github.com/dart-lang/mono_repo) seems to be used by few projects.

**Comment by rrousselGit** [comment]
the issue with mono_repo is that is doesn't support flutter yet. I made a PR so that it won't crash, but it doesn't automatically download the Flutter sdk and run commands.

This is still doable by using `command:` in the yaml, and manually filling the gap though.

**Comment by pavanpodila** [comment]
Do we even need separate repositories ? I suggest we keep the packages together under this repo and publish separately? I think maintenance is much easier if they are all together. At least at this stage where the packages are still maturing. What say?

**Comment by pavanpodila** [comment]
And agree about skipping the whole `mono_repo` dependency. We can add that later if it works out.

**Comment by katis** [comment]
You are of course right about the ease of maintenance from a cross-package point of view, but Travis configuration becomes a problem. With a single package repository the ready made configs of `language: dart` work well, but with multiple packages you have to write the scripts yourself. I'm not that familiar with Travis, so I couldn't figure out how the config would work. If you want to try, you're welcome, but I'm out of ideas.

**Comment by rrousselGit** [comment]
I would heavily suggest to send a mail to Flutter this.

Because the community has been small until now, Flutter team haven't really noticed the monorepository issue.

**Comment by pavanpodila** [comment]
I think in principle the monorepo idea is good, so we can keep the two packages (`mobx` and `flutter_mobx`) together. If it means replicating the Travis scripts, I'm ok for now as there are only two packages. I can do the duplication but it is not that hard, just a matter of fixing the paths in `travis.sh`.

Let's get **flutter_mobx** working for now removing any mono_repo boilerplate? I'll help out with the `travis.sh` scripts when you are ready.

Also as @rrousselGit suggested, we should get in touch with Flutter to share our specific issue? @katis  could you raise an issue detailing where you found problems ?

**Comment by pavanpodila** [comment]
On a separate note, @rrousselGit can you take a look at the PR (#34) to see if there are any obvious fixes?

**Comment by katis** [comment]
This is done.
