### ISSUE TITLE
Missing "part 'Counter.g.dart';"

### ISSUE THREAD

**Issue by Hareis** [mobxjs/mobx.dart#290]
I copied the demo, of https://mobx.pub/getting-started. 
Found that they still reported mistakes, do not know where the lack of configuration

![image](https://user-images.githubusercontent.com/11290701/64474682-bc946c80-d1aa-11e9-91c7-f9a4ba0d3d65.png)
![image](https://user-images.githubusercontent.com/11290701/64474684-c1f1b700-d1aa-11e9-9cd1-d32521c18a2f.png)
![image](https://user-images.githubusercontent.com/11290701/64474692-d930a480-d1aa-11e9-9e29-1863159581ff.png)
```
flutter packages pub run build_runner build
```
It's not generated Counter.g.dart
![image](https://user-images.githubusercontent.com/11290701/64474719-1ac14f80-d1ab-11e9-9414-fbbc7dff9326.png)

**Comment by pavanpodila** [comment]
Your file is named with a capital `C`: `Counter.dart`. Rename it with small `c` as in `counter.dart`, then the part file will be considered. You can also see it in the red rectangle you marked.

**Comment by Hareis** [comment]
> 您的文件以大写字母命名`C`：`Counter.dart`。小重命名它`c`为`counter.dart`，那么部分文件将被考虑。您也可以在标记的红色矩形中看到它。
> 
> dart中的文件总是以小写形式命名，单词以下划线分隔 `_`



> Your file is named with a capital `C`: `Counter.dart`. Rename it with small `c` as in `counter.dart`, then the part file will be considered. You can also see it in the red rectangle you marked.
> 
> Files in dart are always named in lowercase and words separated by underscore `_`

Thank you. I spent the afternoon solving this problem.

**Comment by pavanpodila** [comment]
Oh man...learning can sometimes be hard and fun :-)

**Comment by shyndman** [comment]
Can this case be detected by us?

**Comment by pavanpodila** [comment]
Possible but looking at all the import / header declarations of the library. But I wonder if we even get invoked as build_runner itself does some sanity checks before invoking the PartBuilder. It will only do if there is a proper `part` statement.

**Comment by shyndman** [comment]
I'm lead to believe that our builder may be invoked on every file. Remember that bug I introduced awhile back, where every dart file in the project being evaluated was getting a warning? 😜

**Comment by pavanpodila** [comment]
Cool...then worth a shot checking it out

**Comment by chaschev** [comment]
This library has so much space for improvement. It takes years to get through all errors
