### ISSUE TITLE
change ThemeData, it's not works

### ISSUE THREAD

**Issue by Hareis** [mobxjs/mobx.dart#291]
![image](https://user-images.githubusercontent.com/11290701/64475261-0a14d780-d1b3-11e9-8792-06586dbb577d.png)
![image](https://user-images.githubusercontent.com/11290701/64475264-17ca5d00-d1b3-11e9-8fee-b200393068b9.png)

After changing the color, the interface can't change the color in real time, but the simple counter works fine.

**Comment by pavanpodila** [comment]
You have to an `Observer` around `MaterialApp`

**Comment by Hareis** [comment]
@pavanpodila  
Observer around MaterialApp
that's there a loss of performance?

**Comment by pavanpodila** [comment]
Not at all. The `Observer` only monitors the observables used in the immediate `builder` function, so it will not go deep into your `Widget` tree, just the first level.
