### ISSUE TITLE
Mutations inside an Observer's builder() should throw an Exception

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#297]
It's a conceptual error to mutate inside the `builder()`, as the `Widget` is only supposed to read values and never write. We should catch such mutations and flag them as errors.

This is based on issues #296 and #293

**Comment by alexander-shustanov** [comment]
Hi! Any progress with the issue? I faced another variant of the problem that is extremely hard to debug. It relates to the new `late` keyword.

Imagine the situation, I have `late` observable, which initializes on the first invocation. I have created some reactions inside the initializations which fire immediately. So, if Observer references the observable inside the build method, it might do some mutations inside.

So the exception would be very convenient.

Another variant - fire reactions only after observable is read.
