### ISSUE TITLE
@action function parameters without explicit type produce invalid generated code

### ISSUE THREAD

**Issue by sergeyv** [mobxjs/mobx.dart#298]
I have code like this:

```
@action hydrateChunk(String sectionId, int chunkNum, blob) {
  ...
}
```

which was working fine until I upgraded to the latest version of mobx (0.3.8+1), flutter_mobx (0.3.3+1) and mobx_codegen (0.3.9+1). Now the code generation fails with the following error:

```
line 331, column 58: Expected an identifier.
    ╷
331 │     dynamic hydrateChunk(String sectionId, int chunkNum, null blob) {
    │                                                          ^^^^
    ╵
line 331, column 63: Expected to find ')'.
    ╷
331 │     dynamic hydrateChunk(String sectionId, int chunkNum, null blob) {
    │                                                               ^^^^
    ╵
```
This can be worked around by explicitly specifying types of all parameters 

`@action hydrateChunk(String sectionId, int chunkNum, dynamic blob) {`

but perhaps mobx_codegen should not output `null` in this case.

**Comment by shyndman** [comment]
Thanks for the report

I got this @pavanpodila
