### ISSUE TITLE
[Proposal] Observable value interface

### ISSUE THREAD

**Issue by t-artikov** [mobxjs/mobx.dart#301]
Suppose we have a service that returns the current user's geolocation. The geolocation changes over time, so it should be observable. The question is what type the service should return.
It can be a raw value:
```dart
abstract class GeoLocationService {
    GeoLocation get geoLocation;
}
```
The getter will resolve an observable value under the hood, as a result geoLocation consumers will be notified.
I don't like this approach. It is not clear from the service interface that the property is observable.

Another way is to return an observable value:
```dart
abstract class GeoLocationService {
    Observable<GeoLocation> get geoLocation;
}
```
This is a bad solution because it allows to modify the property from the outside:
`service.geoLocation.value = newValue;`
Moreover, it imposes an implementation restriction - `Observable` cannot be replaced by `ObservableStream` or `Computed` without breaking the interface.

I would prefer to return a simple interface `ObservableValue` (actually, it would be better to call it `Observable`, but this name is already in use 😞)
```dart
abstract class ObservableValue<T> {
    T get value;
}
```
which will be implemented by `Observable`, `Computed`, `ObservableStream`, `ObservableFuture`.

The benefit of such an interface is even more significant when we need to return observable values from functions and process them later:
```dart
abstract class GeoLocationSharingService {
    ObservableValue<GeoLocation> requestGeoLocation(String userName);
}

final myLocation = geoLocationService.geoLocation;
final myFriendsLocations = ObservableList<ObservableValue<GeoLocation>>();
myFriendsLocations.add(geoLocationSharingService.requestGeoLocation('Artur'));
myFriendsLocations.add(geoLocationSharingService.requestGeoLocation('Maria'));
final distanceToNearestFriend = Computed<double>(() => nearestDistance(myFriendsLocations, myLocation));
```

Update: PR https://github.com/mobxjs/mobx.dart/pull/305

**Comment by pavanpodila** [comment]
So if I understand correctly, you want a wrapper type that can hide the differences between `Observable`, `Computed`, `ObservableStream`, `ObservableFuture` and allow easy switching of types internally without affecting the public usage?

I think that's an application level concern and can be handled in that layer.

**Comment by shyndman** [comment]
I think it might be that he wants an immutable interface for `Observable`, so consumers are hinted that they shouldn't change the value.

**Comment by pavanpodila** [comment]
Wouldn't a simple computed do the job then?

**Comment by shyndman** [comment]
Yes, it would. Good point! :)

**Comment by t-artikov** [comment]
Computed(as any other wrapper) will do the trick, but at the cost of a syntactical and computational overhead.

Compare
```dart
class GeoLocationServiceImpl implements GeoLocationService {
    @override
    ObservableValue<GeoLocation> get geoLocation => _geoLocation;

    final _geoLocation = Observable<GeoLocation>();

    void _onNewLocation(GeoLocation newValue) {
        _geoLocation.value = newValue;
    }
    ...
}
```
and
```dart
class GeoLocationServiceImpl implements GeoLocationService {
    @override
    Computed<GeoLocation> get geoLocation => _computedGeoLocation;

    GeoLocationServiceImpl() {
        _computedGeoLocation = Computed(() => _geoLocation.value);
    }

    Computed<GeoLocation> _computedGeoLocation;
    final _geoLocation = Observable<GeoLocation>();

    void _onNewLocation(GeoLocation newValue) {
        _geoLocation.value = newValue;
    }
    ...
}
```

The idea is in the common interface, which is not possible without changes(trivial) in the framework.

**Comment by pavanpodila** [comment]
I am not convinced that this belongs in the library. It seems like an application level concern which could be handled in the application itself. The general usage of the library does not need this behavior. Happy to be proven wrong though.

**Comment by t-artikov** [comment]
> It seems like an application level concern which could be handled in the application itself.

But it cannot be solved at the application level - wrapping an observable value will lead to overhead in the form of additional memory allocation.
I suggest waiting for more opinions from framework users.

**Comment by ramsestom** [comment]
I agree with t-artikov that the best and easier way to handle it is to have an `ObservableValue` abstract class that `Observable`, `Computed`, `ObservableStream` and `ObservableFuture` would all inherit as inheritence is supposed to have no overhead.

**Comment by t-artikov** [comment]
@pavanpodila 
Could you clarify your position?
Do you believe that:

1\. There is no reason for MobX users to return observable values from methods, i.e
```dart
class MyService {
    /// It's observable, actually
    T get someValue;
}
```
is preferable than
```dart
class MyService {
    SomeObservable<T> get someValue;
}
```

What about
```dart
class MyService {
    SomeObservable<T> getSomeValue(Args args);
}
```
?

or

2\. It is fine to return observables, and MobX has all the necessary mechanisms for that?

Doesn't my argument show that all alternatives to `ObservableValue` interface are worse in terms of code readability and performance?

**Comment by pavanpodila** [comment]
Any reason you are not using the `mobx_codegen` package here? It will simplify the usage of observables with `@observable` annotations

**Comment by t-artikov** [comment]
mobx_codegen simplifies implementation, while I'm more worried about the interface.
In the case of `@observable` it will be:
```dart
class MyService {
    /// It's observable, actually
    T get someValue;
    void set someValue(T value);
}
```
Which is definitely not what I want - the property should be readonly.

**Comment by pavanpodila** [comment]
Each of the observable types has very specific behaviors and combining them under a single interface is not the intention. If you need that behavior, you can try extending those types and pulling them under a common interface for your application needs. I would suggest that route rather than changing the library, which IMHO should stay pristine.

**Comment by t-artikov** [comment]
> Each of the observable types has very specific behaviors

in how it produces a value, but for a consumer they are very similar, they provide a value that can be observed, i.e implement
```dart
abstract class ObservableValue<T> {
    /// Returns the value and subscribes reactions to its changes
    T get value;
}
```
> you can try extending those types and pulling them under a common interface

I don't like this way, but I have tried it and found it impossible to extend Observable class because its generative(non factory one) constructor is private.

You wrote that `ObservableValue` is only the need of my application. This is not true, it is an totally generic mechanism. Every time a method returns a dynamically changing value, `ObservableValue` is needed. Why force users to implement it themselves (which I don’t know how to do effectively) if it can be easily done within the framework?

**Comment by pavanpodila** [comment]
Can you try composition instead of inheritance ? Something like:

```dart
class ObservableValue<T> {
  Observable<T> value;
}
```

**Comment by t-artikov** [comment]
> Can you try composition instead of inheritance?

I have considered this option and created the issue because of its shortcomings.
The composition leads to boilerplate code and additional object instantiations.

See the example in this comment
https://github.com/mobxjs/mobx.dart/issues/301#issuecomment-536871759

**Comment by pavanpodila** [comment]
Can you send me a PR of what you are proposing?

**Comment by t-artikov** [comment]
> Can you send me a PR of what you are proposing?

Sure, https://github.com/mobxjs/mobx.dart/pull/305

**Comment by t-artikov** [comment]
The thing I'm worried about is naming.
1. `ObservableValue` is quite long, a one-word name would be better.
2. Users may be confused by the difference of `ObservableValue` and `Observable`.

Personally, I would be glad to replace `ObservableValue` to `Observable`, and current `Observable` to something like `MutableObservable`.

**Comment by pavanpodila** [comment]
Let's go with the `ObservableValue` for now and we can find a better name later

**Comment by t-artikov** [comment]
Thank you!
