### ISSUE TITLE
Can an observable be null?

### ISSUE THREAD

**Issue by ramsestom** [mobxjs/mobx.dart#304]
Not an issue but a simple question. I am starting with mobx and I was wondering. Can observables be nullable? 
For example if I have a `bool` observable, can I asign it the null value and would the change from a 'false' value to a 'null' one (or the reverse) be correctly sent as a change to the observers? (I am asking this because I usually use bool with null value to handle a third "unknown" state additionally to "true" and "false"). 
Also, if null values are supported by observables, can I init an observable with a null value or does it necessarilly need to be a non null value at start?

**Comment by pavanpodila** [comment]
Yup you can.

```dart
bool x;
print(x); // null
```

If you want a tri-state value, you could also use an enum:

```dart
enum TriState { off, on, maybe }
```
