### ISSUE TITLE
ReactiveWritePolicy.observed does not work. 

### ISSUE THREAD

**Issue by Elvis5566** [mobxjs/mobx.dart#307]
mobx should fire exception if one mutate observable outside an action, however, this will never happen because enforceWritePolicy will be wrap in

```dart
final runInfo = controller.startAction();
enforceWritePolicy(atom)
controller.endAction(runInfo);
```

**Comment by pavanpodila** [comment]
We have changed the behavior such that single field writes are now conditionally wrapped in action. This ensures minimal ceremony and improves the Developer eXperience (DX).
