### ISSUE TITLE
How we can update existing item in ObservableList. 

### ISSUE THREAD

**Issue by patelmanjeet** [mobxjs/mobx.dart#312]
Hi Team,

Facing issue with ObservableList, How we can update existing item in ObservableList. 

I try to set using operator []=(int index, T value), but changes not get reflected on Observer. check updateTodo() action.

Below is code snippet.

**todo.dart**
```
class Todo {
  String name;

  Todo(this.name);
}

```
**main_store.dart**
```
import 'package:mobx/mobx.dart';
import 'todo.dart';

part 'main_store.g.dart';

class MainStore = _MainStore with _$MainStore;

// The store-class
abstract class _MainStore with Store {
  @observable
  ObservableList<Todo> todos = ObservableList<Todo>();

  @action
  loadTodos() {
    List<Todo> todos = [
      Todo('todo1'),
      Todo('todo2'),
      Todo('todo3'),
    ];
    this.todos.addAll(todos);
  }

  @action
  addTodo() {
    // This Working fine, get reflected on Observer
    Todo todo = Todo('todo' + todos.length.toString());
    this.todos.add(todo);
  }

  @action
  updateTodo(int index) {
    // THIS NEW UPDATED ITEM not get reflected on Observer
    Todo todo = this.todos[index];
    todo.name = 'NEW UPDATED';
    this.todos[index] = todo;
  }
}
```
**page.dart**
```
class Page extends StatelessWidget {
  final MainStore store = GetIt.instance<MainStore>();

  Page({Key key}) : super(key: key) {
    store.loadTodos();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        FlatButton(
          onPressed: () {
            store.addTodo();
          },
          child: Text('Create Todo'),
        ),
        FlatButton(
          onPressed: () {
            store.updateTodo(0);
          },
          child: Text('Update Todo'),
        ),
        Expanded(
          child: Observer(
            builder: (BuildContext context) {
              return ListView.separated(
                itemCount: store.todos.length,
                separatorBuilder: (context, index) {
                  return Divider();
                },
                itemBuilder: (context, index) {
                  return ListTile(
                    title: Text(store.todos[index].name),
                  );
                },
              );
            },
          ),
        )
      ],
    );
  }
}
```

**Comment by pavanpodila** [comment]
You need to make the `name` field of `Todo` an observable, like so:

```dart
class Todo {
  @observable
  String name;

  Todo(this.name);
}
```

**Comment by patelmanjeet** [comment]
Thanks @pavanpodila 

Here todo was just sample, in real we have more complex json model which have multiple fields string/int/map/list/object. If we add @observable for each fields will it create performance issue OR @observable come in picture if any Reactions attached?

**Comment by pavanpodila** [comment]
There is no performance hit to using observables. It's only when you use it in a reaction will there be any computation cost. That too is negligible in most cases

**Comment by patelmanjeet** [comment]
Thanks @pavanpodila 

mobx really awesome, make state management easy and clean code.

It will be good if some one create video/examples of all types of observables and Reactions. initially its difficult to understand concept who don't have background of mobxjs. 

mobx :+1: :+1:

**Comment by pavanpodila** [comment]
No worries. Feel free to ask questions.

**Comment by VietHo** [comment]
Hello !

Follow up question on that.

Can we modify todo.name without an action ? 

The todos [example](https://github.com/mobxjs/mobx.dart/blob/5c3b1ef13928c386cbac26e484c61571f89a5dcc/mobx_examples/lib/todos/todo_widgets.dart#L55) seems to indicate that we can mutate it directly but I feel like an action should always be required.

**Comment by pavanpodila** [comment]
Yup you can. Single field changes are automatically wrapped in action 🤟

**Comment by TarekMedhat** [comment]
@pavanpodila I'm trying to achieve the same by updating an object variable in an observablelist.
even making name observable not working for me.
I even tried the same example here but the observer isn't being notified with updates only adds.
here is the code:
```
import 'package:mobx/mobx.dart';

part 'main_store.g.dart';

class MainStore = _MainStore with _$MainStore;

// The store-class
abstract class _MainStore with Store {
  @observable
  ObservableList<Todo> todos = ObservableList<Todo>();

  @action
  loadTodos() {
    List<Todo> todos = [
      Todo('todo1'),
      Todo('todo2'),
      Todo('todo3'),
    ];
    this.todos.addAll(todos);
  }

  @action
  addTodo() {
    // This Working fine, get reflected on Observer
    Todo todo = Todo('todo' + todos.length.toString());
    this.todos.add(todo);
  }

  @action
  updateTodo(int index) {
    // THIS NEW UPDATED ITEM not get reflected on Observer, I even tryed using action to update 
// the second item but nothing reflects unless state is reloaded
    Todo todo = this.todos[index];
    todo.name = 'NEW UPDATED';
    this.todos[index] = todo;
    this.todos[index + 1].changeName("NEW");
  }
}

class Todo {
  @observable
  String name;
  @action
  changeName(String name) {
    this.name = name;
  }

  Todo(this.name);
}
```
and here is the screen
```
import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:kalimah_dictionary/stores/main/main_store.dart';

class CategoriesScreen extends StatelessWidget {
  final MainStore store = MainStore();

  CategoriesScreen({Key key}) : super(key: key) {
    store.loadTodos();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          FlatButton(
            onPressed: () {
              store.addTodo();
            },
            child: Text('Create Todo'),
          ),
          FlatButton(
            onPressed: () {
              store.updateTodo(0);
            },
            child: Text('Update Todo'),
          ),
          Expanded(
            child: Observer(
              builder: (BuildContext context) {
                return ListView.separated(
                  itemCount: store.todos.length,
                  separatorBuilder: (context, index) {
                    return Divider();
                  },
                  itemBuilder: (context, index) {
                    return ListTile(
                      title: Text(store.todos[index].name),
                    );
                  },
                );
              },
            ),
          )
        ],
      ),
    );
  }
}
```

What am I missing out there?

**Comment by pavanpodila** [comment]
You will also need an `Observer` around `ListTile` since you are also updating a `Todo`. Without it, MobX won't know about the changes. The top-level `Observer` is still needed to keep track of changes at the list level.

**Comment by pavanpodila** [comment]
Also your Todo class is not defined correctly:

It should be:

```dart
class Todo = _Todo with _$Todo

abstract class _Todo with Store { /* rest of the definition */ }
```

**Comment by DJafari** [comment]
@pavanpodila 
i have a `ObservableList<Item>` in my main store, and `Item` is another store, 
item has a property for example `price` and it's `@observable`

i have a computed value for `totalPrice` in my main store, i want when `item.price` is changed, my computed value updated, but it's not, how can i achieve to this ?

```dart
@observable
ObservableList<Item> items = ObservableList();

@computed
int get totalPrice {
  // WHEN CHANGED FOR EXAMPLE items[0].price, totalPrice computed NOT CALLED again
  int sum = 0;
  items.forEach((item) {
    sum += item.price;
  });
  return sum;
}
```

**Comment by drriguz** [comment]
I also have the same issue. However, I think the approach given by @pavanpodila  is a little bit confusing because we need to make the `Todo` class a `Store`, for me I would prefer to treat it as a simple model.

I checked the source of `ObservableList` and I found this:

```dart
 void replaceRange(int start, int end, Iterable<T> newContents) {
    _context.conditionallyRunInAction(() {
      final oldContents = _list.sublist(start, end);
      _list.replaceRange(start, end, newContents);
      _notifyListUpdate(start, newContents, oldContents);
    }, _atom);
  }

 void operator []=(int index, T value) {
    _context.conditionallyRunInAction(() {
      final oldValue = _list[index];

      if (oldValue != value) {
        _list[index] = value;
        _notifyChildUpdate(index, value, oldValue);
      }
    }, _atom);
  }
```
I noticed that if we assign by `[]=` it will only call `_nofityChildUpdate`, however, we need `_notifyListUpdate` if we want to notify observers, which could be implemented by using `replaceRange`.

I tested it and it does work, but I wonder what is the standard way to handle such a scenario?

**Comment by edgarfroes** [comment]
Put the Observer directly on top of the ListTile, instead of on top of the ListView.builder.

**Comment by ayoubboumzebra** [comment]
@TarekMedhat did fix it ?

**Comment by henriquetroiano** [comment]
nobody fixed yet, thats a shame..

**Comment by FabioSousaFBS** [comment]
Hoje passei por uma situação dessas. O valor foi alterado da forma que o código está, mas se você precisar que algo aconteça na tela você precisa usar o método setState quando estiver configurando o novo valor no MobX. Não encontrei outra maneira, principalmente usando o MobX diretamente.

**Comment by henriquetroiano** [comment]
Calma, gafanhoto kkk
Encontrei uma solução:
você cria uma cópia local do item a ser alterado, altere-o, pegue seu index, remova-o e insira-o no index que ele pertencia!

**Comment by FabioSousaFBS** [comment]
Boa solução Henrique! 
Lembrando que esse ambiente é de cooperação e cordialidade, sem espaços para gracinhas.

Espero que você evolua nesse sentido assim tal qual foi sua solução para a situação proposta nesse tópico. []s

**Comment by henriquetroiano** [comment]
Reclamou da resposta, vai ficar sem ela.

**Comment by henriquetroiano** [comment]
Espero que tenha a copiado

**Comment by henriquetroiano** [comment]
@pavanpodila please close this issue as completes, since is not a problem with mobx itself.
