### ISSUE TITLE
import flutter_mobx fails in desktop

### ISSUE THREAD

**Issue by 926** [mobxjs/mobx.dart#313]
Hi everyone,
This issue might is linked with flutter desktop, sharing here in case,

Here is what the import looks like on standard flutter project, all good :
![image](https://user-images.githubusercontent.com/14161798/68327035-e09dfc80-00cc-11ea-91c1-1bedd8b677de.png)

I get "Target of URI doesn't exist" error when I use the same import in flutter **desktop**

![image](https://user-images.githubusercontent.com/14161798/68327123-075c3300-00cd-11ea-85a6-8ed508f82889.png)

Since it is all dart, .yaml is the same with the same dependencies and dependencies
![image](https://user-images.githubusercontent.com/14161798/68327179-222ea780-00cd-11ea-8ad2-7f5817d71c54.png)

![image](https://user-images.githubusercontent.com/14161798/68327166-1cd15d00-00cd-11ea-8998-34bff37af0f9.png)

The package is imported if I square it down to import 'package:mobx/mobx.dart';
![image](https://user-images.githubusercontent.com/14161798/68327232-3f637600-00cd-11ea-9a13-cabc41b7a6a3.png)

Problem is that then I cannot use Observer,

If anybody has a clue I would be eternally grateful

**Comment by shyndman** [comment]
Looks like you're missing the `flutter_mobx` dependency.

**Comment by shyndman** [comment]
`flutter_mobx: ^0.3.3+1`

**Comment by 926** [comment]
thanks shyndman, you made my day
