### ISSUE TITLE
Use Github Actions to automate publishing of packages to pub.dev

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#314]
The script will run sanity checks and do what is listed here: https://mobx.pub/developer/release

We can leverage Dart to do most of this work

**Comment by rrousselGit** [comment]
If you're looking for a CD, I'm not sure if it's feasible.
There's an authentification check performed by `pub publish` which requires to open a specific URL on the browser.

**Comment by pavanpodila** [comment]
Ya, should clarify: the script is for local execution only.

**Comment by pavanpodila** [comment]
Use this [Github Action](https://github.com/marketplace/actions/dart-package-publisher) created by @k-paxian

**Comment by shyndman** [comment]
This is done, right?

**Comment by pavanpodila** [comment]
Requested a change in github action: https://github.com/k-paxian/dart-package-publisher/issues/1

Once we have that, we are good to go

**Comment by pavanpodila** [comment]
This is done as part of #400
