### ISSUE TITLE
how to observable fields inside object?

### ISSUE THREAD

**Issue by RocketBarage** [mobxjs/mobx.dart#315]
```
@observable
  CustomClass customObj;


 CustomClass {
     double filed = 0.0;
 }

```
how to observable "field" after init customObj?

**Comment by pavanpodila** [comment]
Please go through the [Getting Started](https://mobx-dart.netlify.com/getting-started) guide to learn more

**Comment by NarHakobyan** [comment]
@RocketBarage are you found any information about it?
