### ISSUE TITLE
How to set up a Reaction?

### ISSUE THREAD

**Issue by Magenda** [mobxjs/mobx.dart#316]
Hi, dart/mobx newbie here...

I've read almost everything I could find about reactions (mobx website guide, github examples, stackoverflow, mobx articles, github relevant issues etc) but I don't get how to properly set them up. 

For example, the following reaction just listens to an observable number and prints it's value when the latter gets modified. The following code has this syntax error for my number: "Only static members can be accessed in initializers.". What I'm doing wrong? 

```dart
import 'package:mobx/mobx.dart';
part 'live.g.dart';

class Live = _Live with _$Live;

abstract class _Live with Store {
  @observable
  int mynum = 0;

  // print mynum every time it's changed...
  final myreaction = reaction((_) => mynum, (msg) => print("$msg"));

  _Live() {
    mynum++; //just for testing the reaction...
  }

  @override
  dispose() {
    myreaction();
  }
}
```

**Comment by pavanpodila** [comment]
One option is to setup these reactions in the constructor, eg:

```dart
abstract class _Live with Store {

  ReactionDisposer _disposer;
  
  _Live() {
    _disposer = reaction((_) => mynum, (msg) => print("$msg"));
  }

  @override
  dispose() {
    _disposer();
  }
}```

**Comment by Magenda** [comment]
@pavanpodila I see, many thanks!

Is this the "official" way? I would love to know other common ways of usage. 

Moreover, the [GetStarted reactions section](https://mobx.pub/concepts#reactions) shows a usage outside of a class. Is this on purpose and a common way to import observables/actions/reactions from other files to the Store, or is it class-less just for code minimization in the guide?

**Comment by MaikuB** [comment]
You can definitely do within a class e.g. a widget. I think the examples appear to be done outside of a class because it was only to show the relevant code. At least that's my assumption.

An example would be within a`StatefulWidget` for a page (i.e. one that has a scaffold), you can setup a reaction that listens to connectivity changes. When the user is offline show a message via snackbar. Override the dispose method so that you can dispose the reaction.

@pavanpodila I can try to update our examples to include this in, let me know what you think :)

**Comment by pavanpodila** [comment]
That would be awesome @MaikuB. I think we should have a completely new example just to illustrate the various reactions: `autorun`, `reaction` and `when`. What do you say ? PR time ?

**Comment by MaikuB** [comment]
Would need to think of practical examples if we were to do all of them. I would suspect that doing one of them (in this case a connectivity one could use `autorun`) would be sufficient given the method signatures and the way to set each one up is pretty much identical

**Comment by pavanpodila** [comment]
Ya let's start with `autorun` and we can add more to it later

**Comment by shyndman** [comment]
Can we close this off?

**Comment by pavanpodila** [comment]
Yes, this is done now
