### ISSUE TITLE
Translate to protuguese

### ISSUE THREAD

**Issue by rodriguesJeff** [mobxjs/mobx.dart#317]
Have you interest in create translates? If so, i can help with the translation to pt-br
I only need that you create a folder containing all your code with the name pt-br inside your docs folder. When i can, i help translating some pages for portuguese... 
After this, you connect the translation folder to home page in this website.

**Comment by pavanpodila** [comment]
That is very welcome @rodriguesJeff. Just send me a PR as and when you are ready. You don't have to translate all pages in one go. It can be done one at a time and I'll merge. You can create the folder structure you need in your PR.

Look forward to it!

**Comment by jacobaraujo7** [comment]
Was there any breakthrough? It interests me a lot. I am founder of "Flutterando", the largest independent Brazilian community recognized by Google. We're showing people MobX here, and having a pt-BR documentation would be very attractive.

@pavanpodila  If it's not in progress, do you have a template you can follow?

**Comment by pavanpodila** [comment]
@jacobaraujo7 I would love to have this picked up by you or someone else. In terms of template, there is not much to be done besides putting all of the translated version of markdowns in a `pt-BR` folder at the root and have a simple language bar in the header to switch between English and Portuguese versions. We can add more languages in the future too with the same approach.

Let me know if this makes sense.

**Comment by jacobaraujo7** [comment]
I'm working in a pr

**Comment by jacobaraujo7** [comment]
PR done and Merged. @rodriguesJeff , It would be interesting to see if the translation to pt-BR is good my friend.  If so, I believe we can close this issue.

**Comment by pavanpodila** [comment]
It would be great if you want to translate the site (https://mobx.pub) as well, possibly in a separate PR
