### ISSUE TITLE
Mobx_codegen version conflict

### ISSUE THREAD

**Issue by hrpath** [mobxjs/mobx.dart#322]
Hello, 

I'm using MobX codegen but get this error with generating code

_Because chopper_generator >=3.0.1 depends on analyzer **^0.38.2** 
and mobx_codegen 0.3.3+1 depends on analyzer **^0.36.3**_

Why such difference in version ?
How can I solve that ?

Thank you !

**Comment by pavanpodila** [comment]
Please upgrade to the latest `mobx_codegen` where we changed this constraint to be a range

**Comment by hrpath** [comment]
My IDE that use extended flutter support did not suggest the update. Now it works well.
Thanks @pavanpodila !
