### ISSUE TITLE
Observer not listening.

### ISSUE THREAD

**Issue by vimalmistry** [mobxjs/mobx.dart#323]
```dart    
AppStore appStore = Provider.of<AppStore>(context);
  
return Observer(
      name: 'loginCheck',
      builder: (_) {
        return appStore.isAuthanticated
            ? HomeScreen()
            : FutureBuilder(
                future: authStore.tryLoginWithSharedPreferences(),
                builder: (context, authResultSnapshot) {
                  if (authResultSnapshot.connectionState ==
                      ConnectionState.waiting) {
                    return SplashScreen();
                  }
                  return LoginScreen();
                },
              );
      },
    );
```

I have this code in my main .dart. In loginScreen When I change isAuthanticated its working. But Inside RegisterScreen not working. Both are calling same function.

I tried get_it and also provider But problem is same for both. I tried to ask in gitter and also discord no reply then I am asking here. hope someone help me.

**Comment by pavanpodila** [comment]
Can you share the `AppStore` code? Also are you using `mobx_codegen` ? Hope you have read the [Getting Started](https://mobx.pub/getting-started) guide.

**Comment by hramnathnayak** [comment]
`AppStore appStore = Provider.of<AppStore>(context);`

Shouldn't we be telling the Provider what type of store we are looking for?

**Comment by shyndman** [comment]
@vimalmistry, did you get this sorted out?

**Comment by vimalmistry** [comment]
@shyndman No. I couldn't find any solution. 

- main app
- login
- register

Main app have code as above. which bound with observer.
I pushed login screen above then register. I mean stack wise. 1st main app > login > register.

I found observer working in login screen. but not in register screen. 
I also tried by pushReplaceNamed in login screen still no luck. I think There is screen stack issue. Just observing it. 

I just shorted this by using Pageview in login screen. one screen but two page views.

**Comment by shyndman** [comment]
Any chance you can post a reproduction to Github? We can get this fixed up quickly.

**Comment by vimalmistry** [comment]
Ya I will try tomorrow. I will inform here.

**Comment by pavanpodila** [comment]
Closing for now. Feel free to reopen if needed.
