### ISSUE TITLE
Next reactions not fire, When a reaction set value to the old one.

### ISSUE THREAD

**Issue by benzsuankularb** [mobxjs/mobx.dart#326]
```
import 'package:project/sample_store.dart';
import 'package:mobx/mobx.dart';
import 'package:test/test.dart';

void main() {
  test('Test that passed', () async {
    // Setup
    var store = SampleStore();
    var called = false;
    // I swapped 2 line below in second test.
    when((_) => store.isTrigger, () => called = true); 
    when((_) => store.isTrigger, () => store.isTrigger = false);

    // Do
    store.isTrigger = true;
    await Future.delayed(Duration(milliseconds: 10));

    // Expect
    expect(called, true);
  });

  test('Test that failed', () async {
    // Setup
    var store = SampleStore();
    var called = false;
    when((_) => store.isTrigger, () => store.isTrigger = false);
    when((_) => store.isTrigger, () => called = true);

    // Do
    store.isTrigger = true;
    await Future.delayed(Duration(milliseconds: 10));

    // Expect
    expect(called, true); // THIS FAILED
  });
}
```

I found that the order of reactions is matters.
The problem in the second test case is
The second reaction doesn't fire if the first reaction change the observable to the old value.
My expectation is every reaction will fire even if the observable value changed back. 

Is this by designed or just found?
Thankyou :)

**Comment by pavanpodila** [comment]
Reactions only fire if the value changes

**Comment by benzsuankularb** [comment]
I have a solution for implementation already.

But I still curious that, Is this the right behavior for MobX, Isn't it make MobX lower predictable?

Because if I need to manage reaction by relying on order, I think it's a leak of implementation detail here.

**Comment by shyndman** [comment]
Huh, that is interesting. It's a little weird, but it could be the right decision to not execute the second reaction.

Consider the alternative — that when `isTrigger` is changed, both reactions are queued and always execute. What happens, then, if they both change `isTrigger`, and set it to different values. Last write wins, right? So ordering is important in that case as well.

I'm curious — what does the JS implementation do?

**Comment by pavanpodila** [comment]
The behavior you are observing is correct. A few things to note:

- `when` reactions auto-dispose after they execute, so they will not monitor the observables after they are disposed
- The effect-function (second arg to `when`) is not monitored, so it won't cause a retrigger of the same reaction

Using these you can figure out why the behavior is correct :-)

**Comment by pavanpodila** [comment]
Closing for now
