### ISSUE TITLE
Add the Flutter-Favorite logo everywhere necessary, now that its official

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#328]
Note the Flutter-Favorite logo on the package page for [mobx](https://pub.dev/packages/mobx), [flutter_mobx](https://pub.dev/packages/flutter_mobx) and [mobx_codegen](https://pub.dev/packages/mobx_codegen).

We need to add this (use the hi-res version) to the readme and docs:
![image](https://user-images.githubusercontent.com/156846/70500845-7dc3d900-1b42-11ea-96ee-bbcc6e45fe70.png)

**Comment by shyndman** [comment]
Hi!

What's Flutter Favorite?

**Comment by pavanpodila** [comment]
It's a feather in cap for all of us, who have committed our time to his package. We should all be proud of this moment! 🥇

**Comment by shyndman** [comment]
🍾!!!

**Comment by sohonisaurabh** [comment]
@pavanpodila - Created an initial PR here where I have added the logo to global README. Do we have to add it to all the docs? These one I found listed below:

1. mobx/readme
2. flutter_mobx/readme
3. mobx_codegen/readme
4. All .md/.mdx files under docs directory

Please confirm

**Comment by pavanpodila** [comment]
@sohonisaurabh I added to the ones you mentioned and adjusted the size to 128. It only needs to be on the main pages.
