### ISSUE TITLE
Explore Github Actions for doing our builds and publishing to pub.dev

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#330]
Now that Github Actions is out, let's see if we can replace CircleCI with Actions

**Comment by k-paxian** [comment]
Recently I have created an action for that.
https://github.com/k-paxian/dart-package-publisher

**Comment by pavanpodila** [comment]
This is cool @k-paxian 👍. How do you deal with warnings from `pub publish`? Do you still publish ?

**Comment by k-paxian** [comment]
Nope, algorithm is straight forward and obvious. If your package has at least one warning it will not be published. 
* If package has tests they will be runned first, if fail, publish skipped.
* Versions comparison between local and remote, if the same, publishing skipped.
* if Publish dry run is done w/o warnings real publishing is performed.

**Comment by pavanpodila** [comment]
Nice. As per the pub guidelines, I would also have to make a release tag with `<package-name>-<version>`. Is that something you can add to this ?

**Comment by k-paxian** [comment]
There is an action for that
https://github.com/actions/create-release
You just need to chain them inside your workflow yml steps.

From https://github.com/k-paxian/dart-package-publisher action as an Output parameter
you should have published version, and you could pass it further to `create-release` action
as an Input parameter.

**Comment by pavanpodila** [comment]
Cool..Will spend some time on getting this integrated! Thanks for the tips @k-paxian

**Comment by pavanpodila** [comment]
Started work on this in #400. Having some issues with the bash shell. @k-paxian any ideas?

**Comment by k-paxian** [comment]
Well, honestly I don't see any details, could you please point me to the actual issue?

**Comment by pavanpodila** [comment]
I fixed some of the issues :-). Now we have feature parity with CircleCI. Next I'm going to integrate your action and others. Will ping if I need some help! Thanks for checking in.

**Comment by pavanpodila** [comment]
done with #400
