### ISSUE TITLE
No reaction with observable list in widget parameters

### ISSUE THREAD

**Issue by darkjeff99** [mobxjs/mobx.dart#331]
I tried to do ObservableList and use it for my UI

```dart
 @observable
  ObservableList<Level> addLevels = ObservableList<Level>();
```

I have an action 

```dart
@action
 void getAddedLevels(Figure fig) {
   addLevels.addAll(fig.levels);
 }
```

And in my widget an Observer

```dart
Observer(
  builder: (_) {
    return LevelsBuilder(
        onAddLevel: _figureStore.addLevel,
         onRemoveLevel: _figureStore.removeLevel,
          levels: _figureStore.addLevels);
    },
),
```

But the observer doesn't catch the action when I add a element in the list. 

The workaround is to add in the observer a property of the list in the observer, like that I have a rebuild of my widget.

```dart
Observer(
  builder: (_) {

    _figureStore.addLevels.length;

    return LevelsBuilder(
        onAddLevel: _figureStore.addLevel,
         onRemoveLevel: _figureStore.removeLevel,
          levels: _figureStore.addLevels);
    },
),
```
I don't know if there is a bug or if I don't use it correctly.

**Comment by pavanpodila** [comment]
It's not a bug @darkjeff99. It's the intended behavior of an `Observer`. The `builder` function can only observe the observables in its immediate execution context. This means if you don't have any observables being read in the function, it won't be able to track anything. This is why having a statement like `  _figureStore.addLevels.length;` helps. 

The `builder` can't reach into nested functions, so you have to use some observables which can be tracked within the `builder` function itself. 

One suggestion is to use the `Observer` as close to the place where an observable is being read. Don't put it at the top-level. Be generous with `Observers` and use them freely and just at the place where needed.

**Comment by darkjeff99** [comment]
Thank you for the answer.

But I don't understand something, It is a Widget with parameter, like Text.

Why that is working ? What is the difference between a Text widget and custom widget ?
```dart
Observer(
  builder: (_) {
    return Text(_figureStore.addLevels.toString());
  },
)
```
The goal is to have Widget store agnostic and reusable without store.

**Comment by pavanpodila** [comment]
It's not about the widget but the nesting of these widgets. `Observer` can only track what is immediately executed in its function, not any level deeper. In the example above, `_figureStore.addLevels.toString()` is read immediately inside the `builder` function, hence it can be tracked and rendered on changes.

Hope that clarifies ?

**Comment by darkjeff99** [comment]
Yes it is thank you
