### ISSUE TITLE
@computed codegen fails null safety 

### ISSUE THREAD

**Issue by 1N50MN14** [mobxjs/mobx.dart#332]
Given 
```dart
@computed 
bool get computedBool=>obsvBool1 && obsvBool2
```

codegen would produce:

```dart
Computed<bool> _$computedBool;

@override
bool get computedBool =>
 (_$computedBool ??= Computed<bool>(() => super.computedBool)).value;
```
The generated code, in combination with non-nullable enabled, makes analyzer scream `Non-nullable instance field _$computedBool must be initialized.`.

I'm not sure why `_$computedBool` is declared in the class all together (apologies I might be missing on something) as I couldn't see it's ever set, used or reused throughout the class, super method is always called in this case.

Either ways, I tried to make it nullable by rewriting the getter so that it becomes:

```dart 
@computed bool? get computedBool=>... 
``` 
but that that produced 

```dart
Computed<bool?> _$computedBool
``` 
instead of 
```dart 
Computed<bool>? _$computedBool
``` 
which would've passed the null check and resolved the issue...

(PS: Thank you very much for the work on the library, it's indispensable)

**Comment by shyndman** [comment]
I think the new `late` keyword is intended for use in this situation. I'll start looking into how we can support codebases that have opted in to NNDB.

> I'm not sure why _$computedBool is declared in the class all together (apologies I might be missing on something) as I couldn't see it's ever set, used or reused throughout the class, super method is always called in this case.

It's set and read from in this expression:
```dart
(_$computedBool ??= Computed<bool>(() => super.computedBool)).value;
```

This is equivalent to:
```dart
if (_$computedBool == null) {
  _$computedBool = Computed<bool>(() => super.computedBool);
}
return _$computedBool.value;
```

Computed is memoized based on the state of the observables it depends on — so yeah, super is called, but it won't be called repeatedly unless its dependencies change.

**Comment by 1N50MN14** [comment]
Ah ok I now understand why the expression wasn't simply ```(Computed<bool>(() => super.computedBool).value``` instead of the current inline setter,I misunderstood how/where ```_$computedBool``` is otherwise used.

Yeah `late` does the trick...

Many thanks @shyndman

**Comment by pavanpodila** [comment]
@shyndman if we can check the Dart SDK at compile time, we can add this in the codegen ?

**Comment by shyndman** [comment]
The feature can be enabled on a per-library basis. 

It's easy enough to ask the analyzer whether the feature is enabled, but less clear on how to enable the feature in tests. I'm going to file an issue with the `build` project to see if they can shed some light on it.

**Comment by shyndman** [comment]
We're blocked on this issue. I've started watching it for updates.
https://github.com/dart-lang/build/issues/2343

**Comment by gouthamravella** [comment]
I guess we can start resolving this update now?

**Comment by pavanpodila** [comment]
Hi @gouthamravella, the work is going on in #603  and #634

**Comment by TonioBesl** [comment]
use this version:
mobx: ^1.2.1
flutter_mobx: ^1.1.0
mobx_codegen: ^1.1.0+1
build_runner: ^1.10.0

**Comment by xk08** [comment]
In Aug/2021, to me works with:

sdk: ">=**2.12.0** <3.0.0"

and...

mobx: ^2.0.4
flutter_mobx: ^2.0.2

build_runner: ^2.1.1
mobx_codegen: ^2.0.2

**Comment by luizgomaciel** [comment]
I have the same issue! Does someone know how to resolve?

I added my issue in stackoverflow.
[https://stackoverflow.com/questions/70747831/flutter-mobx-mobx-codegen-generates-null-safety-code-for-computed-getters/71011419](url)
