### ISSUE TITLE
Observer can rebuild when unattached

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#333]
There are cases where an Observer can call setState while unattached from the Element tree, which causes an assertion failure.

I'm encountering this case immediately following an action that mutates both the Observer's observed state, as well as a parent's state that determines whether the Observable exists in the tree. It's a timing issue — if the order of events were reversed, it wouldn't be an issue.

I think that a simple check to ensure that the Observer's `context` has an `owner` before calling `setState` is enough to resolve the issue. The state settles without issue when this is the case.

**Comment by pavanpodila** [comment]
PR?

**Comment by shyndman** [comment]
Yeah, just started looking into how to demonstrate this with a test. I'll have something in the next few days.

**Comment by shyndman** [comment]
It might have to do with me changing observed state during the paint phase, which might be a little unusual. We'll see.

**Comment by shyndman** [comment]
I haven't been able to reproduce this for some time. Marking this closed. I'll reopen if it comes up again.
