### ISSUE TITLE
 Code generation failed

### ISSUE THREAD

**Issue by chenjianjun571** [mobxjs/mobx.dart#335]
prompt：
FileSystemException(path=/Users/******/flutter/bin/cache/dart-sdk/lib/html/dart2js/html_dart2js.dart; message=Cannot open file)。

evn:
Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.6 at /Users/chenjianjun/flutter
    • Framework revision 18cd7a3601 (7 天前), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

**Comment by shyndman** [comment]
Hi @chenjianjun571,

I can't tell what's going wrong from this information. Can you put a simple reproduction somewhere, or give us more information? 

I see this is a Flutter web project. Is there anything else we should know?

**Comment by chenjianjun571** [comment]
> Hi @chenjianjun571,
> 
> I can't tell what's going wrong from this information. Can you put a simple reproduction somewhere, or give us more information?
> 
> I see this is a Flutter web project. Is there anything else we should know?

no, it is Flutter app project.
I have a problem after upgrading Flutter recently。

Below is the log：
flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 454ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 18.4s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.2s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] mobx_codegen:mobx_generator on lib/state/state.dart:

FileSystemException(path=/Users/chenjianjun/flutter/bin/cache/dart-sdk/lib/html/dart2js/html_dart2js.dart; message=Cannot open file)
[SEVERE] mobx_codegen:mobx_generator on lib/state/state.dart:

FileSystemException(path=/Users/chenjianjun/flutter/bin/cache/dart-sdk/lib/html/dart2js/html_dart2js.dart; message=Cannot open file)
[SEVERE] mobx_codegen:mobx_generator on lib/state/state.dart:

FileSystemException(path=/Users/chenjianjun/flutter/bin/cache/dart-sdk/lib/html/dart2js/html_dart2js.dart; message=Cannot open file)

**Comment by shyndman** [comment]
If you downgrade to the version of Flutter you were using previously, does it work again?

**Comment by shyndman** [comment]
Closing for now. Reopen if this is still an issue.
