### ISSUE TITLE
flutter_mobx exception shown without stack trace

### ISSUE THREAD

**Issue by cannoneyed** [mobxjs/mobx.dart#337]
When an error occurs in an `Observer` widget's build method, the error is logged without a stack trace. Interestingly enough, when I tried to dive into fixing the issue by using a local fork of `flutter_mobx`, the stack trace is shown correctly.

```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER_MOBX ╞════════════════════════
flutter: The following NoSuchMethodError was thrown:
flutter: The getter 'primary' was called on null.
flutter: Receiver: null
flutter: Tried calling: primary
flutter: ════════════════════════════════════════════════════════
```

**Comment by pavanpodila** [comment]
Can you try with the newly released version of `flutter_mobx`: https://pub.dev/packages/flutter_mobx

**Comment by shyndman** [comment]
Yes. This is fixed in the new release. I'm closing it off, but let us know if anything doesn't work and we'll reopen.

**Comment by neokree** [comment]
Hello, I'm sorry but in the latest version I did not see the stacktrace printed in console. 

My versions:
```
mobx: ^1.0.2+2
flutter_mobx: ^1.0.1
mobx_codegen: ^1.0.2
```

console error:
```
════════ Exception caught by flutter_mobx ══════════════════════════════════════════════════════════
The following MobXCaughtException was thrown:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(".")

════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
MobXCaughtException: NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(".")
The relevant error-causing widget was: 
  Observer file:///Users/neokree/Documents/Flutter/project/lib/src/ui/core/component/map/widget.dart:342:18
════════════════════════════════════════════════════════════════════════════════════════════════════
```

There is a way to enable it? 
At this time to see the stack trace I need to debug the app and set a breakpoint on the `observer_widget_mixin.dart:89`, so I can get the exception that will be thrown and see the stacktrace.
