### ISSUE TITLE
Is there any thing like redux-persist or how can i persist data in flutter with mobx?

### ISSUE THREAD

**Issue by gwl002** [mobxjs/mobx.dart#339]
Need to write the logic all by my self?

**Comment by pavanpodila** [comment]
Data persistence is outside the scope of MobX. You can use a JSON Serializer or other mechanisms to persist in a DB. MobX gives you a fast and convenient way to keep the UI in sync with changing data without cumbersome subscriptions / notifications. It is automatic for the most part
