### ISSUE TITLE
Create ObservableStream Extension

### ISSUE THREAD

**Issue by jacobaraujo7** [mobxjs/mobx.dart#345]
It would be really cool if there was an extension to the ObservableStream Stream like:

```dart
ObservableStream output = stream.asObservable();
```
instead

```dart
ObservableStream output = ObservableStream(stream);
```

**Comment by pavanpodila** [comment]
@jacobaraujo7 Want to try a PR? 👍

**Comment by jacobaraujo7** [comment]
@pavanpodila 
Yes sir! What do you think about this? Is it also worth thinking about extensions for other collections like ObservableList?

**Comment by pavanpodila** [comment]
Yes, extensions is a huge opportunity to really simplify the API and make it more intuitive. I would certainly explore other APIs that can be introduced, for Observable, Computed, Atom, Observable{List,Set,Map}, ObservableFuture and possibly even inside the core

**Comment by jacobaraujo7** [comment]
I believe the ObservableStream extension will bring BLoC and MobX into the community.

**Comment by jacobaraujo7** [comment]
@pavanpodila If you get your endorsement to work with the minimum dart version 2.7.0, then I will start working on the other extensions.

**Comment by pavanpodila** [comment]
Closing it as part of your PR #346
