### ISSUE TITLE
Todo example not working (mobx flutter)

### ISSUE THREAD

**Issue by klaszlo8207** [mobxjs/mobx.dart#353]
https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/lib/todos/todo_list.dart

I jus copy pasted this code

"The method _$TodoFromJson is 'nt defined for the class Todo"

"The method _$TodoToJson is 'nt defined for the class Todo"

my pubspec is:

  build_runner: any
  provider: ^3.0.0
  #mobx: ^0.3.10
  #mobx_codegen: ^0.3.10+1
  flutter_mobx: ^0.3.4+2

**Comment by shyndman** [comment]
It looks like you're missing the dependency on `json_serializable`, which is used by `TodoList`.

That, or you haven't run the code generator. To do that, open your application's root directory in a terminal, and run `flutter packages pub run build_runner build`

**Comment by klaszlo8207** [comment]
So basically when I just create a class with MobX after I need to generate the .g class? Not to slow this?

Thanks

**Comment by klaszlo8207** [comment]
Any way to build that files after I call the "play btn" in Android Studio? So when I build the apk?

**Comment by pavanpodila** [comment]
I think you will have to set it up as an external command to run `flutter packages pub run build` inside the folder.  In IntelliJ, you could do as part of your run command with a launch runner like so:

![image](https://user-images.githubusercontent.com/156846/71525140-79dfd700-28f6-11ea-990a-91525712e2b7.png)
