### ISSUE TITLE
Upgrade analyzer dependency lower bound and remove deprecated API usage

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#354]
`analyzer` 0.39.x introduced deprecations for APIs that we depend on. As we increase the dependency's lower bound, we can move to using the replacements.

**analyzer 0.38.2**
* Introduces `NullabilitySuffix`, required for calling `ClassElement.instantiate`, which can be used in place of `TypeDefiningElement.type`

**analyzer 0.39.1**
* Introduces `LibraryElement.typeSystem`, the replacement for `AnalysisSession.typeSystem`

**analyzer 0.39.2**
* Introduces `DartType.getDisplayString()`, the replacement for `DartType.displayName`

The real question here is how long we want to keep supporting older `analyzer` versions.

**Comment by leonardocustodio** [comment]
Hi, is it possible to upgrade for analyzer 0.40.x ? Other libraries are already using (for example hive_generator) and both are conflicting.

**Comment by pavanpodila** [comment]
Definitely possible. Do you want to do a PR? 🤞

**Comment by leonardocustodio** [comment]
Ok. I can check it out, just give me a few minutes to check another thing first.

**Comment by shyndman** [comment]
Nice work @leonardocustodio
