### ISSUE TITLE
Is the stores disposable?

### ISSUE THREAD

**Issue by pedromassango** [mobxjs/mobx.dart#366]
In the latest version the `dispose` function was removed and I didn't found any function equivalent to dispose the stores. Is there any performance impact in not disposing the store?

**Comment by pavanpodila** [comment]
You can use dispose by simply creating a `dispose()` method inside your Store and calling it when a Widget no longer needs the store or if the lifetime of the Store has completed. Typically if you have reactions setup in your Store, its a good idea to dispose them. The `dispose()` method is a good way of doing it.

The use of `dispose()` is just a convention and there is no need to call it as such. You can call it destroy, teardown or other such methods. We removed it from Store as it was not really necessary and was adding unnecessary confusion.

**Comment by pedromassango** [comment]
Thank you. I thought that caling `dispose` was a required task now I just removed then all
