### ISSUE TITLE
Add method to transform variable in Observable

### ISSUE THREAD

**Issue by LilySny** [mobxjs/mobx.dart#379]

**Comment by LilySny** [comment]
I suggest a way to turn any variable into an observer based on an extension:
extension ObservableObject on Object {
  Observable<T> asObservable<T>() => Observable<T>(this);
}

var i = 5;
var b = i.asObservable<int>();

**Comment by pavanpodila** [comment]
How about a PR @LilySny . Happy to assist and review.
