### ISSUE TITLE
How can I make the comments appear?

### ISSUE THREAD

**Issue by januwA** [mobxjs/mobx.dart#388]
## counter.dart
```dart
import 'package:mobx/mobx.dart';

part 'counter.g.dart';

/// hello
class Counter = _Counter with _$Counter;

/// hello
abstract class _Counter with Store {
  
  /// hello
  _Counter() {}
  
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}
```

When I look at the comments of this class, it has no effect.
![image](https://user-images.githubusercontent.com/22570563/72124918-8443ab80-33a1-11ea-8248-0b9a916e1340.png)

Please help me, thanks ❤

**Comment by pavanpodila** [comment]
I don't think its an issue with `mobx` or `mobx_codegen`. Its an IDE related issue or with the Flutter/Dart plugin that extracts the comments.

**Comment by januwA** [comment]
@pavanpodila  Thank you for the reply
