### ISSUE TITLE
Any example yet?

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mobx.dart#4]
Hey @pavanpodila, looks like you've been making great progress! Do we have an example of ObservableValue yet?

**Comment by pavanpodila** [comment]
Not yet but will add them this week. I am wrapping on a small feature and will take on examples. Can you share a few ideas for the examples that would be useful. Note that we still don't have the flutter widgets yet so the examples have be pure state-management :-)

**Comment by pavanpodila** [comment]
Oh, the tests are also a good indication of the API: https://github.com/mobxjs/mobx.dart/tree/master/test

**Comment by sanketsahusoft** [comment]
So good to see them in action 👍
