### ISSUE TITLE
[BUG] change in ObservableList do not trigger reaction

### ISSUE THREAD

**Issue by ramsestom** [mobxjs/mobx.dart#401]
a reaction observing an ObservableList isn't triggered when the list content change, making an ObservableList pretty useless...

```
@observable
ObservableList items = new ObservableList();

final itemsDisposer = reaction(
      (_) => this.items,
      (items) {
        print("items change triggered reaction");
       }
);

//This do not work (reaction not triggered)
items.add(item)

//This works (reaction is triggered)
ObservableList tpitems = new ObservableList();
tpitems.addAll(items);
tpitems.add(item)
items = tpitems;
```

**Comment by deadsoul44** [comment]
I also think so. It should be reactive somehow for example using reflectable package. I hope this will be added as a feature.

**Comment by pavanpodila** [comment]
@ramsestom , your reaction is only tracking `this.items`, which means only when its instance changes, will the effect-function be re-run. If you want to track changes, you have to read the list in some way, say by calling `this.items.length`

**Comment by ramsestom** [comment]
Thanks. But it looks like reading the length is not enaugh to track any change in an ObservableList. The reaction is only triggered if  the returned value of the tracking function has changed (So, if I return the length and perform a replace in the list, the reaction wouldn't be triggered). So is there any simple way to trigger a reaction on any change on an ObservableList? 
Anyway, having a `deepReaction` reactiondisposer that could be triggered for any change into a Store's observable (like proposed here: https://github.com/mobxjs/mobx.dart/issues/218#issuecomment-509991708) or for any change into an ObservableList or ObservableSet or ObservableMap content would be a big plus I think.

**Comment by pavanpodila** [comment]
Can you share the code that renders the Observer Widget?

**Comment by pavanpodila** [comment]
We don't support deep observation right now as it hits performance. We will consider it in future for sure.

**Comment by ramsestom** [comment]
How does deep observation hits performances? It shouldn't as it is just like defining a reaction that listen at every atom of a Store. For ObservableList I noticed that there is a single atom for the whole list (and not one by value) so actually using autorun instead of a reaction and calling a list.length in the autorun function should work and the reaction should be triggered for any change in the list (the only issue is that autorun first call the reaction at initialisation so it would be good to have an option to only perform the autorun function on change (and skip the first call)). Using `reaction` do not work because `reaction` perform a test on the predicate value (so if the predicates return the list length it won't work with replace modifications) whereas `autorun` only rely on observable used into the reaction function to report a "change" when calling an associated observable getter (wich will trigger a change even if the value of this observable actually didn't changed)) 
Implementing deepReactionfor stores should be quite simple, it would just be a matter of mobx_codegen to create a `Set<Atom>` of all atoms of a store and for a deepReaction (and deepAutorun) to listen to any change report in these atoms (or to have a _globalatom for each store and having mobx_codegen to call a `_globalatom.reportObserved()` and `_globalatom.reportChanged()` after any observed or changed report on observable store's field atom)

**Comment by pavanpodila** [comment]
For most use cases, this may not be needed. Probably we can add it based on a flag but even there we have to ensure the nested objects are Stores. How about a PR, so we can start building it ?

**Comment by shyndman** [comment]
What is being suggested here? That the ObservableList store an atom per element? What's the use case that the single atom doesn't cover?

The way that it works now is that if your collection's elements are Stores, you'll get deep observability.

**Comment by deadsoul44** [comment]
Any change in an observable list should trigger a reaction without any additional store.

**Comment by shyndman** [comment]
But that's the case already. Any read operation on `ObservableList` is reported as observed. The `[]` operator, all the `Iterable` methods, `+`, `subList`, `toList`, `length`. What more is required?

**Comment by shyndman** [comment]
But that's the case already. Every list mutation currently triggers a reaction.

`[]=`, `add*`, `remove*`, `retain*`, `length=`, `first=`, `clear`, and the rest. All are in actions.

But any change to objects contained _in_ the list? We can't observe those mutations unless they're `Store`s.

**Comment by slavap** [comment]
Just to clarify, the following is working:
```
final itemsDisposer = reaction(
      (_) => this.items.iterator, // or .length
      (items) {
        print("items change triggered reaction");
       }
);

items.add(item)
```

**Comment by pavanpodila** [comment]
closing it for now as its not really a bug

**Comment by mateusfccp** [comment]
I have this problem when using an `addAll`.

With the following code:
```dart
  @action
  Future<void> getConteudoAttachment() async {
    final infos = await PolyFilePicker.pickFile(null);
    documentInfos.addAll(infos);
  }
```

`documentInfos` is an `ObservableList` of a custom type and `pickFile` returns a `Future<Iterable>` of this same type. Inside my `Observer` I am using `documentInfos` to build a list. The list won't update if I call `getConteudoAttachment()`.

Assigning `documentInfo` to itself solves the problem for me: 
```dart
  @action
  Future<void> getConteudoAttachment() async {
    final infos = await PolyFilePicker.pickFile(null);
    documentInfos.addAll(infos);
    documentInfos = documentInfos;
  }
```
