### ISSUE TITLE
[Question] Why my observer don't rebuilds?

### ISSUE THREAD

**Issue by fabiojansenbr** [mobxjs/mobx.dart#402]
Im testing mobx and created a class to get data from an API and store in a observable list and its working ok.

@observable
`List<UserModel> users = ObservableList<UserModel>();`

  @action
  fetchUsers() async {
    var usersApi = await userApiService.getUsers();
    users = usersApi;
  }

Now i want to add a new item to this list:

`
```
  @action
  addUser() {
    final usr = UserModel(
        email: 'user@user.com',
        firstName: 'User',
        lastName: 'New User');
    users.add(usr);
  }
```
`

When i call addUser action, the user is added to the list, but in my view, the observer dont rebuilds to show the new user. How can i fix it? 

thanks

**Comment by pavanpodila** [comment]
Can you share your  Observer related code ?

**Comment by fabiojansenbr** [comment]
Hi @pavanpodila , my observer is a simple Listview:

```
Observer(
              builder: (BuildContext context) {
                return (usersController.usersList.length != 0)
                    ? Container(
                        height: 300,
                        child: ListView.builder(
                          itemCount: usersController.usersList.length,
                          itemBuilder: (BuildContext context, int index) {
                            final user = usersController.usersList[index];
                            return ListTile(
                              title: Text('${user.firstName} - ${user.email}'),
                            );
                          },
                        ),
                      )
                    : Center(
                        child: CircularProgressIndicator(),
                      );
              },
            ),
```

When i use the action fetchUsers, the observer is ok, but when i try to add a new item to the observableList, the observer dont show the new item.

**Comment by pavanpodila** [comment]
`Observer` only observes the observables used in its immediate `builder` function. In your case, you should wrap the `ListView.builder` inside an `Observer`.

**Comment by fabiojansenbr** [comment]
@pavanpodila thanks for the reply.

I did as you mentioned. Wrap my Listview in a Observer

Here's the complete code:

```
Observer(
            builder: (BuildContext context) {
              return (usersController.usersList.length != 0)
                  ? Container(
                      height: 300,
                      child: Observer(
                        builder: (BuildContext context) {
                          return ListView.builder(
                            itemCount: usersController.usersList.length,
                            itemBuilder: (BuildContext context, int index) {
                              final user = usersController.usersList[index];
                              return ListTile(
                                title:
                                    Text('${user.firstName} - ${user.email}'),
                              );
                            },
                          );
                        },
                      ))
                  : Center(
                      child: CircularProgressIndicator(),
                    );
            },
          ),
```

But the list only rebuilds if i do a Hot Reload. I have made a mistake? Thanks

**Comment by pavanpodila** [comment]
Can you share the complete code in a small repo ? Not able to suggest based on the code you shared.

**Comment by hyperella** [comment]
try
@observable
ObservableList<UserModel> users = ObservableList<UserModel>();

and
flutter packages pub run build_runner watch --delete-conflicting-outputs

**Comment by pavanpodila** [comment]
closing for being stale

**Comment by MoacirSchmidt** [comment]
> 
> 
> `Observer` only observes the observables used in its immediate `builder` function. Hence it can't see into the nested functions. In your case, you should also wrap the `ListView.builder` inside an `Observer`.

Could you please point me to documentation page which says that?

**Comment by subzero911** [comment]
@MoacirSchmidt https://mobx.netlify.app/api/observers
