### ISSUE TITLE
Performance benchmarking compared with Redux/Naive solutions?

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#403]
Hi, and thanks for this wonderful library!

I wonder what is the performance of this library? For instance, do we have some benchmarks, or will it perform badly in what cases?

By the way, is it ready to be used for business apps, or is it still in beta? Since I see updates of codes even 1h ago (wow the developers are so active!) and the version number is still 0.x.x.

P.S. I see some discussions about performance, but they seem to be a little bit old so I wonder the latest situation after all these updates to Mobx, Flutter, and Dart.

**Comment by pavanpodila** [comment]
Hey @fzyzcjy 👋. Yes, MobX.dart is **certainly ready for the prime time**. Don't let the version number deter you. There are folks using it already in production. We haven't done an official perf comparison with other libraries but so far there are no issues related to perf.

The reason we are not 1.0 is purely to fill some gaps in docs. We should be there soon.

**Comment by fzyzcjy** [comment]
Thanks very much! Do we have some showcases? Because I need to persuade my boss, and of course, if I can show some popular apps using it, he will be more convinced compared with only listing some abstract cons :)

**Comment by pavanpodila** [comment]
The folks who are using it have not publicly shared their apps :-)

**Comment by fzyzcjy** [comment]
Oh I thought those apps are on Apple Store or Google Play :)

**Comment by pavanpodila** [comment]
I am sure they are, just that I don't know their names. I only know because of issues and comments filed on the repo :-)

**Comment by fzyzcjy** [comment]
Ah, reasonable :) Maybe there can be some kind of "gathering who is using it" in the future
