### ISSUE TITLE
add ObserverHookWidget

### ISSUE THREAD

**Issue by deadsoul44** [mobxjs/mobx.dart#404]
ObserverStatefulWidget is great to reduce boilerplate code. But I need to use it with flutter_hooks to make api calls. I know that I can make a combination either with StatefulObserverWidget and HooksBuilder or HookWidget and observer.builder but it is a lot of boilerplate. Is it possible to add some kind of ObserverHookWidget to the MobX library?

**Comment by pavanpodila** [comment]
I think it should be part of a separate package, say `mobx_hooks` ? @rrousselGit can suggest better perhaps ?

**Comment by rrousselGit** [comment]
Yeah agreed

**Comment by pavanpodila** [comment]
Closing as it should be a separate package outside of mobx
