### ISSUE TITLE
MST.dart?

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#411]
Hi thanks for the package! I wonder there is a dart version for the MST mobx state tree package?

**Comment by pavanpodila** [comment]
Not yet. What specific features are looking for?

**Comment by fzyzcjy** [comment]
@pavanpodila I like the "automatically get the object from the id" very much

**Comment by pavanpodila** [comment]
Dup of #115

**Comment by fzyzcjy** [comment]
@pavanpodila Maybe not? That one is about snapshots and time travel...

**Comment by pavanpodila** [comment]
I linked it because in principle its about bringing in some MST functionality

**Comment by fzyzcjy** [comment]
Ah reasonable :) So is there any plan of implementing this? Or what should I do?

**Comment by pavanpodila** [comment]
No plans right now. We want to tackle the spy functionality first

**Comment by fzyzcjy** [comment]
Ah OK, so any ideas on how to implement this? If I do that, will my PR be accepted?

**Comment by pavanpodila** [comment]
> Ah OK, so any ideas on how to implement this? If I do that, will my PR be accepted?

A good first step is to pore over the [MST code](https://github.com/mobxjs/mobx-state-tree) and see how they have implemented it. Some of that code is about building a runtime Type System, which is then used during creation of patches and also doing consistency checks.

Once you have your initial PR, we will review with some other folks and eventually merge :-). So go for it!

**Comment by fzyzcjy** [comment]
OK I will try that once I have time! Thanks!

**Comment by DQvsRA** [comment]
Subscribing for PR. Nested data structure is what I really like about MST.

**Comment by pavanpodila** [comment]
I think it would be good to pick and list out the high priority pieces. So far we have:

- [ ] Nested objects
- [ ] Lookup objects from `id`
- [ ] Patches and snapshots
- [ ] Runtime consistency checks
