### ISSUE TITLE
Please add @observer feature to class header

### ISSUE THREAD

**Issue by 5lineofcode** [mobxjs/mobx.dart#412]
Please add the @observer feature to the class header. As can be done in React.

I use mobx in my office project.
I like it very much.
Thank you for bringing mobx on Flutter. :-)

**Comment by pavanpodila** [comment]
For most cases, you should be fine with `Observer`. You could also try extending the `StatelessObserverWidget` for self contained observer widgets. Adding the `@observer` annotation will not save much in code.

**Comment by deadsoul44** [comment]
To be exact, @observer would save one line, StatelessObserverWidget saves two lines, StatefulObserverWidget saves many lines :)

**Comment by pavanpodila** [comment]
I'm going to close this for now. It's a good idea but the benefits are limited and does not warrant an exploration. We can revisit in future.
