### ISSUE TITLE
ObservableMap doesn't set null values

### ISSUE THREAD

**Issue by Vardiak** [mobxjs/mobx.dart#416]
If we add `null` as a new value in an ObservableMap, the map isn't updated.

```
final map = ObservableMap();
map['test'] = null;
print(map);
```

Here, we can see that the map is still `{}`.
It works if we update the value after being set.

```
final map = ObservableMap();
map['test'] = 'value';
map['test'] = null;
print(map);
```

I found where this might come from, I will submit a pull request later today.

**Comment by pavanpodila** [comment]
The code indicates that you are using a plain map. Hope you are using an instance of the `ObservableMap`?

**Comment by Vardiak** [comment]
Sorry I messed up my example, yes it works when using plain map, but not when using an ObservableMap.

**Comment by pavanpodila** [comment]
Fixed and merged
