### ISSUE TITLE
Q: debug reason of rebuild

### ISSUE THREAD

**Issue by DJafari** [mobxjs/mobx.dart#418]
is possible we detect why an observer is rebuild ?

i have too many nested Observer widget, i want debug why my parent Observer is rebuilt ( what variable is changed ? ), how can i debug it ?

thanks

**Comment by jacobaraujo7** [comment]
A good resource I use is to name the observer.
Observer (name: 'debug name', build: ...)

**Comment by DJafari** [comment]
@jacobaraujo7 but i don't see any output in logs

**Comment by pavanpodila** [comment]
@DJafari we don't have logging of the reactions yet. It's a feature I'm going to start working on soon. We call this "spying" in the MobX parlance.

**Comment by DJafari** [comment]
@pavanpodila any update from this feature ?

**Comment by pavanpodila** [comment]
The spy feature is complete and waiting to be merged. Some build failure going on Github Action, which I am not able to resolve :-(. If you want to give it a try, you can take a look in this PR: #451

**Comment by pavanpodila** [comment]
The spy feature is now merged into master, but not yet part of an official release. The docs are still pending and I'll put up a new version once that's ready :-)

**Comment by pavanpodila** [comment]
I'm closing this issue and creating a new one for the docs and new version
