### ISSUE TITLE
Reaction to any model change

### ISSUE THREAD

**Issue by slavap** [mobxjs/mobx.dart#420]
Something like proposed here: https://github.com/mobxjs/mobx.dart/issues/218#issuecomment-509991708
All current workarounds are verbose and require manual field list sync on model structure changes, e.g. new fields added to model.

**Comment by pavanpodila** [comment]
I am happy to assist *any*one willing to start a PR on the `any` reaction :-). I think it would be a great addition to MobX.

**Comment by pavanpodila** [comment]
As @rrousselGit proposed, we need an `any` atom that will report anytime there is a read/write to any of the Store properties. 

- This will be generated by `mobx_codegen` as part of the `Store` code template. 
- We can also configure if this should be generated using the upcoming `@storeConfig` PR (#414)

**Comment by pavanpodila** [comment]
We will pick this up once #391 is merged

**Comment by adrianaxente** [comment]
Cannot we write the any reaction as something like this:

````dart
ReactionDisposer any(
  List<dynamic Function(Reaction)> fns,
  void Function() effect, {
  String name,
  int delay,
  bool fireImmediately,
  ReactiveContext context,
  void Function(Object, Reaction) onError,
}) {
  Set<dynamic> fn(Reaction reaction) => fns.map((f) => f(reaction)).toSet();
  return reaction<Set<dynamic>>(
    fn,
    (c) => effect(),
    delay: delay,
    name: name,
    fireImmediately: fireImmediately,
    context: context,
    equals: (dynamic set1, dynamic set2) {
      return SetEquality().equals(set1, set2);
    },
    onError: onError,
  );
````

Of course, we lose the equals on the individual fns, but maybe the above method can be extended to take in account this case too.

**Comment by emme1444** [comment]
Hey @pavanpodila do you have any updates on this? Now that #414 is merged.

I've looked into the source, but this feels pretty complicated to me. Although with some help I might be able to implement it. (low hopes though) Maybe I'm missing something obvious though (probably).

Would you be willing to help, or is this something you can give a try?

**Comment by pavanpodila** [comment]
Can you try with a function like this:

```dart
  _track(List<Observable> observables, void Function(List<dynamic>) onChange) {
    reaction((_) {
      final list = observables.map((e) => e.value).toList(growable: false);
      return list;
    }, (List<dynamic> changes) {
      onChange(changes);
    });
  }

```

**Comment by emme1444** [comment]
Sorry to be ignorant, but I'm having a hard time figuring out where to put the snippet you suggested.

My vision is to have a function, kind of like `reaction`, but say `any` which takes a `Store` (or list of) and an effect which runs whenever any of the observables change in that `Store`. Is this possible?

You also talked about an `any` atom. I kind of get that, but am struggling to piece it together as well.

I probably am not setup for the job, but would really like this feature. Although I need some help, as you can probably tell.

Thanks for you patience @pavanpodila

**Comment by slavap** [comment]
@emme1444 
This is too late I think, but just an example for possible other people with the same question - if you need to react to ANY change in your store, it could be done the following way:
```dart
autorun((_) {
      var s = mySstore.toString();
      print('autorun: myStore changed');
    });
```
