### ISSUE TITLE
mobx.pub not registered anymore?

### ISSUE THREAD

**Issue by geisterfurz007** [mobxjs/mobx.dart#422]
Opening https://mobx.pub results in an error in firefox, using http://mobx.pub shows this:

![Namecheap domain registered screen](https://user-images.githubusercontent.com/26303198/74083295-c7f20980-4a62-11ea-8959-f6bd13504fee.png)

Did the documentation move somewhere else?

**Comment by pavanpodila** [comment]
@katis has the domain expired?

**Comment by pavanpodila** [comment]
While we wait for the domain to be transferred to my name/account, please use this: https://mobx.netlify.com/
