### ISSUE TITLE
Sorting / Filter

### ISSUE THREAD

**Issue by phcaraujo** [mobxjs/mobx.dart#426]
I'm having trouble making an order in my code and would like to ask for help from you.

**My repository**

> Future<FilialModel> getAll() async {
>     try {
>       var response = await _dio.get('/DASHDVENDAS/2/',
>           options: Options(headers: {
>             "Content-Type": "application/json",
>             "Authorization": "Bearer $token"
>           }));
>       switch (response.statusCode) {
>         ...
>       }
>       return null;
>     } catch (e) {
>       print(e);
>       ...
>     }
>   }

### **My model**

> `import 'dart:convert';
> 
> FilialModel filialModelFromJson(String str) {
>   try {
>     return FilialModel.fromMap(json.decode(str));
>   } catch (e) {
>     print(e);
>     return null;
>   }
> }
> 
> String filialModelToJson(FilialModel data) {
>   try {
>     return json.encode(data.toMap());
>   } catch (e) {
>     print(e);
>     return null;
>   }
> }
> 
> class FilialModel {
>   final List<Vlvendaslj> vlvendaslj;
> 
>   FilialModel({
>     this.vlvendaslj,
>   });
> 
>   factory FilialModel.fromMap(Map<String, dynamic> json) {
>     try {
>       return FilialModel(
>         vlvendaslj: List<Vlvendaslj>.from(
>             json["vlvendaslj"].map((x) => Vlvendaslj.fromMap(x))),
>       );
>     } catch (e) {
>       print(e);
>       return null;
>     }
>   }
> 
>   Map<String, dynamic> toMap() => {
>         "vlvendaslj": List<dynamic>.from(vlvendaslj.map((x) => x.toMap())),
>       };
> }
> 
> class Vlvendaslj {
>   final double vlvenda;
>   final double metadia;
>   final double metaatg;
>   final String filial;
> 
>   Vlvendaslj({
>     this.vlvenda,
>     this.metadia,
>     this.metaatg,
>     this.filial,
>   });
> 
>   factory Vlvendaslj.fromMap(Map<String, dynamic> json) => Vlvendaslj(
>         vlvenda: json["vlvenda"].toDouble(),
>         metadia: json["metadia"].toDouble(),
>         metaatg: json["metaatg"].toDouble(),
>         filial: json["filial"],
>       );
> 
>   Map<String, dynamic> toMap() => {
>         "vlvenda": vlvenda,
>         "metadia": metadia,
>         "metaatg": metaatg,
>         "filial": filial,
>       };
> }

My controller

> import 'package:lojas_guido/app/modules/filial/model/filial_model.dart';
> import 'package:lojas_guido/app/modules/filial/model/filial_repository.dart';
> import 'package:mobx/mobx.dart';
> 
> part 'filial_controller.g.dart';
> 
> class FilialController = _FilialBase with _$FilialController;
> 
> abstract class _FilialBase with Store {
>   final FilialRepository repository;
> 
>   @observable
>   ObservableFuture<FilialModel> filial;
> 
>   _FilialBase(this.repository) {
>     getAll();
>   }
> 
>   @action
>   getAll() {
>     filial = repository.getAll().asObservable();
>   }
> }
> `

 I created a dropdown with the filter options, however, how do I call the specific filter?
 
### **AppBar**

> `AppBar(
>           title: Text("Filiais"),
>           backgroundColor: Theme.of(context).primaryColor,
>           actions: <Widget>[
>             PopupMenuButton<String>(
>               onSelected: optionsActions,
>               itemBuilder: (_) {
>                 return FilialFilter.options.map((String option) {
>                   return PopupMenuItem<String>(
>                     value: option,
>                     child: Row(
>                       children: <Widget>[
>                         Text(option),
>                         Icon(
>                           Icons.keyboard_arrow_up,
>                           color: Colors.black,
>                         )
>                       ],
>                     ),
>                   );
>                 }).toList();
>               },
>             )
>           ],
>         ),

**Comment by pavanpodila** [comment]
Can you enclose the code in backticks (```) ? It's hard read otherwise

**Comment by hmayer00** [comment]
@phcaraujo Take a look at #437 - I don't know whether @pavanpodila will want that code for the repo but you're welcome to use it if you'd like. If you do, lemme know how it goes.

**Comment by pavanpodila** [comment]
Closing this for now. I suggest we move to Discord for all discussions on using MobX. Let's keep Github purely to log issues
