### ISSUE TITLE
ObservableStream - Type erro before code generator

### ISSUE THREAD

**Issue by claudneysessa** [mobxjs/mobx.dart#427]
hello, I'm trying to use ObservableStream and it works but only if I put it as a dynamic type in my case I'm doing it as follows: 

I have an 

@observable
ObservableStream <List <UsersData>>

But when it passes through the code generator it  does it make ObservableStream <List <dynamic>> have any way to fix this?

**Comment by jacobaraujo7** [comment]
Which version of MobX are we talking about?

**Comment by pavanpodila** [comment]
closing for being stale
