### ISSUE TITLE
MobX best pratices guideline

### ISSUE THREAD

**Issue by irvine5k** [mobxjs/mobx.dart#433]
When we are developing our business logic with MobX, arises the need of some good pratices that we can not find on documentation, so I have some questions:

1. Should we declare reactions at UI(Widgets) or at store?
2. Should I inject stores in other stores?
3. Should I use platform branching inside stores like a TextEditingController?
4. When the need of comunicating two stores, It should be by reactions at UI code or It can be made inside the store by "store injection"?

Feel free to input your ideas, other questions and answers.

**Comment by pavanpodila** [comment]
PR has been started: #435. Please comment directly on that to track changes

**Comment by pavanpodila** [comment]
Merged #435
