### ISSUE TITLE
Problem to Edit a ObsevableList

### ISSUE THREAD

**Issue by toshiossada** [mobxjs/mobx.dart#434]
I have a ObservableList, when I add ou filter list everything are fine. But when I try to edit a element in the list and go back to the homepage (pop) my Listview (with Observer) doesnt update. Anyone can hlep me?
![mobx5](https://user-images.githubusercontent.com/2637049/74439543-2f390080-4e4b-11ea-9292-77aafa90054b.gif)

**Comment by pavanpodila** [comment]
Can you share the relevant code ?

**Comment by toshiossada** [comment]
https://github.com/toshiossada/ContactsMobx

We have ListViewBuilder
`Observer(
        builder: (_) {
          return ContactListWidget(
            itemCount: controller.contactsFilteredLength,
            showMessage: () {
              _scaffoldKey.currentState.showSnackBar(snackBar);
            },
          );
        },
      ),`

ContactListWidget
`
ListView.builder(
      itemCount: itemCount,
      itemBuilder: (_, i) {
        var contact = controller.contactsFiltered[i];
        return Dismissible(
          key: UniqueKey(),
          direction: DismissDirection.endToStart,
          background:  Container(
            color: Colors.red,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: DissmissdBackgroundWidget(),
            ),
          ),
          onDismissed: (direction) {
            if (direction == DismissDirection.endToStart) {
              controller.remove(contact.id);

              showMessage();
            }
          },
          child: ListTile(
            onTap: () {
              Modular.to.pushNamed('/details/${contact.id}');
            },
            title: Text(contact.fullName),
          ),
        );
      },
    );
`
Controller
`
  @observable
  ObservableList<ContactModel> contacts = ObservableList<ContactModel>();
  @observable
  String filter;

  @computed
  int get contactsLength => contacts?.length ?? 0;
  @computed
  int get contactsFilteredLength => contactsFiltered?.length ?? 0;
  @computed
  List<ContactModel> get contactsFiltered => contacts
      .where((e) => (e.fullName ?? '')
          .toLowerCase()
          .contains(filter?.toLowerCase() ?? ''))
      .toList();

  @action
  edit(ContactModel c) async {
    var index = contacts.indexWhere((e) => e.id == c.id);
    contacts[index] = c;
  }
`

**Comment by toshiossada** [comment]
https://github.com/toshiossada/ContactsMobx

We have ListViewBuilder
```
Observer(
        builder: (_) {
          return ContactListWidget(
            itemCount: controller.contactsFilteredLength,
            showMessage: () {
              _scaffoldKey.currentState.showSnackBar(snackBar);
            },
          );
        },
      ),
```

ContactListWidget
```
ListView.builder(
      itemCount: itemCount,
      itemBuilder: (_, i) {
        var contact = controller.contactsFiltered[i];
        return Dismissible(
          key: UniqueKey(),
          direction: DismissDirection.endToStart,
          background:  Container(
            color: Colors.red,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: DissmissdBackgroundWidget(),
            ),
          ),
          onDismissed: (direction) {
            if (direction == DismissDirection.endToStart) {
              controller.remove(contact.id);

              showMessage();
            }
          },
          child: ListTile(
            onTap: () {
              Modular.to.pushNamed('/details/${contact.id}');
            },
            title: Text(contact.fullName),
          ),
        );
      },
    );
```
Controller
```
  @observable
  ObservableList<ContactModel> contacts = ObservableList<ContactModel>();
  @observable
  String filter;

  @computed
  int get contactsLength => contacts?.length ?? 0;
  @computed
  int get contactsFilteredLength => contactsFiltered?.length ?? 0;
  @computed
  List<ContactModel> get contactsFiltered => contacts
      .where((e) => (e.fullName ?? '')
          .toLowerCase()
          .contains(filter?.toLowerCase() ?? ''))
      .toList();

  @action
  edit(ContactModel c) async {
    var index = contacts.indexWhere((e) => e.id == c.id);
    contacts[index] = c;
  }
```

**Comment by toshiossada** [comment]
Thanks everyone, I got a resolution here

**Comment by deadsoul44** [comment]
What is the solution?

**Comment by Dealerpriest** [comment]
I also wonder. Setting an index directly in an ObservableList doesn't work for me.

using a combination of .removeAt and then insert works, but that seems like a workaround to me. Any ideas?
