### ISSUE TITLE
Sorting and Filtering of ObservableSets (with code)

### ISSUE THREAD

**Issue by hmayer00** [mobxjs/mobx.dart#437]
I was struggling with setting up sorted/filtered views of my repository data without redoing the work on every build, so I combined ObservableSets with UnmodifiableSetViews to facilitate. I put the file [in this gist](https://gist.github.com/hmayer00/25ace4832ba85f228c76623a1f3fb0a1) so you can take a look at it.

If you feel like this is out of scope for mobx then no worries. But if it's something you'd like to include, then I can add some tests and make a PR for it. Or if you like the idea but not the execution, then let me know and I'll take another swing! I'm still fairly new to dart so it's entirely possible that I've done something stupid.

**Comment by hmayer00** [comment]
Example:
```dart
ObservableSet<int> ints = { 1, 8, 2, 5, 3 }.asObservable();
ObservableSetView<int> evens = ints.filteringView((element) => element.isEven);
ObservableSetView<int> descending = ints.sortingView(compare: (a, b) => -a.compareTo(b));

print(evens.toList()) // => [8, 2]
ints.add(6)
print(evens.toList()) // => [8, 2, 6]

print(descending.toList()) // => [8, 6, 5, 3, 2, 1]
```

You could also combine them e.g. `evens.sortingView`

**Comment by pavanpodila** [comment]
If you want to keep view-specific sort/filter, you could just use a separate `ObservableSet` instance. This is, I'm afraid, outside the scope of MobX and purely an application level concept.
