### ISSUE TITLE
ObservableStream.transform no effect

### ISSUE THREAD

**Issue by mitty1987** [mobxjs/mobx.dart#444]
loginStream = ObservableStream(_loginPresenter.login(loginForm))
        .transform(StreamTransformer.fromHandlers(handleError: (o, s, e) {
          logger.e(s);
    }));

nothing output when error happened，so,I don't know how to use transform.

**Comment by mitty1987** [comment]
Is there any suggestion that you can not only notify the widget to update, but also let the service observe the status so as to open a dialog for example?

**Comment by deadsoul44** [comment]
I am not sure if this is what you are looking for but there is a package for showing snackbar/dialog with mobx:

https://pub.dev/packages/flutter_mobx_helpers
