### ISSUE TITLE
I'd like to contribute to mobx.dart with file generator

### ISSUE THREAD

**Issue by copydog** [mobxjs/mobx.dart#45]
Now, I am writing annotation generator for mobx.dart.
Here is the repo, https://github.com/copydog/mobx_annotation

If you are interested, let me know how I can contribute to the mobx.dart.

**Comment by pavanpodila** [comment]
This is awesome 💯. I suggest you join our team as a collaborator and work on this monorepo. Once you become a collaborator, you can create a branch under this repo and add the **annotation** project at the root level, just like `mobx` or `flutter_mobx`. 

Let me know if that's ok with you and I'll add you 😃

**Comment by copydog** [comment]
yes, it is ok with me, please add me to collaborator

**Comment by pavanpodila** [comment]
Just sent you the invite! Once you accept, you should be able to create a branch and send a PR with the **annotations** project added as a peer-folder of `mobx`. Look forward to seeing it! 

I am sure it will drastically improve the the developer experience of using mobx.dart 👍

**Comment by copydog** [comment]
Should I use the name 'mobx_annotation' or any other name for this project?

**Comment by rrousselGit** [comment]
Code-generators should be published as two separate packages anyway (see https://github.com/google/built_value.dart, https://github.com/dart-lang/json_serializable)

As such we'll likely need two separate names.

**Comment by katis** [comment]
I'd like the annotations to just live in the `mobx` package, that way you just need `mobx` and `mobx_annotations` in your pubspec. I made my own codegen experiments in #46, and you can see the project structure there.

**Comment by pavanpodila** [comment]
The base annotations should be for `observable`, `computed`, `action`, which can live in the `mobx` package itself (as @katis suggested). From an end-user's perspective, it should come with _batteries-included_.

Similarly, we would also need the **`observer`** annotation for `flutter_mobx`.

**Comment by copydog** [comment]
Just like mobx.js includes `observable`, `computed`, `action` in the main package, I think these annotations should be included in the `mobx` package (as @katis  @pavanpodila suggested). Also, `observer` annotation should be in `flutter_mobx` package.

Btw, I like Observer personally, because I want fully control to widgets that need rebuild. I think 'observer' annotation might not be useful for other user too.

Last thing, I vote the name 'mobx_annotations' (as @katis suggested), just like other *mobx.js* package `mobx-persist`, `mobx-devtools`, etc.

**Comment by katis** [comment]
I just want to reiterate that I think having a package called `mobx_annotations` is a bit weird if it contains no annotations. Names like `mobx_codegen`, `mobx_generator` or `mobx_store_generator` at least hint that the package is a code generator, and as such should probably be in `dev_dependencies:` instead of `dependencies`

**Comment by pavanpodila** [comment]
I like the `mobx_codegen` name, as its very explicit about the intent. Are we still keeping a separate package for `mobx_codegen` or making it part of `mobx`. I need to read up on `source_gen` as I can feel some ignorance even asking this question 😉

**Comment by katis** [comment]
@pavanpodila the package needs to be separate, as it should just be a development time dependency.

**Comment by copydog** [comment]
@katis that's right, we want to put it in `dev_dependencies` instead of `dependency`.
I think `mob_generater` name would be great.

**Comment by pavanpodila** [comment]
Closing this as many of ideas are now discussed in #48
