### ISSUE TITLE
How to Serializable a list

### ISSUE THREAD

**Issue by nvthuong1996** [mobxjs/mobx.dart#457]
your code
`var t = '''  [{
   "description": "first one",
   "done": false
  }]''';
final listInstance =
JsonMapper.deserialize<List<Todo>>(t);
`
result

The following assertion was thrown while handling a gesture:
**type List&#60;Object&#62; is not a subtype of type List &#60;Todo&#62;**

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

**Comment by pavanpodila** [comment]
I don't think this is MobX related. You should post this on the JsonMapper project.

**Comment by nvthuong1996** [comment]
thank you.
