### ISSUE TITLE
Prevent widget rerendering on non current screens

### ISSUE THREAD

**Issue by ganeshrvel** [mobxjs/mobx.dart#460]
I am building an app and there is this common widget ([Github link](https://github.com/ganeshrvel/open_cloud_encryptor/blob/new-router-logic/lib/widgets/common_widget/common_widget.dart)) `AlertsScreen` which is rendered along with multiple other widgets. `AlertsScreen` is subscribed to a mob store and it all works just fine except whenever I update the store the `AlertsScreen` is rerendered multiple time.

How do I make sure that `AlertsScreen` widget is only rerendered in the current screen and how do prevent it from rebuilding everywhere else while updating the store?

Currently I am using some workaround like this: https://github.com/ganeshrvel/open_cloud_encryptor/blob/new-router-logic/lib/features/alerts/ui/pages/alerts.dart

alerts.dart
```dart
 @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _alertsStore ??= Provider.of<AlertsStore>(context);
    _disposers ??= [
      reaction(
        (_) => _alertsStore.alertsList.iterator,
        (alertsList) {
          if (ModalRoute.of(context).isCurrent) { // Check whether current screen is rendered 
            buildSnackbar();
          }
        },
      ),
    ];
  }
```
Is there any better way to do this?

**Comment by pavanpodila** [comment]
This is not a MobX issue. You will have to dispose AlertScreen, when not active. Closing it as its an app-specific scenario.
