### ISSUE TITLE
Observer builder error don't throw expect exception

### ISSUE THREAD

**Issue by nvthuong1996** [mobxjs/mobx.dart#472]
When builder function error 1 exception throw with error
`A build function returned null.`
This makes me unable to know where the error occurred

**Comment by pavanpodila** [comment]
Try giving some names to the various Observers that you have, especially the ones that have a branch that may be returning null as output. You can do so:

```dart
Observer(builder: (context){}, name: 'Suspected Observer')
```

**Comment by nvthuong1996** [comment]
i want to show call stack of exception. how i do ?

**Comment by pavanpodila** [comment]
There is no way to show the exception inside the Observer. We are firing the `FlutterError`, which can be seen on the debug console.
