### ISSUE TITLE
Create documentation on writing tests

### ISSUE THREAD

**Issue by MaikuB** [mobxjs/mobx.dart#473]
An issue was recently raised where guidance was needed on writing tests for cases where reactions trigger asynchronous operations (see https://github.com/mobxjs/mobx.dart/issues/448). The issue has since been resolved but it's suggested the docs include a section on how one could write tests. The repository itself has tests for the library itself that can also be used as reference.

I might not get around to this at the moment so can help review contributions should any be submitted.

Edit: if you have some suggestions on topics you'd like to see covered, please add them the thread

**Comment by bakeyevrus** [comment]
@MaikuB, if the snippet below makes sense to you, I can try to create a small section on how we can test `ObservableStream`.

```dart
class AuthRepositoryMock extends Mock implements IAuthRepository {}

class RootStoreMock extends Mock implements RootStore {}

void main() {
  IAuthRepository authRepository;
  RootStore rootStore;
  AuthStore authStore;
  StreamController<AuthStatus> authStatusStream;

  setUp(() {
    authRepository = AuthRepositoryMock();
    rootStore = RootStoreMock();
    authStatusStream = StreamController();
    when(authRepository.authStatus())
        .thenAnswer((_) => authStatusStream.stream);
    authStore = AuthStore(rootStore: rootStore, authRepository: authRepository);
  });

  group('logIn', () {
    final tAccessToken = 'Test token';
    final tAuthToken = AuthToken(accessToken: tAccessToken);
    final tAuthRequest = AuthRequest();
    test('should get AuthToken from repository and change authStatus',
        () async {
      final tExpectedStatus = AuthStatus.authenticated;
      when(authRepository.logIn(any)).thenAnswer((_) {
        authStatusStream.add(tExpectedStatus);
        return Future.value(tAuthToken);
      });

      // LogIn should be called before asyncWhen, so the mock emits new AuthStatus
      await authStore.logIn(tAuthRequest);
      // We should access the value inside reaction, so MobX subscribes to the stream
      await asyncWhen((_) => authStore.authStatus.value != null, timeout: 1);

      verify(authRepository.logIn(tAuthRequest));
      expect(authStore.authToken, equals(tAuthToken));
      expect(authStore.authStatus.value, tExpectedStatus);
    });
  });

  tearDown(() {
    authStatusStream.close();
  });
}
```

**Comment by MaikuB** [comment]
I get where this is going though the issue I have with this is that it use MobX itself to wait for a state change so that it can then proceed verify that the state has changed as expected. This means the test depends on the implementation to have used MobX. IMO, the test should ideally not know about the inner workings as it would end up being a bit more brittle if it did. As `ObservableStream` extends from a `Stream`, the way you would test a `Stream` should also apply to an `ObservableStream` i.e. you should be able to refer to what is mentioned [here](https://pub.dev/packages/test#stream-matchers) when it comes to testing streams
