### ISSUE TITLE
TextFormField do not change its initialValue when rebuild from an Observer

### ISSUE THREAD

**Issue by ramsestom** [mobxjs/mobx.dart#476]
I have an Observer with a builder that return a TextFormField and I defined the initialValue of this TextFormField based on an observed value like this:

 ```
 Observer(
          builder: (context) {
            DateTime date = _certificate.value.date;
            print('build date field $date');
            return TextFormField(
              initialValue: date.toString(),
              ....
```

but when the observed value of _certificate.value.date change, the observer is correctly notified (I can see the 'build date field $date' print in the console) but the TextFormField do not change. I don't understand why as if I change another field of this TextFormField, like for example its decoration labeltext, so if I have:
 ```
 Observer(
          builder: (context) {
            DateTime date = _certificate.value.date;
            print('build date field $date');
            return TextFormField(
              initialValue: date.toString(), 
              decoration: InputDecoration(
                labelText: date.toString(),
              ),   
```

the displayed labelText is correctly changed but not the TextFormField text...

**Comment by pavanpodila** [comment]
TextFormField will require a TextController to update the text. I think that's the way of Flutter. You should setup a `reaction` in a `StatefulWidget` inside the `initState` that tracks the `_certificate.value.date` and updates the `TextController.text` accordingly.

**Comment by ramsestom** [comment]
Yes I fixed it with a controller. 
There is just something I am not sure to understand perfectlly. What does the observer do exactly as a reaction to an observable change. For widgets defined in its builder method, does it recreate completely new one to replace old ones or does it only change their state? I  assume it is the second solution else I wouldn't have to pass to a controller to change a TextFormField text. But as changing the text of a single Text() widget works (while I don't think Text expose its internal text state out of its constructor so you have to create a completely new Text widget if you want to change its text), I am not sure...

**Comment by pavanpodila** [comment]
It will rebuild the Widget from scratch with the `builder` method. The `builder` monitors the observables and re-runs to create a new Widget with the new state. This is how all of Flutter works, so we are not doing anything different, just that mobx monitors observables to trigger the rebuilds.
