### ISSUE TITLE
reaction does not work on ObservableMap

### ISSUE THREAD

**Issue by nothinggift** [mobxjs/mobx.dart#477]
here is the code:
```
// store.dart
 @observable
  ObservableMap<String, dynamic> data = ObservableMap.of({});

// main.dart
reaction((_) => store.data, (msg) => print(msg)); // not work
reaction((_) => store.data['name'], (msg) => print(msg)); // works well

store.data['name'] = 'nickname';
```

Is this a bug? If not, how can I watch a map variable change?

**Comment by pavanpodila** [comment]
The first one will only work when the reference `store.data` changes. There is no direct way of watching any change happening on the map. You will have to specifically watch the appropriate keys with reactions.

**Comment by nothinggift** [comment]
ok...
I think the feature will be very useful, is this on plan?

**Comment by pavanpodila** [comment]
Not at the moment.

**Comment by smkhalsa** [comment]
I think this issue should be reopened. I ran into the same issue, and I definitely think the most intuitive result would be for reactions on the entire ObservableMap to get fired when individual entries are updated.

**Comment by pavanpodila** [comment]
I think that would be a new feature request and should become a new issue. Please file an enhancement request
