### ISSUE TITLE
Store management across pages/screens?

### ISSUE THREAD

**Issue by pbysh** [mobxjs/mobx.dart#478]
There are some similar/related issues in this project: #128, #152, #136. 

I am new to dart/mobx/flutter but experienced in web development, so I am just trying to understand what the best pattern is. It seems the answer is usually to use a Provider to get a handle to your store from deeper widgets. While this works, it makes it really annoying because Provider needs a context to be able to get me the handle, which means I can't get a handle to a store in `initState` of a stateful widget, which is a very common use case of wanting to load something on Widget mounting. What I have to end up doing is putting an initialized flag in the widget and checking if its not true in `didChangeDependencies` then initiating whatever it was I was trying to do there.

I have a small test project that plays around with having a global store handle I can just import from any widget I need the store from, and this agrees with me because I don't need a context to use the store which works for my needs. I have not gotten a super satisfying answer on why this is a bad practice, or if there are any alternatives with similar advantages that are more widely accepted.

Any help or suggestions would be awesome, thanks.

**Comment by d-apps** [comment]
I am developing an app and I am using Get_It for singletons and mobx, retrieving the same instance of one Store in all screens and so far so good, perfomance is good and for me it's ok. Since get_it instance itself is a singleton and it doesn't need context, so I can call it whenever I need.

**Comment by pbysh** [comment]
Ooh, Get_It looks really good and like the kind of stuff that I am talking about! Thanks for the link. I'd still love to hear from others if the pattern I am describing of trying to load things on initState is just not the "dart/flutter way" and if I should instead maybe be using FutureBuilders more or something?

**Comment by emanuel-braz** [comment]
I faced this issue several times, and found get_it as a good and consistent solution for my needs. There is a get_it implementation to deal with Stores through different screens.(stateful widgets dispose injections on dispose event)
It maybe can fit to your needs too. It's under development: https://github.com/emanuel-braz/mobx_store_disposer
And that helpers widgets to deal observables future and streams. https://pub.dev/packages/mobx_widget

If you can, leave some feedback, I'm working on it to improve it. Thx

**Comment by pavanpodila** [comment]
I think it would be great to include these options in the online guide for [Organizing Stores](https://mobx.netlify.app/guides/stores). I'm happy to take in a PR, which I think will benefit everyone. It will be more visible and not a buried treasure like this thread :-).

**Comment by MaikuB** [comment]
Chances are you have a `MultiProvider` that defines all of your stores and it wraps a `MaterialApp`. When you define your routes and the screens for each route, you could get a hold of the stores you need and pass them to the constructor of the widget that represents that screen. 

```
MaterialApp(
   ...
    routes: {
      '/settings': (context) => Consumer<SettingsStore>(
      builder: (_, store, __) => SettingsExample(store),
      ),
      ...
    },
  ...
)
```

This is effectively what the [example app](https://github.com/mobxjs/mobx.dart/tree/master/mobx_examples) does but the name of the route and function that defines how to build the screen has been refactored into an `Example` class. Perhaps including the above snippet and mentioning that point [here](https://mobx.netlify.app/guides/stores#using-proxyprovider-with-a-service) in the docs would add more clarity?

**Comment by pavanpodila** [comment]
closing this discussion
