### ISSUE TITLE
new state for FutureStatus

### ISSUE THREAD

**Issue by DJafari** [mobxjs/mobx.dart#483]
i think `FutureStatus` need new state for example wtih `initialization` name that shows `ObservableFuture` not runned yet, 

`ObservableFuture.value([])` is not good idea, because i want show a message when result is empty, if i use `ObservableFuture.value([])` before call `@action` user see empty message for a seconds

something like this

```dart
Observer(
	builder: (_) {
	  if(_store.itemsFuture.status == FutureStatus.initialization) {
	    return Text("PLEASE CALL ACTION");
	  } else if(_store.itemsFuture.status == FutureStatus.pending) {
	    return CircularProgressIndicator();
	  } else if(_store.itemsFuture.status == FutureStatus.fulfilled) {
	    final List results = _store.itemsFuture.result;
	    if(results.length == 0) {
	      return Text("EMPTY");
	    }
	    return Text("${results.length} ITEMS");
	  }
	  return SizedBox();
	},
)
```

**Comment by pavanpodila** [comment]
You can start with a `null` ObservableFuture to indicate the initial state.

**Comment by DJafari** [comment]
thanks!
