### ISSUE TITLE
MobX on Flutter Web Server target causes page to not render

### ISSUE THREAD

**Issue by mikeryder** [mobxjs/mobx.dart#485]
When MobX is running on the Flutter Web Server target causes the page to not render.

Flutter (Channel beta, v1.17.0-3.3.pre, on Microsoft Windows [Version 10.0.18363.778], locale en-US).

Steps to recreate:
1. Brand new project created with "flutter create"
2. Add "flutter_mobx: ^1.1.0" to pubspec.yml
3. Add "Observer(builder: (_) => Center(child: Container()))" to the build function
4. Run 'flutter run -d "Web Server"

Launching lib\main.dart on Web Server in debug mode...
Syncing files to device Web Server...
lib\main.dart is being served at http://localhost:52510

Running the same app targeting Chrome or Android works, but in the case of my simplified reproduction case throws expected warnings ("No observables detected in the build method of Observer".

Let me know if I can provide additional information.

**Comment by pavanpodila** [comment]
The reason why you see a warning on the console is because no Observables are being referenced inside your `builder` function. Remove the Observer to get rid of the warning.

**Comment by mikeryder** [comment]
I opened the ticket because if the Observer call is included when the app is built for the Web Server target, the page does not render (blank white screen).
