### ISSUE TITLE
Q: Possible to observe changes in model sub-classes

### ISSUE THREAD

**Issue by nea** [mobxjs/mobx.dart#487]
Hi there

I am searching and experimenting for quite some time now but am probably missing something.

The baseline:
I am using mobx, mobx_codegen and flutter_mobx in a Flutter environment
I have a model of data and a store. In the store I have an observable map and an active model.
The map, the active and properties in the model are annotated as observable.

What happens now is that I have an action, which changes (increases) a value in the active model reference and I would like to observe that to update the view. But no matter what I do, the frontend does not update.

I have annotated everything. I tried adding a reaction on the model based on this example: https://mobx.js.org/best/store.html but nothing updates as long as I am only touching the subclass property. If I just set the `active = active` all works fine.

So, as an example:
```
abstract class AStoreBase with Store {

  @observable
  Model active;

  @action
  void increase() {
    model.number++;
  }

  ...
```

and the model
```
class Model {
  @observable
  int number = 0;

  ...
```

If I "observe" the number in the widget nothing updates, only if I "re-set" the `active = active`.

As mentioned, I also tried adding a `reaction((_) => this.toJson()...` with JsonSerialize to the Model, and a `dispose` method, but nothing triggers.

I am probably just missing a small detail but maybe someone can point me in the right direction.

Thanks a lot in advance for any help ^^

**Comment by pavanpodila** [comment]
Any chance your build_runner is not running ?

**Comment by nea** [comment]
Hi @pavanpodila 

`build_runner` is running. Had it running once, also in watch mode. Completes without errors and also generates as expected, all `g` files look good.


Thanks

**Comment by JRamos29** [comment]
Hi.

I have the same problem. In my case i'm using a model as a form. I declared my _form model_ in the store and i'm trying to set it at the onChange value property of a TextFormField. But thus like @nea, i have annotated everything, but with no results. There's some way to do this work? And is this a good practice? 

I have some similar to this:

```
class FormModel {
  @observable
  username
  @action
  setUsername(value) => username = value;
}
```

```
class MyController with Store {
   @observable
   FormModel formModel;
   @action
   setFormModel(value) => formModel = value;
}

```
```
class MyPage {

TextFormField(
    onChange: controller.formModel.setUsername,
}
```

If i declare the username direct on the store works fine as expected.

**Comment by zackhsuan** [comment]
Same issue here. 
I have read the document, says mobx-codegen only converts @observable inside store class, so I suppose it doesnt work as we expect to mark any model class property observable? 

cc @pavanpodila

**Comment by EvertonMJunior** [comment]
This is still an issue, not solved.
