### ISSUE TITLE
MobX on Flutter Web Server target does not render

### ISSUE THREAD

**Issue by mikeryder** [mobxjs/mobx.dart#488]
When MobX is running on the Flutter Web Server target does not render.

Environment: Flutter (Channel beta, v1.17.0-3.3.pre, on Microsoft Windows [Version 10.0.18363.778], locale en-US).

Steps to recreate:

1. Brand new project created with "flutter create"
2. Run 'flutter run -d "Web Server"'
3. Open in browser, confirm page renders
4. Add "flutter_mobx: ^1.1.0" to pubspec.yml
5. Add "Observer(builder: (_) => Center(child: Container()))" to the build function
6. Run 'flutter run -d "Web Server"'
7. Open in browser, screen is all white

Running the same app targeting Chrome or Android works as expected.

Let me know if I can provide additional information.

_Originally posted by @mikeryder in https://github.com/mobxjs/mobx.dart/issues/485
Issue was closed because the original post was poorly written.

**Comment by pavanpodila** [comment]
I think that is for server-side apps that are pure Dart. Not sure if we can run Flutter for that target.

**Comment by mikeryder** [comment]
Was this issue fixed?  If not, I think this is a real issue as people are using Flutter Web more.   Flutter Web is not pure Dart nor a server-side app.  It actually runs in the browser.
