### ISSUE TITLE
Observable not updating in Observer

### ISSUE THREAD

**Issue by knightkill** [mobxjs/mobx.dart#494]
```
  static ObservableStream<List<Product>> emptyProductsResponse = ObservableStream(Stream.value(null));

  @observable
  ObservableStream<List<Product>> _getProductsStream = ObservableStream<List<Product>>(emptyProductsResponse);
  @observable
  List<Product> productList;

  @computed
  bool get loading => _getProductsStream.status == StreamStatus.waiting;

  @action
  void getProducts({Receipt receipt}) {
    final Stream<List<Product>> stream = receipt!=null ? _repository.getProductsForReceipt(receipt):_repository.getProducts();
    _getProductsStream = ObservableStream(stream);
    stream.listen((data) {
      productList =data;
    }).onError((error) {
      errorStore.errorMessage = error.toString();
    });
  }
```
I am using ProductStore to populate the list in the HomePage and using the same store with a new instances to populate the Product on other pages.
But while retrieving Observable in Observer, Observable isn't getting updated.

```
Widget _buildBody() {
  return Observer(
      builder: (context) {
        //log('${!_receiptStore.isNew} && ${_productsStore.loading}');
        if (!_receiptStore.isNew && _productsStore.loading) {
          return CustomProgressIndicatorWidget();
        } else {
            // This code isn't getting invoked.
        }
   );
```
But If I uncomment the "log" above, Observable gets updated and everything works fine

I am instantiating ProductsStore in didChangeDependencies
```
@override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final DataRepository dataRepository =
        Provider.of<DataRepository>(context, listen: false);
    _productsStore = ProductsStore(dataRepository);
    if (!_receiptStore.isNew) {
      _productsStore.getProducts(receipt: _receiptStore.receipt);
    }
  }
```

Also, there are no errors received.

**Comment by yudikarma** [comment]
have same issue

**Comment by pavanpodila** [comment]
Are the properties that are being read (`_receiptStore.isNew` && `_productsStore.loading`) observable? If not, mobx would not know when to react.

**Comment by MrMuMu** [comment]
It seems like it is about if statements, maybe observer is failing to detect the observers inside if statements. In my case, I'm fetching data, and updating ui state to show circular progress. In first fetch the indicator is missing, in second fetch the indicator is there.

**Comment by pr-1** [comment]
Use ObservableList<Product> instead of List<Product> I think that would reflect your changes @knightkill
