### ISSUE TITLE
Any plan for mobx-flutter ?

### ISSUE THREAD

**Issue by jzlxiaohei** [mobxjs/mobx.dart#5]

**Comment by pavanpodila** [comment]
Yup coming next, once I get the mobx project into shape. I'll start the project mostly next week. Happy to take ideas, suggestions and even contributions

**Comment by pavanpodila** [comment]
This has been started and work will continue here: https://pub.dartlang.org/packages/flutter_mobx. Closing this for now

**Comment by pavanpodila** [comment]
The rationale for naming it as flutter_mobx was because [there were enough projects already doing this](https://pub.dartlang.org/flutter/packages?q=flutter_), so thought of keeping the convention
