### ISSUE TITLE
Não é possível trabalhar com objetos personalizados

### ISSUE THREAD

**Issue by ReniDelonzek** [mobxjs/mobx.dart#505]
Eu tenho um objeto comum chamado Pessoa, porém o código gerado aponta erros 

app_controller.dart

`part 'app_controller.g.dart';

class AppController = _AppBase with _$AppController;

abstract class _AppBase with Store {
  @observable
  Pessoa pessoa;
}
`

Código gerado pelo mobx
`// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_controller.dart';

// **************************************************************************
// StoreGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names, unnecessary_lambdas, prefer_expression_function_bodies, lines_longer_than_80_chars, avoid_as, avoid_annotating_with_dynamic

mixin _$AppController on _AppBase, Store {
  final _$pessoaAtom = Atom(name: '_AppBase.pessoa');

  @override
  dynamic get pessoa {
    _$pessoaAtom.reportRead();
    return super.pessoa;
  }

  @override
  set pessoa(dynamic value) {
    _$pessoaAtom.reportWrite(value, super.pessoa, () {
      super.pessoa = value;
    });
  }

  @override
  String toString() {
    return '''
pessoa: ${pessoa}
    ''';
  }
}
`

Erro no compilador:

'_$AppController.pessoa' ('dynamic Function()') isn't a valid override of '_AppBase.pessoa' ('Pessoa Function()').
 
Em suma, corrigindo `dynamic get pessoa` para `Pessoa get pessoa` resolve o problema, porém é bastante trabalhoso ter que fazer isso toda vez que executo o build novamente

**Comment by emanuel-braz** [comment]
@ReniDelonzek blza? Fiz um teste com o cenário descrito e não obtive os mesmos resultados. Se puder, informe a versão do Flutter e das libs que você está utilizando, e tentarei reproduzir o problema novamente.

Aparentemente, está funcionando normalmente nas versões em que fiz o teste, inclusive está sendo feito a tipagem corretamente na geração de código, conforme evidência abaixo.

`app_controller.dart`
```dart
import 'package:mobx/mobx.dart';

part 'app_controller.g.dart';

class AppController = _AppBase with _$AppController;

abstract class _AppBase with Store {
  @observable
  Pessoa pessoa;
}

class Pessoa {}
```

`Generated: app_controller.g.dart`
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_controller.dart';

// **************************************************************************
// StoreGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names, unnecessary_lambdas, prefer_expression_function_bodies, lines_longer_than_80_chars, avoid_as, avoid_annotating_with_dynamic

mixin _$AppController on _AppBase, Store {
  final _$pessoaAtom = Atom(name: '_AppBase.pessoa');

  @override
  Pessoa get pessoa {
    _$pessoaAtom.reportRead();
    return super.pessoa;
  }

  @override
  set pessoa(Pessoa value) {
    _$pessoaAtom.reportWrite(value, super.pessoa, () {
      super.pessoa = value;
    });
  }

  @override
  String toString() {
    return '''
      pessoa: ${pessoa}
    ''';
  }
}
```

Ambiente e libs:
`[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G84, locale en-BR)`
`[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)`
`mobx: ^1.2.1`
`mobx_codegen: ^1.1.0`
`build_runner: ^1.10.0`

Aconselho fechar a issue, caso não esteja mais dando problema. Se não, adicione mais informações, e tentarei ajudar novamente.

**Comment by ReniDelonzek** [comment]
@emanuel-braz obrigado pela atenção.

Eu criei um exemplo mínimo reproduzível do problema [aqui](https://github.com/ReniDelonzek/example_mobx)

Em resumo, utilizo a lib `sqfentity` para geração das classes para uso no banco de dados.
Eu tive esse problema com o mobx > 0.3.9+3, mas não sei informar exatamente qual a versão que passou a ser problemática, mas utilizo essa por conhecer que não tem esse problema.

Ambiente:
`[✓] Flutter (Channel master, 1.19.0-5.0.pre, on Mac OS X 10.15.4 19E287, locale pt-BR)`
Todas as bibliotecas mencionadas em suas últimas versões

**Comment by emanuel-braz** [comment]
@ReniDelonzek testei o código que você enviou e consegui reproduzir o problema :)

O mobx_codegen está fazendo o build antes do sqfentity_gen, e isso é um problema porque o mobx_codegen precisa saber que classe ele vai utilizar para poder tipar corretamente a sua variável.
Como ainda "não existe" a classe Pessoa no momento da primeira geração(ela é gerada pelo sqfentity_gen), o mobx_codegen não encontra e usa o dynamic como tipo.

Acontece que o build_runner tem uma espécie de ordem aleatória para executar esses generators, e precisaria que fosse adicionado uma flag chamada runs_before no build.yaml com o sqfentity_gen, afim de definir a ordem em que esses generators devem ser executados. (sqfentity_gen deve rodar primeiro que o mobx_codegen).

Alguns possíveis workarounds(vulgo gambiarra) para evitar ficar alterando manualmente toda vez que rodar um build:

* Crie uma classe que estenda Pessoa, essa classe vai existir antes da geração de código, o mobx_codegen vai saber qual tipo utilizar e você só vai precisar fazer isso uma única vez.

```dart
class $Pessoa extends Pessoa{} // Utilize o nome que preferir
```

#### Exemplo:
```dart
class $Pessoa extends Pessoa{}
const pessoa = SqfEntityTable(
    tableName: 'Pessoa',
    primaryKeyName: 'id',
    primaryKeyType: PrimaryKeyType.integer_auto_incremental,
    useSoftDeleting: true,
    fields: [
      SqfEntityField('idServer', DbType.integer, defaultValue: -1),
      SqfEntityField('sync', DbType.bool, defaultValue: true),
      SqfEntityField('nome', DbType.text),
      SqfEntityField('nomeFantasia', DbType.text),
]);
```
* Depois use a implementação `$Pessoa`, em vez de acessar a classe `Pessoa` diretamente.

#### Exemplo:
```dart
import 'package:example_mobx/app/db/model.dart';
import 'package:mobx/mobx.dart';

part 'app_controller.g.dart';

class AppController = _AppControllerBase with _$AppController;

abstract class _AppControllerBase with Store {
  @observable
  $Pessoa pessoa;
}
```

#### Código gerado pelo mobx_codegen com o tipo correto(sem o dynamic)
```dart
mixin _$AppController on _AppControllerBase, Store {
  final _$pessoaAtom = Atom(name: '_AppControllerBase.pessoa');

  @override
  $Pessoa get pessoa {
    _$pessoaAtom.reportRead();
    return super.pessoa;
  }

  @override
  set pessoa($Pessoa value) {
    _$pessoaAtom.reportWrite(value, super.pessoa, () {
      super.pessoa = value;
    });
  }

  @override
  String toString() {
    return '''
      pessoa: ${pessoa}
    ''';
  }
}
```

#### Ou faz um cast.

```dart
@observable
dynamic pessoa;
```

depois...
`(pessoa as Pessoa).nome`

**Comment by ReniDelonzek** [comment]
@emanuel-braz desculpe a demora

Entendi o problema, o estranho é que isso nunca acontece se eu usar o mobx na versão <= 0.3.9+3, como mencionei acima, houve alguma mudança para que ele seja executado antes? 

Não consegui achar muita coisa sobre `runs_before` que o senhor mencionou acima, teria como me dar algum exemplo de como deixar a ordem de execução explícita? Acredito que essa seria a melhor solução
