### ISSUE TITLE
Can we get more efficient observable collections?

### ISSUE THREAD

**Issue by khainke** [mobxjs/mobx.dart#507]
Currently observable map and observable list react to every update on the collection, even when only one specific index was referenced and another was changed. An example:

```dart
final ObservableMap<int, int> map = ObservableMap.of({
  1:1, 2:2, 3:3, 4:4, 5:5,
});

final List<int> reactionsOn3 = [];

final remember3 = autorun((_) {
  reactionsOn3.add(map[3]);
});

map[1] = 14;
map[3] = 2;
map[4] = 23;
map[5] = 41;
map[3] = 37;
map[1] = 62;

remember3();
```

```reactionsOn3``` currently holds a snapshot of the value for the watched key for every update on the map:
current: 
```dart
[3, 3, 2, 2, 2, 37, 37]
```

more efficient would be a snapshot of the value for every time the watched key was updated:
```dart
[3, 2, 37]
```

**Comment by pavanpodila** [comment]
This could be an enhancement. This requires some thinking as well to ensure we do the housekeeping correctly around the watched keys.

**Comment by peterweb2005** [comment]
any solution which 1 observer just want to react change on 1 item of a collection?
