### ISSUE TITLE
IDE tools for boilerplate generation/refactoration?

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#508]
Thanks for the library! I wonder whether there are IDE tools (e.g. for Android Studio) for boilerplate generation/refactoration?

**Comment by DJafari** [comment]
you can define a `LiveTemplate` in AndroidStudio

**Template text**:
```
import 'package:mobx/mobx.dart';

part '$FNAME$.g.dart';

class $NAME$ = _$NAME$ with _$$$NAME$;

abstract class _$NAME$ with Store {
  
}
```

**variables**:
| Name  | Default Value                                     |
|-------|---------------------------------------------------|
| FNAME | fileNameWithoutExtension()                        |
| NAME  | capitalize(camelCase(fileNameWithoutExtension())) |

**Comment by fzyzcjy** [comment]
Thanks! I already use the live templates :) I wonder whether there are code jumping helpers: Say there is `abstract class _AppleStore with Store {@observable int appleCount;}`. When I use it like `print(appleStore.appleCount)`, I often ctrl-click the "appleCount" to read its source code. However, I will jump into the generated class, instead of my `_AppleStore` ...

**Comment by asavchuk** [comment]
> I wonder whether there are code jumping helpers

it wound be nice to have such a functionality

**Comment by fzyzcjy** [comment]
@asavchuk after half a year, I still do not find any such tools :/
