### ISSUE TITLE
Observable vs. @observable 

### ISSUE THREAD

**Issue by zackhsuan** [mobxjs/mobx.dart#510]
Hi All, just found an interesting situation here:

suppose I have model class: SampleItem, it has only one boolean type property called isEnabled:
```
class SampleItem {
  bool isEnabled = false;
}
```

I tried to have a store to have an observable property which is the type of SampleItem:
```
// store

@observable 
SampleItem item = SampleItem();

@action
enableItem(bool enabled) {
  item.isEnabled = enabled;
}
```

I would like to make the widget be reactive when I am calling enableItem of the store.
so I changed the property of isEnabled in SampleItem to wrap with `@observable`. it become: 
```
@observable
bool isEnabled = false;
```

But it just didnt re-render when I call enableItem(). I spent 2 hours of trying different approaches, no luck.

when I changed `@observable` in SampleItem to 
```
var isEnabled = Observable(false);
```

It worked. But this just doesnt make sense, I can't make all properties to use without annotations.

anyone can give me any ideas?

**Comment by maxim-toleutai** [comment]
@zackhsuan did you use https://github.com/mobxjs/mobx.dart/tree/master/mobx_codegen, when you try to use @observable annotation? without this, that will not work

**Comment by kaashyapan** [comment]
Same issue. I'm using codegen.
