### ISSUE TITLE
Incorrect "observables not detected" stdout

### ISSUE THREAD

**Issue by 1N50MN14** [mobxjs/mobx.dart#515]
Trying to transform:
```dart
Observer(builder:(context)=>WidgetThatContainsAnObservable());
```
Into:
```dart
WidgetThatContainsAnObservable.mobx(context);
```
Using:
```dart
extension X_ on Widget
{
  Widget mobx(BuildContext context) => Observer(builder:(context)=>this);
}
```
It works, but observer_widget_mixin.dart (`L82`) still logs `No observables detected in the build method of Observer`.

**Comment by pavanpodila** [comment]
The builder function needs to have at least one observable that is read. I don't see any in your case, which is why the warning is being printed

**Comment by 1N50MN14** [comment]
It does. `this` refers to `WidgetThatContainsAnObservable`.
