### ISSUE TITLE
ObservableList trigger update on nested item change

### ISSUE THREAD

**Issue by nrehm** [mobxjs/mobx.dart#516]
Hey currently trying to figure out if this is even possible:

Given the following structure.

channel: [
   channel1: { messages: [ "msg1", "msg2"] },
   channel2: { messages: [ "msg1", "msg2"] },
]

I have an ObservableList on channel and want to have the widget update if channel.message gets a new item.

```
  Channel updateChannel = channels.firstWhere((element) => element.id == payload.id);
  updateChannel.messages = [...updateChannel.messages, payload.message];
```

Is it possible to trigger an update that the new message is observed inside the widget.
After an hot-reload the state updates but not before.

If i pull the messages out into something like activeMessages and update them directly its working as intended.

**Comment by pavanpodila** [comment]
MobX does not handle nested updates. To do that you will have to make the `messages` into an `ObservableList<Message>`
