### ISSUE TITLE
mobx: ^1.2.1, cannot implement listChange.added, listChange.index

### ISSUE THREAD

**Issue by MarcoGolin** [mobxjs/mobx.dart#523]
I was using normally, after updating my version I can no longer use the [listChange.added]    
 ([url](url
![sdfadsfasdfasdfasdf](https://user-images.githubusercontent.com/26425460/84685954-14fe5480-af09-11ea-9ee1-d11c9e909c03.PNG)
))

**Comment by pavanpodila** [comment]
The signature has changed to better reflect the changes happening on the list. This is part of a recent PR.

```dart
class ListChange<T> {
  ListChange({ this.list, this.elementChanges, this.rangeChanges});

  final ObservableList<T> list;
  final List<ElementChange> elementChanges;
  final List<RangeChange> rangeChanges;
}

```

**Comment by 926** [comment]
Hi @pavanpodila,
Thank you for upgrading this package,
Could you please show us how to use this new signature in the example provided by @MaikuB ?
His example project seems like a common one,
And I might not be the only one to not to grasp how to use these....

**Comment by Emadeddin-eibo** [comment]
Any updates on this issue? I'm facing the same syntax migration issue with no clear documentation to solve it!
