### ISSUE TITLE
@computed with arguments

### ISSUE THREAD

**Issue by danielwalczak** [mobxjs/mobx.dart#525]
Is there equivalent of [computedFn](https://github.com/mobxjs/mobx-utils#computedfn) form mobx-utils ?

**Comment by pavanpodila** [comment]
We don't have an equivalent but it could be implemented with a combination of an Observable and a reaction.

**Comment by danielwalczak** [comment]
Thanks I will look into reactions.

**Comment by ezze** [comment]
@pavanpodila What do you mean exactly? Any guide how it can be achieved, please?
