### ISSUE TITLE
flutter packages pub run build_runner watch --delete-conflicting-outputs

### ISSUE THREAD

**Issue by anchao-lu** [mobxjs/mobx.dart#526]
Bad state: Unexpected diagnostics:
/Users/lu/Desktop/Flutter/development/flutter/bin/cache/dart-sdk/lib/internal/internal.dart:172:16 - This requires the 'non-nullable' language feature to be enabled.
[SEVERE] Failed after 71ms

**Comment by yacineblr** [comment]
Same for me.
Did you find the solution?

**Comment by giri-jeedigunta** [comment]
Are you seeing this error when you are using the ```build_runner``` I have added a comment here see if it helps: https://github.com/mobxjs/mobx.dart/issues/552

**Comment by leonardocustodio** [comment]
Clean cache (flutter clean) and upgrade project dependencies should solve that issue.
