### ISSUE TITLE
Observer doesn't rebuild without hack

### ISSUE THREAD

**Issue by Blquinn** [mobxjs/mobx.dart#527]
Using flutter_mobx I've encountered an issue where the Observer rebuild is not triggered in the following code.

```dart
// Store
part 'request_list.g.dart';

class RequestListStore = RequestListStoreBase with _$RequestListStore;

abstract class RequestListStoreBase with Store {
  ObservableList<RequestModel> requests = ObservableList.of([
    RequestModel(url: 'http://google.com'),
    RequestModel(url: 'http://yahoo.com'),
  ]);

  @observable
  int activeRequest = 0;
}

// Widgets 

class RequestMenu extends StatelessWidget {
  final store = RequestListStore();

  @override
  Widget build(BuildContext context) {
    return CupertinoScrollbar(
      child: Observer(
        builder: (_) {
          return ListView.builder(
            itemCount: store.requests.length,
            itemBuilder: (_, idx) {
              final req = store.requests[idx];
              return Padding(
                padding: const EdgeInsets.all(4),
                child: ButtonTheme(
                  height: 50,
                  child: FlatButton(
                    onPressed: () => store.activeRequest = idx,
                    color: idx == store.activeRequest ? Colors.grey : Colors.transparent,
                    child: Text(req.url),
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
```

Adding the following line triggers the observer to rebuild on changes.

```dart
class RequestMenu extends StatelessWidget {
  final store = RequestListStore();

  @override
  Widget build(BuildContext context) {
    return CupertinoScrollbar(
      child: Observer(
        builder: (_) {
          store.activeRequest; // <- Add this line, call get on activeRequest
          return ListView.builder(
            itemCount: store.requests.length,
            itemBuilder: (_, idx) {
              final req = store.requests[idx];
              return Padding(
                padding: const EdgeInsets.all(4),
                child: ButtonTheme(
                  height: 50,
                  child: FlatButton(
                    onPressed: () => store.activeRequest = idx,
                    color: idx == store.activeRequest ? Colors.grey : Colors.transparent,
                    child: Text(req.url),
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
```

My first guess was that by adding this line, I'm subscribing (reporting the observation) the observer to changes on store.activeRequest, however that function is already called multiple times when the ListView builds in the color field. So, I can't really figure out what is going on.

My apologies if this is covered in the docs, I couldn't find anything about it. Thanks in advance for your help!

**Comment by pavanpodila** [comment]
Since you have `store.requests.length` as your `itemCount`, it should trigger the rebuilds whenever the count of the requests changes. We do the same thing in the [Todos example](https://github.com/mobxjs/mobx.dart/blob/04dff4791e060c12cd188381348a2418a14d6b91/mobx_examples/lib/todos/todo_widgets.dart#L48). Looks like there might be some issue in the adding of requests

**Comment by Blquinn** [comment]
So I'm not adding requests to RequestListStore.requests, but rather I am just changing RequestListStore.activeRequest, which represents and index to the "active" request. The list item that is active is filled in grey instead of white. Based on the TODO example i was also able to find a second solution which is not a hack.

```dart
class RequestMenu extends StatelessWidget {
  final store = RequestListStore();

  @override
  Widget build(BuildContext context) {
    return CupertinoScrollbar(
      child: Observer(
        builder: (_) {
          return ListView.builder(
            itemCount: store.requests.length,
            itemBuilder: (_, idx) {
              final req = store.requests[idx];
              return Padding(
                padding: const EdgeInsets.all(4),
                child: ButtonTheme(
                  height: 50,
                  child: Observer( // <-- Added a second observer here
                    builder: (_) => FlatButton(
                      onPressed: () => store.activeRequest = idx,
                      color: idx == store.activeRequest ? Colors.grey : Colors.transparent,
                      child: Text(req.url),
                    ),
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
```

I'm a little confused about why my initial code didn't rebuild. If I have the ListView.builder wrapped in an observer, shouldn't the whole ListView get re-built when activeRequest changes?

**Comment by pavanpodila** [comment]
Observer's builder function only knows about the observables in its immediate context. It can't know about observables used inside nested functions, since it has no way of knowing. Unfortunately, a side effect of closures in Dart suggest that all code (including code in nested functions) is in the same scope, when in reality the runtime scopes are different. So the fact to remember is that **only observables in immediate context** are tracked by MobX Observers.

**Comment by Blquinn** [comment]
Ah, ok that clarifies it for me, thank you!

So in my case, the context to the Observer's scope is lost inside of the ListView.builder's itemBuilder function. The pattern would then be to add an additional Observable any time a closure cuts off the access to a parent Observable.

I also noticed that instead of the whole listview being rebuilt each time this value changes, each item of the view is rebuilt instead. It's unclear to me how that would effect performance.

**Comment by pavanpodila** [comment]
If you keep the Observer at the ListItem level, a change in the item will not re-render the entire list. You gain performance boost when you reduce the amount of re-rendering.

**Comment by Blquinn** [comment]
Great, thanks for your help! Closing the issue.
