### ISSUE TITLE
no @required warning in store constructor

### ISSUE THREAD

**Issue by imerkle** [mobxjs/mobx.dart#528]
```
part 'mystore.g.dart';

class Mystore = _Mystore with _$Mystore;

abstract class _Mystore with Store {
  _Mystore(
      {@required this.title});

  @observable
  String title;
}

```
`
Mystore() //no @required warning here`

**Comment by pavanpodila** [comment]
`@required` is meant for Flutter Widgets and won't have any effect for pure Dart code.

**Comment by imerkle** [comment]
But this does show warning

```
class A{
  A({@required this.a});
  String a;
}

```

`A() //The parameter 'a' is required.dartmissing_required_param`

**Comment by pavanpodila** [comment]
Does it have to do with the analyzer.yaml settings?

**Comment by rrousselGit** [comment]
@/required is not associated to a lint rule, so no.

It may be the linter that doesn't support this case.
I'd suggest making an issue. 

Although I doubt it'll get fixed, as "required" is becoming an official keyword.
