### ISSUE TITLE
MobX Todos example has an unused observable

### ISSUE THREAD

**Issue by Fleximex** [mobxjs/mobx.dart#529]
I was following along with the Todos example and noticed that the tutorial states the following for the AddTodo widget:
_Similarly, here is the AddTodo widget that observes the list.currentDescription and also fires the list.changeDescription action._
https://mobx.netlify.app/examples/todos

The AddTodo widget has no Observer widget. The action is never used. Additionally the currentDescription observable in the TodoList store is never read and only directly written to.

My question being: why is the observable currentDescription not written to via an `@action` instead of directly. The tutorial shows the `changeDescription` method existing in the store but it doesn't exist in the latest version on GitHub.

It might be good to state the purpose of `currentDescription` or remove it to prevent confusion.
My guess for `currentDescription` existing is that potentially you can leave the todo page and come back still having your last entered text in there. And also you could use the current user input to, for example, check if a todo title already exists while the user is typing.

But in the example it serves no purpose.

The AddTodo widget uses the TextController instead to clear the TextField and the TextField's onSubmitted value to pass the description when creating a new Todo.

Maybe I'm missing something, but it would be nice if someone can clarify.

**Comment by pavanpodila** [comment]
I think its time for a quick PR that rectifies this :-). Want to take a shot ? Let's fix this to avoid confusion for others too 👍

**Comment by pr-1** [comment]
@pavanpodila  Is this resolved yet ? I would like to take this up and remove the unwanted observable for simplification.

**Comment by Fleximex** [comment]
@pr-1 I don't think it is. I have not taken this up.

**Comment by pr-1** [comment]
Yup I have made the changes and opened a PR

**Comment by leonardocustodio** [comment]
@pr-1 since this was already merged, can you close the issue? (;

**Comment by pr-1** [comment]
@leonardocustodio I am sorry but I cannot close it as I did not open it. 
@Fleximex  Please close the issue.
