### ISSUE TITLE
Question and maybe a Widget idea

### ISSUE THREAD

**Issue by Ascenio** [mobxjs/mobx.dart#530]
Currently in MobX if we're intending to use a reaction at some point we, generally, got to make the page Widget a StatefulWidget, in order to dispose every reaction. Not only that, but the code also get's verbose and note reusable, so I think we could delegate reactions to a Widget and make the page stateless. Something like this:

```dart
class HomePage extends StatelessWidget {
@override
  Widget build(BuildContext context) {
    return Reactor(
      reactions: [
        reaction((_) => _controller.status, (status) {
          // Some code..
        }); 
        reaction((_) => _controller.errors, (errors) {
          // Even more code
        }); 
      ],
      child: Scaffold(
        // Waaay more widgets down there.
      );
    );
  }
}
```
This gets even nicer because you could encapsulate the `Reactor` with your own implementation and reuse common reactions.
However I'm not really sure if it's pratical or needed, so would like to hear some thoughts from you guys.

**Comment by Ascenio** [comment]
Similar to [Bloc](https://pub.dev/packages/flutter_bloc)'s BlocConsumer

**Comment by Rudiksz** [comment]
The flutter_mobx package has an Observer widget. Isn't that just a reaction?

**Comment by MaikuB** [comment]
There was some work done to implement reactions as hooks but work on it has stopped. It can be found in [here](https://github.com/rrousselGit/mobx.dart/tree/backup/flutter_mobx_hooks). You could try to see if what's there works or perhaps even consider completing the work

**Comment by Ascenio** [comment]
> The flutter_mobx package has an Observer widget. Isn't that just a reaction?

The thing is when you use a reaction you have to dispose it later, and this is not possible directly through a Observer.

**Comment by Ascenio** [comment]
> There was some work done to implement reactions as hooks but work on it has stopped. It can be found in [here](https://github.com/rrousselGit/mobx.dart/tree/backup/flutter_mobx_hooks). You could try to see if what's there works or perhaps even consider completing the work

Thanks, I didn't know MobX had pre-made hooks. However, I'm not really sure if I should use it because I don't know if it's stable, they aren't even mentioned in the docs :disappointed:

**Comment by MaikuB** [comment]
MobX doesn't have pre-made hooks. To re-iterate the work on it had stopped and was in a fork. This means it was not released/merged in so it's not going to be in the docs. You could pick up from where the work left off

**Comment by Ascenio** [comment]
I though MobX had it because I saw the hooks being [merged](https://github.com/mobxjs/mobx.dart/pull/43)

**Comment by MaikuB** [comment]
That no longer exists in the repo and was not released. There were discussions on having it moved to be part of the `flutter_hooks` package instead.
