### ISSUE TITLE
Re - Observer is suppressing Flutter exceptions in its Reaction

### ISSUE THREAD

**Issue by ganeshrvel** [mobxjs/mobx.dart#532]
The reaction disposer is suppressing the exception in its reaction.
I see that there is already an issue: https://github.com/mobxjs/mobx.dart/issues/259

There is no clear documentation anywhere how to handle such a situation. 

I tried something like this:
```dart
_disposers ??= [
      reaction(
        (_) => _store.someValue,
        (bool someValue) {
            if(someValue) // do something
        },
        onError: (e, _) {
          print('e');
        },
      ),
]
```

The above code works fine but is there a way to capture the  reaction disposer exceptions at a common place? It will be difficult and repetitive to use `onError` parameter everywhere.

The below code didn't work as well.
```dart
FlutterError.onError = (FlutterErrorDetails details) async {
  print(details.exception);
};
```

**Comment by pavanpodila** [comment]
You can setup a listener for all reaction errors on the ReactiveContext. See this for an example: https://github.com/mobxjs/mobx.dart/blob/43524ae9184dc00729f63fea8561eabcc5c9f850/mobx/test/context_test.dart#L21

It uses the `mainContext.onReactionError()` API
