### ISSUE TITLE
mobx_codegen generates wrong code when a store has late observable fields?

### ISSUE THREAD

**Issue by kennethnym** [mobxjs/mobx.dart#537]
I wanted to start migrating my flutter project to nnbd, but it seems like `mobx_codegen` has not migrated to nnbd just yet. With the following code:
```dart
import 'package:mobx/mobx.dart';

part 'store.g.dart';

class TestStore = _TestStore with _$TestStore;

abstract class _TestStore with Store {
  @observable
  late String field;
}
```
`mobx_codegen` would interpret `String` as the field name instead of `field`. Below is a snippet of the generated code:
```dart
@override
dynamic get String {
  _$StringAtom.reportRead();
  return super.String;
}
```
Here, `mobx_codegen` generated getter for `String` but not for `field`. It did the same for the setter.  

I was able to reproduce this in a brand new flutter project:
1. `flutter create test_project`
2. install `mobx` and `mobx_codegen`
3. enable nnbd and change dart sdk version constraint in `pubspec.yaml`
4. create `store.dart`
5. `flutter pub run build_runner build`
5. `store.g.dart` fails

**Comment by tuskinhu** [comment]
@MrCreeper1008 
Mine is happening same thing, in dart file is ok, but in g.dart codegen put dynamic, even if my type is a class.

You still getting this error on codegen?

**Comment by simonkimi** [comment]
same issue

**Comment by pavanpodila** [comment]
Unable to reproduce in `mobx_codegen 2.0.0`
