### ISSUE TITLE
Reaction is not fired when a list observable is changed.

### ISSUE THREAD

**Issue by divyanshub024** [mobxjs/mobx.dart#538]
I have an observable of type `List`.

```
@observable
  List<Conversation> conversations = [];
```
 and inside `action` I'm fetching the data and adding it to the `conversations`.

```
conversations.addAll(data);
```
this should fire the reaction and UI under `observer` should change but it's not happening
unless until I use the `=` operator. 

```
conversations += data;
```

Similarly all the other list methods like `add`, `remove` etc.

Please let me know what's the solution for this because right now after every `add` or `remove` method I'm calling `=` operator to fire the reaction.

**Comment by MaikuB** [comment]
Change `conversations` to be an `ObservableList<Conversation>`

**Comment by divyanshub024** [comment]
@MaikuB I've tried that but still it's the same.

**Comment by MaikuB** [comment]
Did you run the code generation after you changed the type?

**Comment by divyanshub024** [comment]
Yes and I re-installed the app.

**Comment by MaikuB** [comment]
Hmm doesn't sound right. You'll probably need to setup a minimal sample app to reproduce this. In my experience, the code generator might not apply the changes properly. Another thing is I always run it with the `delete-conflicting-outputs` flag

**Comment by pavanpodila** [comment]
any update @divyanshub024 ?

**Comment by rodrigolmacedo** [comment]
> 
> 
> I have an observable of type `List`.
> 
> ```
> @observable
>   List<Conversation> conversations = [];
> ```
> 
> and inside `action` I'm fetching the data and adding it to the `conversations`.
> 
> ```
> conversations.addAll(data);
> ```
> 
> this should fire the reaction and UI under `observer` should change but it's not happening
> unless until I use the `=` operator.
> 
> ```
> conversations += data;
> ```
> 
> Similarly all the other list methods like `add`, `remove` etc.
> 
> Please let me know what's the solution for this because right now after every `add` or `remove` method I'm calling `=` operator to fire the reaction.
here works fine @divyanshub024 

<strong>my store</strong>
```
import 'dart:async';

import 'package:mobx/mobx.dart';
part 'minha_store.g.dart';

class MinhaStore = _MinhaStoreBase with _$MinhaStore;

abstract class _MinhaStoreBase with Store {
  ObservableList<String> listStrings =
      ObservableList<String>(name: "listStrings");

  @action
  Future<void> populateList() async {
    listStrings.add(DateTime.now().toIso8601String());
  }

  @action
  Future<void> pupulateListAll() async {
    List<String> temp = List();
    for (var i = 0; i < 5; i++) {
      await Future.delayed(Duration(seconds: 1))
          .then((_) => temp.add(DateTime.now().toIso8601String()));
    }

    listStrings.addAll(temp);
  }
}
```

<strong>my view</strong>
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                OutlineButton(
                    onPressed: () => minhaStore.populateList(),
                    child: Text('Add single')),
                OutlineButton(
                    onPressed: () => minhaStore.pupulateListAll(),
                    child: Text('Add Multi')),
              ],
            ),
            Divider(),
            Expanded(
              child: Observer(builder: (context) {
                if (minhaStore.listStrings.isEmpty) {
                  return Text('Empty list');
                }
                return ListView.builder(
                  itemCount: minhaStore.listStrings.length,
                  itemBuilder: (context, index) =>
                      Center(child: Text('${minhaStore.listStrings[index]}')),
                );
              }),
            ),
          ],
        ),
      ),
    );
  }
```
