### ISSUE TITLE
[flutter_mobx] Use condition inside Observer to render one or the other widget

### ISSUE THREAD

**Issue by andreyeurope** [mobxjs/mobx.dart#543]
Hello there Mobx devs and users.
I am using the following code in my `Observer` widget:
```
Observer(
                  builder: (context) => _signUpStore.signUpState == SignUpState.Start
                      ? const Spacer()
                      : const SizedBox(
                          height: 80,
                        ),
                )
```

But I get the message `No observables detected in the build method of Observer`.

Is it not possible to use the `Observer` in this way or how should I go about rendering a widget based on a met condition from the store?

**Comment by MaikuB** [comment]
Can you provide a minimal app to reproduce this? I've used conditions but haven't run across issues

**Comment by andreyeurope** [comment]
I managed to resolve the issue by doing `flutter clean`.
