### ISSUE TITLE
Generating even unchanged files?

### ISSUE THREAD

**Issue by fluxion8** [mobxjs/mobx.dart#547]
I'ts should be not generate unchanged files.Can i specify file name for generation?

**Comment by giri-jeedigunta** [comment]
@fluxion8 are you talking about ```build_runner```? if so refer this issue: https://github.com/mobxjs/mobx.dart/issues/552

**Comment by giri-jeedigunta** [comment]
@fluxion8 This is an issue with build runner reported here on flutter: flutter/flutter#63556 This could be causing the issue.
