### ISSUE TITLE
Using ObservableFutere with reaction not working

### ISSUE THREAD

**Issue by danielwalczak** [mobxjs/mobx.dart#549]
first example is not working as expected, callback is not called on `fulfilled`, the second one is working but Im loosing all the information from future instance.

```
ObservableFuture action = ObservableFuture(async());

reaction(() => action, (ObservableFuture result) = print(result.status);
// output
// FutureStatus.pending

vs
reaction(() => action.status, (status) = print(status);
// output
// FutureStatus.pending
// FutureStatus.fulfilled
```

**Comment by pavanpodila** [comment]
This is the intended behavior as the  ObservableFuture instance on its own is not really observed by MobX (I know ironic right ??). What gets observed are the `status`/`error` and other properties inside the ObservableFuture. Hence the second reaction works and not the first.
