### ISSUE TITLE
[question] why `reportWrite` always call `reportChanged` even oldValue is equal to newValue?

### ISSUE THREAD

**Issue by meritozh** [mobxjs/mobx.dart#556]
https://github.com/mobxjs/mobx.dart/blob/5095e966fe591d223c7730579de2f4778a7ff465/mobx/lib/src/core/atom_extensions.dart#L9-L21

I think it should compare `oldValue` `newValue` first. If state is not changed, why we need call `build`?

**Comment by pavanpodila** [comment]
Agree that the values should be compared. For primitives its easier to just do a `==`, however for more complex structures, it would need an `EqualityComparer<T>`. This will have to be incorporated at some level to make it a thorough comparison. I am open for PRs, if you are keen on getting this in 👍 . Will be more than happy to review.
