### ISSUE TITLE
Deeply watch an ObservableMap of ObservableMaps?

### ISSUE THREAD

**Issue by shilangyu** [mobxjs/mobx.dart#560]
```dart
// store.dart
@observable
ObservableMap<String, ObservableMap<String, String>> data = ObservableMap.of({});

// main.dart
reaction((_) => store.data.asObservable(), (msg) => print(msg)); // does not work
```

Is it possible to listen to `store.data` deeply? I would like to react to all things below:

```dart
// currently triggers reaction
store.data =  ObservableMap.of({});
store.data['newKey'] = ObservableMap.of({});
store.data.remove('newKey');
// does not trigger reaction
store.data['newKey']['deepNewKey'] = 'hello';
sotre.data['newKey'].remove('deepNewKey');

```

**Comment by avioli** [comment]
You need to walk the whole observable map within your observation function.

Returning `store.data.asObservable()` isn't walking the deeply nested values.

Use something that visits every value of the sub-map:

```
reaction(
  (_) => store.data
      .map((k, submap) => MapEntry(k, submap.map((k2, v2) => MapEntry(k2, v2)))),
  (msg) => print(msg),
);
```

Fires the effect as expected.

NOTE: if you don't care for the actual data, but want the effect to run, then a forEach works fine - your observation function needs to access the length, keys and values for them to be observed.

**Comment by shilangyu** [comment]
This seems to work. Thanks!
