### ISSUE TITLE
Docs not rendering code snippets

### ISSUE THREAD

**Issue by difelice** [mobxjs/mobx.dart#574]
Docs are no longer rendering code snippets after recent package upgrades.

**Comment by pavanpodila** [comment]
Thanks for catching this @difelice. There is some compatibility issue with some syntax highlighting plugin in the Docz tool that I'm using. I am going to switch over to **Docusaurus** as Docz is getting very buggy and slow.

**Comment by pavanpodila** [comment]
This is now fixed (as part of #575) and will go live on https://mobx.netlify.app
