### ISSUE TITLE
How to change Observable<T> value?

### ISSUE THREAD

**Issue by subzero911** [mobxjs/mobx.dart#579]
I have a plain Dart model (not a MobX store).
I have a field `final Observable<String> fullName;` in it.
When I try to change its value
`currentProfile.fullName.value = value;`
I catch the following error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:mobx/src/core/context.dart': Failed assertion: line 214 pos 18: '_state.isWithinBatch': Side effects like changing state are not allowed at this point. Please wrap the code in an "action". Tried to modify: Observable@8
```
I also tried to put a value mutation into Action as proposed:
`mobx.Action(() => _editableProfile.fullName.value = newValue)`
but the error still persists.
So, how to change a value of Observable?

**Comment by tek08** [comment]
Try `runInAction(() { currentProfile.fullName.value = value; }`  ?

**Comment by subzero911** [comment]
Thanks, it works great!
