### ISSUE TITLE
Private action in stores question

### ISSUE THREAD

**Issue by miguelpruivo** [mobxjs/mobx.dart#581]
Hi, how would one set a private `@action` to mutate an `@observable`?

For example:
```
class Foo {

Foo() {
  _doSomething();
}

@observable
int bar;

@action
void _doSomething() {
  bar = 10;
}

}
```
The above code doesn't generate properly, however, if I remove the `@action` annotation, it works and it actually mutates properly and the view will rebuild accordingly. But the docs mentioned that _every method that mutates an observable, must be an action, otherwise an exception will be thrown_. But so far, it works just fine.

How's the correct way to have private methods that mutate observables with MobX?

Thanks!

**Comment by MisterJimson** [comment]
In my experience the code generates properly with private actions. Perhaps in this example because you are calling the method in the constructor the field is already up to date on the first build.

**Comment by miguelpruivo** [comment]
The thing is that I'm not able to have private methods within my `Store` annotated as `@action`.

**Comment by MisterJimson** [comment]
Can you provide an reproducible example? I do this all the time.

**Comment by pavanpodila** [comment]
stale
