### ISSUE TITLE
Generate files for annotations of multiple packages

### ISSUE THREAD

**Issue by awagege** [mobxjs/mobx.dart#582]
Projects have multiple packages, and CodeGen cannot generate files for annotations other than lib. I know this is a build_runner problem itself, but is there a better solution for mbox.

**Comment by MisterJimson** [comment]
If you have multiple packages I would suggest setting up build runner for each of them. Each package should have its own pubspec.yaml.

**Comment by awagege** [comment]
I have read some relevant cases these days, and I am aware of this. I am currently developing a build_Runner related vsCode plug-in, which should be able to solve this tedious multiple package process.
