### ISSUE TITLE
A Discussion forum

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#59]
What would you recommend and why:

- [Discord](https://discordapp.com/)
- [Spectrum](https://spectrum.chat/)
- [Slack](https://slack.com/)
- [Gitter](https://gitter.im/)
- Something else

Inputs please: @katis, @rrousselGit and others!

**Comment by katis** [comment]
I think free Slack has a limited history/search which I consider a dealbreaker

**Comment by katis** [comment]
Gitter seems to have infinite searchable history, and has good integration with Github, so it's fine by me.

**Comment by rrousselGit** [comment]
We can start small, with a mobx channel on Flutter Study Group? https://flutter.io/community

**Comment by pavanpodila** [comment]
Does the flutter study group have infinite search? Any limitations?

**Comment by katis** [comment]
That's true, having a less fragmented community is a very good thing too.

**Comment by pavanpodila** [comment]
Not sure how much of history is saved but if it goes back far enough, I am ok to join and/or create the channel. I think few years of history is good enough for now, given the pace of things. What do you think?

**Comment by katis** [comment]
Yeah, ok by me

**Comment by pavanpodila** [comment]
Tried to sign-in to the [Flutter Study Group](https://flutterstudygroup.slack.com/), but requires an invitation?

**Comment by slightfoot** [comment]
Contact community@flutter.zone for an invitation.

**Comment by pavanpodila** [comment]
@slightfoot sent the request for invite

**Comment by Rahiche** [comment]
+1 for Flutter Study Group
When can we expect the channel?

**Comment by pavanpodila** [comment]
I've asked @slightfoot to create it as I don't have permissions

**Comment by pavanpodila** [comment]
I have created the Gitter channel so we have yet another source of chat, exclusively for mobx.dart community. I've added some of you already 👍 

 [![Gitter](https://badges.gitter.im/mobxjs/mobx.dart.svg)](https://gitter.im/mobxjs/mobx.dart?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

**Comment by pavanpodila** [comment]
Looks like we are settling on Gitter for now
