### ISSUE TITLE
Problem with action async?

### ISSUE THREAD

**Issue by mobile-esig** [mobxjs/mobx.dart#595]
I would like to know if there are any problems with @action async in mobx with flutter and dart or if there are any issues that should be taken into account when using this type of approach. Thankful!

**Comment by pr-1** [comment]
As far as I have used it. There is no problem in async approach.  Just a point that async is analogous to .then() 
approach. So any changes to store after a await should be 
put in a separate action or by using runInAction to reflect in the ui. Otherwise it would render in next cycle.

**Comment by leonardocustodio** [comment]
Also I've used the library a lot and I had no problems with async. But you do need to return it as a Future, even if it is a Future<void>. You can't just use void at least on earlier version you couldn't not sure about right now. But it is a good practice anyway.

**Comment by MaikuB** [comment]
You shouldn't have problems with it as it's still a method to be called. Like how you would deal with standard async methods that return a `Future`, you may need to await them (I recommend turning on [this rule](https://dart-lang.github.io/linter/lints/unawaited_futures.html)) or use a widget if need to render the UI differently based on the status like in the [Hacker News example](https://mobx.netlify.app/examples/hacker-news)
