### ISSUE TITLE
Observables are not updated correctly in asynchronous actions when awaited futures complete immediately

### ISSUE THREAD

**Issue by hacker1024** [mobxjs/mobx.dart#597]
I have a storage abstraction in use, and it looks something like this:
```dart
abstract class Storage {
  Future<void> open();
  Future<void> close();
  Future<String> read(String key);
  Future<void> write(String key, String value);
}
```

Depending on the platform, I then use one of two implementations:
```dart
class StorageImpl implements Storage {
  Future<void> open() async {}
  Future<void> close() async {}
  Future<String> read(String key) => StorageApi.readFromDisk(key);
  Future<void> write(String key, String value) => StorageApi.writeToDisk(key, value);
}
```

```dart
class FallbackStorageImpl implements Storage {
  Map<String, String> _data;

  Future<void> open() async => _data = await FallbackStorageApi.readData();
  Future<void> close() async => await FallbackStorageApi.writeData(_data);
  Future<String> read(String key) async => _data[key];
  Future<void> write(String key, String value) => _data[key] = value;
}
```

As you can see, one performs an I/O operation upon reading and writing, and the other performs an I/O operation upon initialisation, and then synchronously reads and writes data from and to memory.

My MobX store looks like this:
```dart
abstract class _MyStore with Store {
  final Storage _storage;

  _MyStore(this.storage);

  @observable
  bool reading = false;

  String username;
  String password;

  @action
  Future<void> read() async {
    reading = true;
    final creds = await Future.wait<String>([
      _storage.read('username'),
      _storage.read('password'),
    ]);
    username = creds[0];
    password = creds[1];
    reading = false;
  }
}
```

When `read()` is called, you would expect observers to be first notified of `reading` changing to true, and then notified of it changing to false. This only happens, however, when the first storage implementation is used. When the second implementation is used, observers will not be notified of `reading` changing to true.

If I add something like `await Future<void>.delayed(const Duration(seconds: 2));` in the `read()` function, however, both implementations result in the expected behaviour.

**Comment by pr-1** [comment]
try making username and password an observable 😅

**Comment by leonardocustodio** [comment]
@hacker1024 I think for your use-case you should be using reaction as it would make more sense for an Observable called "reading" act as a reaction.

I tested over here your implementation using reaction and it worked fine (reading reacted as true and after as false even when the updates immediately)

Here a sample code:

On didChangeDependencies:
```
    disposerTest = reaction((_) => myStore.reading, (reading) {
      print('## Reaction Reading: $reading');
    });
```

Although I can confirm that only the false is notified when the async happens immediately. I think this has to do with that would not make sense to rebuild the widget tree twice for something that would not even show up. Not sure about that though, I think @pavanpodila can clarify it to you.

**Comment by hacker1024** [comment]
I see.
I'll switch to reactions in the meantime - thanks for the suggestion.

**Comment by MaikuB** [comment]
> When read() is called, you would expect observers to be first notified of reading changing to true, and then notified of it changing to false.

MobX actions only dispatches change notifications when the method completes (see https://mobx.netlify.app/api/action).

In your scenario, you could use an [ObservableFuture](https://mobx.netlify.app/api/observable#observablefuturefuturet-future-reactivecontext-context) and use either a reaction or Observer widget to be notified of changes

**Comment by hacker1024** [comment]
> MobX actions only dispatches change notifications when the method completes (see https://mobx.netlify.app/api/action).

I tried splitting the code into two functions annotated with `@action`, and then called them sequentially from a regular function. It didn't help.

I also tried using an `ObservableFuture` with `@computed` properties, but I observed the same behaviour - the Observer was not getting notified about the loading starting in any case.

**Comment by MaikuB** [comment]
I'm not sure what's going on with the case where the method was split. Might need a repro sample for that.

For using `ObservableFuture`, take a look at the hacker news sample documented [here](https://mobx.netlify.app/examples/hacker-news). You should have a `ObservableFuture` property with the `@observable` annotation. This gets set to a new instance of an `ObservableFuture` when the async method passed to the `ObservableFuture` is meant to start running. I had my own version of the hacker news that I documented about [here](https://dexterx.dev/managing-ui-state-in-flutter-with-mobx-and-provider/) (look for `StoriesStore`) as well

**Comment by avioli** [comment]
Your `FallbackStorageImpl.read` must return a Future, not a String:

```dart
class FallbackStorageImpl implements Storage {
  Map<String, String> _data;

  Future<void> open() async => _data = await FallbackStorageApi.readData();
  Future<void> close() async => await FallbackStorageApi.writeData(_data);
  Future<String> read(String key) => Future.value(_data[key]);
  Future<void> write(String key, String value) {
    _data[key] = value;
  }
}
```

Alternative is to add the `async` keyword.

<details>
<summary>Dart repro</summary>

```dart
import 'package:mobx/mobx.dart';

void main(List<String> arguments) async {
  print('start');

  {
    print('--- StorageImpl');
    final storage = StorageImpl();
    await storage.write('username', '597');
    await storage.write('password', 'secre7');
    await testStore(MyStore(storage));
  }

  {
    print('--- FallbackStorageImpl');
    final fallbackStorage = FallbackStorageImpl();
    await fallbackStorage.open();
    await testStore(MyStore(fallbackStorage));
  }

  print('end');
}

Future<void> testStore(MyStore s) async {
  final disposer = autorun((_) {
    print('- reading: ${s.reading} '
        '- username: ${s.username} '
        '- password: ${s.password}');
  });
  await s.read();
  print('username/password: ${s.username}/${s.password}');
  disposer();
}

// /////////////////////////////////////////////////////////////////////////////

class StorageImpl implements Storage {
  Future<void> open() async {}
  Future<void> close() async {}
  Future<String> read(String key) => StorageApi.readFromDisk(key);
  Future<void> write(String key, String value) =>
      StorageApi.writeToDisk(key, value);
}

class FallbackStorageImpl implements Storage {
  Map<String, String> _data;

  Future<void> open() async => _data = await FallbackStorageApi.readData();
  Future<void> close() async => await FallbackStorageApi.writeData(_data);
  Future<String> read(String key) => Future.value(_data[key]);
  Future<void> write(String key, String value) {
    _data[key] = value;
  }
}

abstract class Storage {
  Future<void> open();
  Future<void> close();
  Future<String> read(String key);
  Future<void> write(String key, String value);
}

class StorageApi {
  static final Map<String, Object> _store = {};

  static Future<String> readFromDisk(String key) async {
    return _store[key];
  }

  static Future<void> writeToDisk(String key, Object value) async {
    _store[key] = value;
  }
}

class FallbackStorageApi {
  static Map<String, String> _store;

  static Future<Map<String, String>> readData() async {
    _store = {
      'username': '597',
      'password': 'secre7',
    };
    return _store;
  }

  static Future<void> writeData(Map<String, String> data) async {
    _store = data;
  }
}

// /////////////////////////////////////////////////////////////////////////////

class MyStore = _MyStore with _$MyStore;

abstract class _MyStore with Store {
  final Storage _storage;

  _MyStore(Storage storage) : _storage = storage;

  @observable
  bool reading = false;

  String username;
  String password;

  @action
  Future<void> read() async {
    reading = true;
    final creds = await Future.wait<String>([
      _storage.read('username'),
      _storage.read('password'),
    ]);
    username = creds[0];
    password = creds[1];
    reading = false;
  }
}

mixin _$MyStore on _MyStore, Store {
  final _$readingAtom = Atom(name: '_MyStore.reading');

  @override
  bool get reading {
    _$readingAtom.reportRead();
    return super.reading;
  }

  @override
  set reading(bool value) {
    _$readingAtom.reportWrite(value, super.reading, () {
      super.reading = value;
    });
  }

  final _$readAsyncAction = AsyncAction('_MyStore.read');

  @override
  Future<void> read() {
    return _$readAsyncAction.run(() => super.read());
  }

  @override
  String toString() {
    return '''
reading: ${reading}
    ''';
  }
}
```

```sh
$ dart run
start
--- StorageImpl
- reading: false - username: null - password: null
- reading: true - username: null - password: null
- reading: false - username: 597 - password: secre7
username/password: 597/secre7
--- FallbackStorageImpl
- reading: false - username: null - password: null
- reading: true - username: null - password: null
- reading: false - username: 597 - password: secre7
username/password: 597/secre7
end
```
</details>

**Comment by hacker1024** [comment]
> Your FallbackStorageImpl.read must return a Future, not a String

Oops. This isn't related to the issue, though - just a syntax error I made while writing the example code in the browser.

The code you've posted does not demonstrate my issue.
Both of your implementations have futures that complete immediately, so they have the same behaviour - for the issue to be replicated, one must wait on a delayed future or on I/O.

**Comment by avioli** [comment]
@hacker1024 I thought it was a typo.

Maybe I don't get what the problem is.

Even if I change both APIs to have some delay you still get `- reading: true - username: null - password: null`, which means the `reading` change gets reported correctly.

Of course the `FallbackStorageImpl.read` will possibly not be able to trigger a Flutter re-render cycle, since the response comes faster than a microtask. Still - any listener for the `reading` property will be called and never missed.

How do you "monitor" the `reading` property? Using an `Observer` or one of the reaction methods - `autorun/reaction/when/asyncWhen`? `Observer` internally uses similar implementation as `reaction`.

<details><summary>updated APIs</summary>

```dart
class StorageApi {
  static final Map<String, Object> _store = {};

  static Future<String> readFromDisk(String key) async {
    print('readFromDisk...');
    await Future.delayed(Duration(seconds: 3));
    print('... after 3s - done');
    return _store[key];
  }

  static Future<void> writeToDisk(String key, Object value) async {
    _store[key] = value;
  }
}

class FallbackStorageApi {
  static Map<String, String> _store;

  static Future<Map<String, String>> readData() async {
    print('readData...');
    await Future.delayed(Duration(seconds: 3));
    print('... after 3s - done');
    _store = {
      'username': '597',
      'password': 'secre7',
    };
    return _store;
  }

  static Future<void> writeData(Map<String, String> data) async {
    _store = data;
  }
}
```
</details>

```sh
$ dart run
start
--- StorageImpl
- reading: false - username: null - password: null
readFromDisk...
readFromDisk...
- reading: true - username: null - password: null
... after 3s - done
... after 3s - done
- reading: false - username: 597 - password: secre7
username/password: 597/secre7
--- FallbackStorageImpl
readData...
... after 3s - done
- reading: false - username: null - password: null
- reading: true - username: null - password: null
- reading: false - username: 597 - password: secre7
username/password: 597/secre7
end
```

The only difference is that
