### ISSUE TITLE
Are private observables normal?

### ISSUE THREAD

**Issue by subzero911** [mobxjs/mobx.dart#604]
![image](https://user-images.githubusercontent.com/12999702/100438297-02d93280-30b3-11eb-88fe-afe77c21ecec.png)

I want to have a private variable, but a public observable getter.
In this example, I want to rebuild a widget when an `isUserNotFound` value changes. But the getter couldn't be observable, so I mark it as computed. But computed should rely on observable, so I have to mark `_profileResponseErrorCode` as observable. But it looks like a mistake, because it's a private member and it's not intended to be observable.
So, how should I write it properly?

**Comment by pavanpodila** [comment]
Yup private observables are perfectly fine and is the right approach in this case.

**Comment by Fleximex** [comment]
To add on this. When you use `@readonly` instead `@observable` the `_profileResponseErrorCode` will have a public getter and private setter called `profileResponseErrorCode`, after code generation.
