### ISSUE TITLE
How to ignore generated files when navigating to the strore properties (actions)?

### ISSUE THREAD

**Issue by asavchuk** [mobxjs/mobx.dart#605]
When user navigates to the strore properties (actions), for instance in the Android Studio, it opens a generated property (action) in *.g.dart file. It's annoying, because then user should navigate to the _source_  property (action) from there. So we win on one side (using generated code), and loose on the other (when have to navigate one more time). 

Is there a way to go to the _original_ (not generated) property (action), when navigating to them from the code in ide?

**Comment by pavanpodila** [comment]
I think it will require some help from the IDE to skip the generated files and go straight to the original code. When we were designing the code-generation for MobX, we did think of this and were torn on how to generate the code and finally had to give to the generation instead of the Developer Experience. It was a trade-off. However, given that we now have newer features in Dart like extensions, we can revisit to see if there is a better way to generate this code with some extra work on part of the Developer.

/cc @rrousselGit

**Comment by avioli** [comment]
Here's what I do - I click on a Store property, then when the `.g.dart` file opens, I click the `super.` property there and that gets me to the actual one. It is not ideal, but better than looking it up with search.

@pavanpodila 
Without some "hint" from the code, like a decorator within the `.g.dart` file, there won't be any easy way for an IDE (or plugin ) to figure it out on its own.

Like this mocked-up definition:

```dart
  @override
  @SourceDefinition('my_observable_model.dart', '_MyObservableModel.syncError')
  set syncError(Object value) {
    _$syncErrorAtom.reportWrite(value, super.syncError, () {
      super.syncError = value;
    });
  }
```

Then a plugin could potentially read these SourceDefinitions and jump to the source, but I doubt it will be worth investing the time to build and support IDE plugins as well, although it could become a generic solution for any Dart generated output.

**Comment by leonardocustodio** [comment]
@avioli  The ".g.dart" file always have the same name as the main file and the function has the same name as well. I don't know anything about IntelliJ plugins but it is not possible to read the function's name, get the main file without the g and just find the function in there?

**Comment by CoderBuck** [comment]
try this

```dart
import 'package:mobx/mobx.dart';

part 'counter.g.dart';

class CounterImpl = Counter with _$CounterImpl;
abstract class Counter with Store {

  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }

}
```

``Counter counter = CounterImpl();``

in android studio is ok
