### ISSUE TITLE
Mobx actions don't allow to throw an exception

### ISSUE THREAD

**Issue by alexaf2000** [mobxjs/mobx.dart#612]
Hi!

I'm currently trying to implement Firebase Crashlytics and Sentry into a project. They detect every unhandled exception and throw it to Crashlytics/Sentry, where I can see the exception and stacktrace, the issue comes when I throw an exception from a Mobx action.

What happens is like Mobx automatically get any kind of exception and just print it into console instead of rethrow it as I would like to do. 

In my code:

> 
> /// Send forgotten mail with password recovery  
> @action  
>   Future sendForgottenMail(context, email) async {
>     try {
>       sendForgottenMailFuture =
>           ObservableFuture(AuthRepository(context).passwordRecovery(email));
>       bool correctResponse = await sendForgottenMailFuture;
>       if (correctResponse == true) {
>         sendForgottenMailStatus = ForgottenPasswordStatus.sended;
>         //  sendForgottenMailStatus = ForgottenPasswordStatus.unset;
>       } else {
>         sendForgottenMailStatus = ForgottenPasswordStatus.unset;
>         forgottenPasswordError = tr("errors.api_errors.unknown");
>       }
>     } on ApiException catch (e) {
>       sendForgottenMailStatus = ForgottenPasswordStatus.unset;
>       forgottenPasswordError = tr(e.message);
>     } catch (e) {
>       sendForgottenMailStatus = ForgottenPasswordStatus.unset;
>       forgottenPasswordError = tr("errors.api_errors.unknown");
>       rethrow; -> I need to rethrow here to Crashlytics/Sentry get the exception
>     }
>   }
> 

As you can see, if an unexpected exception is throw, I rethrow it, but when a exception is throw inside an action all we get is this debug message:

> /flutter (22550): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out [5000ms]
> E/flutter (22550): 0      DioMixin._request._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>
> package:dio/src/dio.dart:871
> E/flutter (22550): 1      _rootRunUnary (dart:async/zone.dart:1198:47)
> E/flutter (22550): 2      _ZoneDelegate.runUnary (dart:async/zone.dart:765:19)
> E/flutter (22550): 3      AsyncAction._runUnary
> package:mobx/…/async/async_action.dart:58
> E/flutter (22550): 4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> E/flutter (22550): 5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)

And does not re-throw the exception. Is this a correct behaviour?

**Comment by alexaf2000** [comment]
Tried again, with the next code on main.dart

> runZoned(() async {
>             runApp(EasyLocalization(
>                 supportedLocales: [Locale('ca'), Locale('es'), Locale('en')],
>                 path: 'assets/localization', // <-- change patch to your
>                 fallbackLocale: Locale('ca'),
>                 child: MyApp())); // starting point of app
>           }, onError: (error, stackTrace) {
>             print("Error FROM OUT_SIDE FRAMEWORK ");
>             print("--------------------------------");
>             print("Error :  $error");
>             print("StackTrace :  $stackTrace");
>           });

Any kind of exception has to be throw into log, but the ones that are on a Mobx function still doesn't work. Seems to be Mobx catching and just printing the errors, but not rethrowing.

**Comment by pavanpodila** [comment]
One option is to setup a global reaction handler on the `mainContext`: https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/core/context.dart#L495

**Comment by alexaf2000** [comment]
> One option is to setup a global reaction handler on the `mainContext`: https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/core/context.dart#L495

But does this handle actions? They both are different.

**Comment by alexaf2000** [comment]
> One option is to setup a global reaction handler on the `mainContext`: https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/core/context.dart#L495

I tried to add the global reaction handler on the mainContext, but as I said it just works when something goes wrong in the reaction. But the most usual is to do API calls inside an action. 

That is what I do, and sometimes this API Call inside an action would throw an error. Which is not throwing, instead of this is returning on console the next:
(This is just is an example but the first part of the message is always the same).
` [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out [5000ms]`

When inside an action an error is throw, it gets handled automatically. And some libraries as Crashlytics detects the unhandled errors and send you an email with the data. But if MobX automatically handles the errors inside actions this could be a big problem on the future for many developers. Maybe I am doing something wrong. The easiest solution is to put a try/catch on every action and set a manual message function to call crashlytics, but this is ugly and unnecesary I think.

**Comment by pr-1** [comment]
```dart
 } on ApiException catch (e) {
sendForgottenMailStatus = ForgottenPasswordStatus.unset;
forgottenPasswordError = tr(e.message);
} catch (e) {
sendForgottenMailStatus = ForgottenPasswordStatus.unset;
forgottenPasswordError = tr("errors.api_errors.unknown");
rethrow; -> I need to rethrow here to Crashlytics/Sentry get the exception
}
```

When any exception apart from ApiException will occur it will go to the last catch and from there mobx will rethrow it. 
Are you handling it where you are calling this action ?

This error will occur if you are not handling it where you are calling the action method. 
Mobx doesn't handle it automatically. Can you check this and revert.

**Comment by alexaf2000** [comment]
> ```dart
>  } on ApiException catch (e) {
> sendForgottenMailStatus = ForgottenPasswordStatus.unset;
> forgottenPasswordError = tr(e.message);
> } catch (e) {
> sendForgottenMailStatus = ForgottenPasswordStatus.unset;
> forgottenPasswordError = tr("errors.api_errors.unknown");
> rethrow; -> I need to rethrow here to Crashlytics/Sentry get the exception
> }
> ```
> 
> When any exception apart from ApiException will occur it will go to the last catch and from there mobx will rethrow it.
> Are you handling it where you are calling this action ?
> 
> This error will occur if you are not handling it where you are calling the action method.
> Mobx doesn't handle it automatically. Can you check this and revert. @alexaf2000

As you can see, in the "any other catch" I set a unknown error message and then I rethrow the exception. Why I do this? Be cause when a unhandled exception is throw, Firebase Crashlytics get the exception and report its to me with an email. But the issue is that even if I force a exception inside an action, is always handled or doesn't allow to throw an exception. Just getting a log message with the prefix: "[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: ...".

If I put the error on any part of the code, even async functions, it returns a correct exception and Crashlytics notifies me.

An easy way to check it is to do the next.

On the main.dart insert the next:

```
void main() {
    WidgetsFlutterBinding.ensureInitialized(); //imp line need to be added first
    FlutterError.onError = (FlutterErrorDetails details) {
    //this line prints the default flutter gesture caught exception in console
    //FlutterError.dumpErrorToConsole(details);
    print("Error From INSIDE FRAME_WORK");
    print("----------------------");
    print("Error :  ${details.exception}");
    print("StackTrace :  ${details.stack}");
    };
    runApp(MyApp()); // starting point of app
 }
```
And force inside a Mobx Action a new exception with:

`throw new Exception("This is just a test exception");`

And you will see that the exception is thrown but, somehow is handled and don't enter on the FlutterError.onError. Therefore crashlytics will never notify me.

**Comment by alexaf2000** [comment]
Any news?

**Comment by avioli** [comment]
Actions do not catch exceptions. Computed, Derivations, Reactions and some Observables do.

Since you have a point where you `rethrow` - why not simply post your error for analysis from there?

Both Crashlytics and Sentry have support for this:

```dart
FlutterCrashlytics().reportCrash(error, stackTrace, forceCrash: false).catchError((_) {});
Sentry.captureException(error, stackTrace: stackTrace).catchError((_) {});
```

You can still `rethrow` afterwards. Up to you.

There's no magic here - just look at your generated source code or the lib's source and you can work it out.

**Comment by alexaf2000** [comment]
Than you for your reply @avioli , the reason why I do not manually call to sentry/crashlytics with the error is because, there are a lot of functions inside an app, and set on every Mobx action a try catch seems a bit boilerplate. 

About what you said, that the async functions are not being catched by flutter onError, I think that I tested it a time ago and was catching it.

**Comment by CoderBuck** [comment]
1. right
```dart
void main() {
  
  runZoned((){
    WidgetsFlutterBinding.ensureInitialized()
    FlutterError.onError = (FlutterErrorDetails details) {
    /// 捕获异常，上报
    };
    runApp(MyApp());
  }, onError: (Object obj, StackTrace stack){
    /// 捕获异常，上报
  });
}
```

2. wrong
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized()
  FlutterError.onError = (FlutterErrorDetails details) {
    /// 捕获异常，上报
  };
  runZoned((){
    runApp(MyApp());
  }, onError: (Object obj, StackTrace stack){
    /// 捕获异常，上报
  });
}
```

**Comment by vini2001** [comment]
Any updates on this?
Adding a try catch block inside every action to report errors is too boilerplate as @alexaf2000 pointed out. It also doesn't solve the problem when you use unawaited async functions inside the action.

I'm trying to solve a particular bug but I don't have the Crashlytics reports for that as there is no way of globally catching mobX action errors. I think this should be reopened?
