### ISSUE TITLE
are non-Observable collections allowed?

### ISSUE THREAD

**Issue by 2x2xplz** [mobxjs/mobx.dart#618]
Most of my app was built using MobX 0.3.10, as far as collections go there are some `ObservableList`s and `ObservableSet`s and `ObservableMap`s, however, I also have quite a few collections that are **not** observable, on purpose.

After upgrading to the latest versions, the compiler will not allow any plain `List`, `Set` or `Map`, with the error message `List isn't a type`. It suggests importing `dart:core` but doing so doesn't help. This behavior only occurs in files that import MobX. After some trial and error it seems this goes all the way back to 0.4.0. 

Is making non-observable collections illegal the expected behavior? If not, is it possible to tell why I am getting these errors?

**Comment by fzyzcjy** [comment]
Maybe show some code? I have plenty of them in my code and have no problem.

**Comment by 2x2xplz** [comment]
Glad to hear they are working for you -- makes it clear that they *should* be working.

Very simple class:

```
import 'package:mobx/mobx.dart';

part 'vehicle.g.dart';

class Vehicle = _Vehicle with _$Vehicle;

abstract class _Vehicle with Store {
  final String brand;
  final String color;
  final int wheelCount;
  List<int> passengerIDs = List.of([]);
  @observable double speed = 0.0;

  _Vehicle(this.brand, this.color, this.wheelCount);
  _Vehicle._withPassengers(this.brand, this.color, this.wheelCount, this.passengerIDs);
}
```

works totally fine under **mobx 0.3.10**.

Upgrade to **mobx 0.4.0** and now the line `List<int> passengerIDs = List.of([]);` raises 2 errors:
`List isn't a type`
`The method 'of' isn't defined for the type 'Function'.`

This persists after running `flutter packages pub run build_runner build`

If I change it to `ObservableList<int> passengerIDs = ObservableList.of([]);` the errors go away and we're all good again.

**Comment by fzyzcjy** [comment]
What error? error from .g.dart? from the mobx code generator? from flutter compiler?

In addition, `ObservableList<int> passengerIDs = ObservableList.of([]);` is the correct way.

Or, `@observable ObservableList<int> passengerIDs = ObservableList.of([]);`. Or, `final ObservableList<int> passengerIDs = ObservableList.of([]);`. (would be better)

**Comment by 2x2xplz** [comment]
> What error? 

`List isn't a type`
`The method 'of' isn't defined for the type 'Function'.`

> In addition, `ObservableList<int> passengerIDs = ObservableList.of([]);` is the correct way.

what do you mean the "correct" way?  I do NOT want this particular list to be Observable, there is no need for observability or reactive-ness. Your first comment claimed you had plenty of non-observable lists.

(I agree the list should be final, should have written it that way... but it's irrelevant to this issue)

**Comment by fzyzcjy** [comment]
Then what about `List()` or `[]` instead of `List.of([])`?

> What error?

I mean, *where* do you see the error? output from what command?

> Your first comment claimed you had plenty of non-observable lists.

Oh I mean `List<T> a = ObservableList()`. But yours should work IMHO

**Comment by 2x2xplz** [comment]
I think this was a compiler or IDE issue. I'm using IntelliJ 2020.3.1. I re-installed the Dart plugin, Flutter plugin, upgraded flutter, cleared the cache, upgraded mobx, flutter_mobx and mobx_codegen to the latest versions. No more issues using regular (non-observable) `List`s, `Set`s and `Map`s. Closing.

**Comment by fzyzcjy** [comment]
Happy to hear that!
