### ISSUE TITLE
Can we observe store inside another store?

### ISSUE THREAD

**Issue by chounry** [mobxjs/mobx.dart#620]
### Code example
```dart
/// Child store
class PlayerDataStore = PlayerDataStoreBase with _$PlayerDataStore;

abstract class PlayerDataStoreBase with Store {
      @observable
      String username;
}



/// Parent store
class DuelInGameStore = DuelInGameStoreBase with _$DuelInGameStore;

abstract class DuelInGameStoreBase with Store {
       PlayerDataStore playerMeStore;
}
```

```dart
/// Screen
final duelInGameStore = DuelInGameStore();

....
Observer(
      builder: (context) {
            return PlayerStateWidget(
              username: duelInGameStore.playerMeStore.username,
            );
       },
)
....
```

Right now, the `Observer` seems like it doesn't rebuild when the username change.

However, the observer rebuild when I do a hack.
```dart
/// Screen
final duelInGameStore = DuelInGameStore();

....
Observer(
      builder: (context) {
            var a = duelInGameStore.playerMeStore; // <------ add this line
            return PlayerStateWidget(
              username: duelInGameStore.playerMeStore.username,
            );
       },
)
....
```

Am I doing it wrong or it's not possible to observe sub stores?

**Comment by Rudiksz** [comment]
The `var a = duelInGameStore.playerMeStore; ` line is not needed in your Observer widget. There's a few potential things going on. Looks to me like you initialise your duel store with the child store set to null, then you actually assign the store somewhere else. Since the observer is subscribing to a reaction that is effectively on a null object, it would never fire.

The solution is indeed to make the store itself observable so Observer widgets rebuild whenever you assign a new instance:

```Dart
/// Parent store
class DuelInGameStore = DuelInGameStoreBase with _$DuelInGameStore;

abstract class DuelInGameStoreBase with Store {
      @observable
      PlayerDataStore playerMeStore;
}
```

**Comment by chounry** [comment]
@Rudiksz First, thanks for the reply. 
I have update the child `PlayerDataStore` to have `action`
```dart
class PlayerDataStore extends PlayerDataStoreBase with _$PlayerDataStore {
  PlayerDataStore(String username) : super(username);
}
abstract class PlayerDataStoreBase with Store{
  @observable
  String username;

 @action
  void setUsername(String username) {
    this.username = username;
  }
}
```

Then I updated the parent store to initialize the child `PlayerDataStore`.
```dart 
  PlayerDataStore playerMeStore = PlayerDataStore("");
```

Then when the API called is completed in the **parent store** I called this 
```dart
 playerMeStore.setUsername('newUsername');
```

This still doesn't make the `observer` rebuild.

Is there an example on how to manage sub stores?

**Comment by Rudiksz** [comment]
Your example should work, I use sub stores like that all the time without any particular setup.
The only thing that comes to mind is that you should set the variable holding your sub store as observable (as I showed in my previous post). But even that is only needed if you want to be able to assign new instance to it.

**Comment by chounry** [comment]
@Rudiksz yes, I got that work. Now I have another problem with `ObservableList`. It doesn't notify the `observer` to rebuild when the list change. The observable list is declare in the child store `PlayerDataStore` and the methods are called by the parent store `DuelInGameStore`
This is the code in the child store :

```dart
@observable
var resultAnswers = ObservableList<int>();

@action
void setInitialResult(List<int> results) {
    resultAnswers.addAll(results);
}

@action
void setResultList(List<int> results) {
    // resultAnswers.add(1);     <---- even this doesn't work
    resultAnswers.setAll(0, results);
}

```

**Comment by Rudiksz** [comment]
ObservableList.setAll uses List.setAll, which does not modify the length of the list as per the docs and I have a vague suspicion that observablelist.setAll only tracks changes to the list if its length changes. It sounds like a bug, or a simple oversight - I don't think a lot of people use that method in the vanilla List class, let alone with mobx.

Either way, if you don't need to keep the old values (ie. just want to replace your observablelist) you can use:
```
@action
void setResultList(List<int> results) {     <---- even this doesn't work
    resultAnswers = results.asObservable();
}
```

**Comment by deadsoul44** [comment]
As far as I understand, since individual items in the list are primitive types like int, mobx cannot react since those individual items are not stores and are not reactive. You can try replaceRange.

**Comment by avioli** [comment]
I would suggest you do:

```dart
@observable
var resultAnswers = ObservableList<int>();

@action
void setInitialResult(List<int> results) {
    resultAnswers.addAll(results);
}

@action
void setResultList(List<int> results) {
    resultAnswers = ObservableList.of(results);
}
```
