### ISSUE TITLE
Need to update versions

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mobxjs/mobx.dart#621]
I am getting this error when copying depenedencies from your documentation
```
Because no versions of mobx_codegen match >1.1.2 <2.0.0 and mobx_codegen 1.1.2 depends on mobx ^1.1.0, mobx_codegen ^1.1.2 requires mobx ^1.1.0.

So, because senio_assist depends on both mobx ^2.0.0-nullsafety.2 and mobx_codegen ^1.1.2, version solving failed.
```

**Comment by leonardocustodio** [comment]
It is working fine over here.

Using
mobx ^1.2.1+4
flutter_mobx ^1.1.0+2
mobx_codegen ^1.1.2

Also the documentation updates the versions automatically to the latest version

**Comment by vytautas-pranskunas-** [comment]
Yes but I was trying to install mobx 2.0.0

**Comment by leonardocustodio** [comment]
I see, since 2.0.0 is a pre-release it was not supposed to be in the default doc. I'm going to fix the script right now.
Thank you for your comment (;

**Comment by leonardocustodio** [comment]
There you go #623

**Comment by pavanpodila** [comment]
Thanks @leonardocustodio 🥇
