### ISSUE TITLE
Documentation and code eample mismatch

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mobxjs/mobx.dart#627]
Hi, I am building form and going throu documentation and code. As far as I understood from docs if i want to mutate observable i have to call action e.g. takne from docs: https://mobx.netlify.app/examples/form/

```
@observable
String username;

@action
  void setUsername(String value) {
    name = value;
  }
```

however if i look at example code given in same page at the botoom i see that

```
// store
@observable
String name = '';

//widget
Observer(
                builder: (_) => TextField(
                  onChanged: (value) => store.name = value,
                  decoration: InputDecoration(
                      labelText: 'Username',
                      hintText: 'Pick a username',
                      errorText: store.error.username),
                ),
              ),

```

We see that **onChange observable is mutated not through action**

I have implemented like in the code and it works.
So question - ca i mutate observables not through actions? 
Or maybe while inside Observable => it is enough to do direct assignment but once outside we have to use actions?

Also it would be good to sync docs and code :)

**Comment by pavanpodila** [comment]
For single property updates MobX auto-wraps the setter in an action. That said I'll update the docs to include this
