### ISSUE TITLE
Missing documentation how to build form with TextFormField

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mobxjs/mobx.dart#628]
I am trying to build form with mobx having my textFormField synced with but appereantly there many troubles
Can you put here an example how to have TextFormField synced both ways with model?
I have found only this talk about this and so far it looks clampsy: https://gitter.im/mobxjs/mobx.dart?at=5cdbe2ecda34620ff94543aa

And in your documentation there is only simple form with TextField (feeling like to "sell" MobX - no offense)

**Comment by Rudiksz** [comment]
This is what the TextFormField's doc says:

> When a [controller] is specified, [initialValue] must be null (the default). If [controller] is null, then a [TextEditingController] will be constructed automatically and its text will be initialized to [initialValue] or the empty string.

The first obvious choice of wrapping a TextFormField in an observer and rebuild it with a new initialValue does not work because TextFormField will do all kinds of weird stuff if the initialValue is different between rebuilds.

The alternative is to manage your own TextEditingControllers separate from the TextFormFields, and set up reactions in your stores that update the value of these controllers when the content of the textfields needs to be updated from the store.

So, I have plain TextFields in my forms and I use mobx stores as state/controller for them. These controllers manage the textediting controllers, focusnode and the actual state of the form. Non-text fields use the observer widget to rebuild when the state changes, but for the text fields I set the texteditingcontroller value manually as such.

```
  setTextControllerValue(FormFieldType field, value) {
    textControllers[field].value = TextEditingValue(
      text: value ?? '',
      selection: TextSelection.collapsed(offset: value?.length ?? 0),
    );
  }
```

It's clumsy because Flutter's TextFormField and the TextEditingController is clumsy and bugged.  Months ago I completely abandoned the Form widget and its FormFields widget because they were lacking basic stuff or just acted weird. The above workaround to make TextFields work and the time I spent to write my own "forms" that manage my their focusnodes, texteditingcontrollers and behavior is minuscule compared to how much debugging I had to do on the Flutter widgets.

**Comment by vytautas-pranskunas-** [comment]
So basically you are using TextField over TextFormField?

Can you share component you use?

**Comment by Rudiksz** [comment]
Here's a stripped down version with Widget and controller. I pretty much use this pattern in all my forms and it's working fine.
The widgets are purely presentation code with the Controllers (being Stores) handle **all** the view logic.
I use Flutter's State object purely for it's initState/didUpdateWidget/dispose lifecycle.

Some people in the Flutter will call this cumbersome and repetitive . I think it's fine. With some extra work it could be made into a more generic widget, but I didn't bother with it. It's 2 one liner functions and then the code to set up the fields, I think it's fine. I'm not going to abstract away 2 one liner functions.

```Dart
import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:mobx/mobx.dart';

class SomeForm extends StatefulWidget {
  final String id;

  SomeForm(
    this.id, {
    Key key,
  }) : super(key: key);

  @override
  SomeFormState createState() => SomeFormState();
}

class SomeFormState extends State<SomeForm> {
  SomeFormController controller;

  @override
  void initState() {
    super.initState();
    controller = SomeFormController();
    controller.loadItem(widget.id);
  }

  @override
  void didUpdateWidget(SomeForm oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (oldWidget.id != widget.id) {
      // tell the controller to load new item
      controller.loadItem(widget.id);
    }
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextField(
          controller: controller.textControllers[FormFieldType.name],
          focusNode: controller.focusNodes[FormFieldType.name],
        ),
        TextField(
          minLines: 5,
          maxLines: 10,
          controller: controller.textControllers[FormFieldType.notes],
          focusNode: controller.focusNodes[FormFieldType.notes],
        ),
        Observer(
          builder: (_) {
            // Change the style of the Wrap to appear "focused"
            final isFocused = controller.focusedField == FormFieldType.type;
            return Wrap(
                children: ItemTypes.values
                    .map<Widget>(
                      (e) => ActionChip(
                        label: Text(e.toString()),
                        onPressed: () => controller.setType(e),
                      ),
                    )
                    .toList());
          },
        ),
        //... more fields here
        Observer(builder: (_) {
          return ActionButtons(
            onReset: controller.reset,
            onSave: controller.save,
          );
        }),
      ],
    );
  }
}

enum FormFieldType { name, notes, type }
enum ItemTypes { A, B, C }

class SomeFormController = _SomeFormControllerBase with _$SomeFormController;

abstract class _SomeFormControllerBase with Store {
  _SomeFormControllerBase() {
    // When textfields come into focus this will cause any non-text field to unfocus
    focusNodes.forEach((field, focusNode) => focusNode.addListener(
          () => focusNode.hasFocus ? focusField(field) : null,
        ));
  }

  @observable
  Map<FormFieldType, String> fieldErrors = ObservableMap();

  // Which form fields are text fields. They are handled different from other types
  Map<FormFieldType, String> textFields = {
    FormFieldType.name: '',
    FormFieldType.notes: '',
  };

  /// Current state of the text fields
  Map<FormFieldType, TextEditingController> textControllers = {
    FormFieldType.name: TextEditingController(text: ''),
    FormFieldType.notes: TextEditingController(text: ''),
  };

  // FocusNodes used by the text fields
  Map<FormFieldType, FocusNode> focusNodes = {
    FormFieldType.name: FocusNode(),
    FormFieldType.notes: FocusNode(),
  };

  @observable
  FormFieldType focusedField;

  @action
  void focusField(FormFieldType field) {
    focusNodes.forEach((key, value) {
      if (field != key) value.unfocus();
    });

    focusedField = field;
  }

  void setTextControllerValue(FormFieldType field, value) {
    textControllers[field].value = TextEditingValue(
      text: value ?? '',
      selection: TextSelection.collapsed(offset: value?.length ?? 0),
    );
  }

  void loadItem(String id) {
    // This will update any non-text field listening to it
    itemBeingEdited = getItemFromSomeWhere(id);

    // update text fields separately
    setTextControllerValue(FormFieldType.name, itemBeingEdited.name);
    setTextControllerValue(FormFieldType.notes, itemBeingEdited.notes);
  }

  // Form logic here, set non text fields, validate, reset, save, update, etc...

  void setType(ItemTypes type) {
    focusField(FormFieldType.type);
    itemBeingEdited.type = type;
  }

  void dispose() {
    focusNodes.forEach((_, n) => n.dispose());
    textControllers.forEach((_, c) => c.dispose());
  }
}

```

**Comment by lucasdidur** [comment]
@Rudiksz, I liked your example, but how do I use form validation, like mobx documentation, or retrieve the field values? Using their controllers?
