### ISSUE TITLE
The name "Action" conflicts with the "Action" class in Flutter

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#632]
As @acoutts has pointed out at https://github.com/mobxjs/mobx.dart/issues/598, the `Action` in `'package:mobx/mobx.dart'` conflicts with the Action in Flutter. Thus, people may have to use `import 'package:mobx/mobx.dart' as mbx;` and write anything as `mbx.Something`, which is quite cumbersome and wasting time.

**Comment by pavanpodila** [comment]
don't see it as an issue as its not MobX related and has to do with naming collisions due to SDKs

**Comment by Rudiksz** [comment]
You can also just do 
```import 'package:flutter/material.dart' hide Action;```

Fluter's Action is meant for sending messages between widgets. If you need to use it in the same file with your mobx stores, you're probably mixing UI logic with business logic.
