### ISSUE TITLE
Is it possible to have a computed property based on DateTime.now in Mobx?

### ISSUE THREAD

**Issue by lbuse** [mobxjs/mobx.dart#633]
Consider that 'expires' receives a date representing 2 days from now, so 'expired' is true and should change to false when 2 days passes.

`
@observable
DateTime expires;

@computed
bool get expired =>
      expires == null ||
      expires.difference(DateTime.now()).inSeconds <= 0;
`

When running the app, this property does not change from false to true, but in my unit test, it does, and that's why I don't know if this is possible or not.

Unit test for reference:
`
test('when expires pass its due date, it should trigger expired',
    () async {
  state.changeExpires(
    DateTime.now().add(const Duration(seconds: 3)),
  );

  expect(
    state.hasTokenExpired,
    isFalse,
    reason:
        'because expires ${state.expires.toIso8601String()} should be in the interval expected to not be expired',
  );

  await Future.delayed(const Duration(seconds: 3));

  expect(
    state.hasTokenExpired,
    isTrue,
    reason:
        'because expired ${state.expires.toIso8601String()} has not expired',
  );
});
`

**Comment by Ascenio** [comment]
As DateTime represents a single point in time you gotta use something which is reactive to time changes. A stream will do.
```dart
class TimeStore = _TimeStoreBase with _$TimeStore;

abstract class _TimeStoreBase with Store {
  @observable
  ObservableStream<DateTime> _time = Stream.periodic(Duration(seconds: 1))
      .map((_) => DateTime.now())
      .asObservable();

  @computed
  DateTime get now => _time.value;
}
```

**Comment by Ascenio** [comment]
So you would change your code to
```dart
@computed
bool get expired => expires == null || expires.difference(now).inSeconds <= 0;
```

**Comment by lbuse** [comment]
That's it! Thank you!
