### ISSUE TITLE
Cannot find easy way to revert changes

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mobxjs/mobx.dart#635]
Hi, 

I am using mobx for forms in my app. Thins is that i am running reactions on store properties and everything works great however - those changes heppening live! If user edits the form and exits without saving - changes stay.

If there any "know how" how to solve that without many boilerplate like:
1) store serialized state on enetering
2) adding reactions to each field and mark them as 'changed'
3) upon exit, if user did not save changes, revert state from json

#1 and #3 is ok but i do not want to add to all observables reactions only to mark that form was changed.... smells like a lot of boilerplate....

Maybe there is some generic / recommendet way of doing this.

Issue for referrence: https://github.com/mobxjs/mobx.dart/issues/218#issuecomment-509991708

```any change``` mentioned in that issu would be saver!

Is there something like that implemented?

**Comment by pavanpodila** [comment]
Typically you would create a clone of your model, manipulate the clone and commit changes to the original on submit
