### ISSUE TITLE
Release a version of mobx_codegen compatible with analyzer ^1.1.0

### ISSUE THREAD

**Issue by MisterJimson** [mobxjs/mobx.dart#642]
Other codegen packages are being updated to work with analyzer ^1.1.0 and currently can’t be used in tandem with mobx_codegen.

Related to #598

**Comment by raphaelbarbosaqwerty** [comment]
For this moment use in your project the `analyzer: ^0.41.1`, here it's worked in this version.

**Comment by pavanpodila** [comment]
done as part of #603
