### ISSUE TITLE
mobx_codegen with custom mixin

### ISSUE THREAD

**Issue by fxioi** [mobxjs/mobx.dart#645]
https://mobx.netlify.app/examples/form
When writing store-related code, how can I write code with a similar structure? I tried to write it as follows, but the generated file will be missing FormFields related fields.
```dart
mixin FormFields {
  @observable
  String name = '';

  @observable
  String email = '';

  @observable
  String password = '';
}

abstract class _FormStore with FormFields, Store {
  @action
  void setUsername(String value) {
    name = value;
  }
}

abstract class _FormErrorState with FormFields, Store {
  // ...
}
```

**Comment by Ascenio** [comment]
I don't think the codegen can see mixins, but I might be wrong. But there's a easy fix, make your FormFields a store, and have it as a field on _FormStore.

**Comment by fxioi** [comment]
@Ascenio thx.
