### ISSUE TITLE
ObservableList doesn't trigger update when setting an element directly with the index

### ISSUE THREAD

**Issue by Dealerpriest** [mobxjs/mobx.dart#651]
For me the following doesn't trigger an update:
```dart
@observable
ObservableList<AClass> things = new ObservableList<AClass>();

@action
replaceAThing(int idx, AClass updatedThing){
  // This doesn't trigger an update
  things[idx] = updatedThing;
}
```

Any ideas?

**Comment by deadsoul44** [comment]
Since the element itself is not a store, it does not react. You can use other list methods such as replaceRange.

**Comment by pavanpodila** [comment]
It will update and fire notification of the value is different than previous.

**Comment by Dealerpriest** [comment]
> It will update and fire notification if the value is different than previous.

Aah. It might be that I receive an updated value from the backend that is considered to be the same by dart/mobx. I will investigate today and write my findings here👍

**Comment by Dealerpriest** [comment]
I have now verified that the "updated" object has the same hashCode, and my understanding is that this is what makes two objects equal in dart, and hence the reason why there is no notification triggered. That makes sense. 
I will close this issue then, as the behaviour is related to my object and not mobx.

I have a follow up question though. Is there a recommended way to manually trigger a notification, when I, as a programmer know that the object is indeed updated?

**Comment by thphuc** [comment]
Hi @Dealerpriest did you find the answer for your question about manually trigger?
