### ISSUE TITLE
Cannot generate files on Windows

### ISSUE THREAD

**Issue by kil0ba** [mobxjs/mobx.dart#655]
Hi! 

When i try to generate files on Windows is fails then tries to move them to the correct folder:
```

FileSystemException: Cannot create file, path = 'c:\work\mobileapp\.dart_tool/build/generated/dol/lib/app/ui/screens/main_tabs_screen/tabs/services_tab/abonent_services/service_categories_screen/services_screen/subscription_details_screen/subscription_details_screen_store.store_generator.g.part' (OS 
Error: The system cannot find the path specified. 
```
In the error you can see how the code generator switches to slashes for unix (/ instead of \\)

I tried flutter clean to reinstall all deps, but it doesn't help

Has anyone met this problem?

**Comment by pavanpodila** [comment]
This looks more like a build_runner issue than a code generation. Probably better to file on the builds runner project
