### ISSUE TITLE
Error when using @action on a setter

### ISSUE THREAD

**Issue by jjosenaldo** [mobxjs/mobx.dart#656]
The code within a store `{Store}`
```dart
@observable
int _count = 0;

@action
set count(int newCount) => _count = newCount;
```
gives rise to the following error when running the code generator:
```
Could not make class "{Store}" observable. Changes needed:
  1. Remove @action annotation for the member "count=". They only apply to methods.

```

but this code
```dart
@observable
int _count = 0;

@action
void setCount(int newCount) => _count = newCount;
```

works fine. Shouldn't the first code work as well with `@action`? It does the same thing as the second, but it is slightly more sugary.

**Comment by pavanpodila** [comment]
Property setters are not methods, hence the error

**Comment by jjosenaldo** [comment]
Then the issue is more like a feature request than a bug report. I think it would be nice if the first code generated valid code.

**Comment by pavanpodila** [comment]
For single property setters there is no need for action wrappers around observables. Mobx does it automatically

**Comment by jjosenaldo** [comment]
Sure, the example was minimal. The setter could have more code. This is the actual code I wrote in my app (`_height` and `interpretationVisible` are observables):

```dart
@action
void setHeight(double newHeight) {
  _height = newHeight;
  interpretationVisible = false;
}
```
It would be nice if we could write

```dart
@action
set height(double newHeight) {
  _height = newHeight;
  interpretationVisible = false;
}
```
so that we could use the store as `store.height = 42.0`.

**Comment by Ascenio** [comment]
Hey @jjosenaldo :wave: I think what Pavan meant was that you don't need `@action` annotation on setters because they work exactly as you expect without it. Changes are made, computeds are updated and reactions are triggered accordingly.
