### ISSUE TITLE
MobX + Google Maps : Observer is not triggered

### ISSUE THREAD

**Issue by mfarizon** [mobxjs/mobx.dart#657]
Hello,
I'm using MobX as state management for my app and I really appreciate it. I just found a case that I don't really understand. I'm am trying to render markers on a Google Maps. 
My markers are an ObservableSet in my Store (marked observable), and I always update them via an action.
```
@observable
ObservableSet<Marker> markers = ObservableSet();

@action
void addMarker(Marker marker) {
    markers.add(marker);
}
```
The GoogleMaps widget is directly wrapped with an Observer widget, and the marker parameter refers directly to my markers in my store. But when the markers are updated, the observer doesn't rebuild :(

However if in the didChangeDependencies I initialize an autorun like following, it gets triggered whenever a Marker is added to the ObservableSet.
```
autorun((_) {
    print("Autorun has been triggered ${store.markers}");
    setState(() {});
});
```
So calling setState in the autorun does what I need, but it feels like an ugly workaround. I don't understand why the Observer doesn't rebuild from itself when the markers are updated. Am I doing something wrong, or is there an issue here ?

(I can write a sample app to reproduce if needed)

```
google_maps_flutter: ^1.2.0
mobx: ^1.2.1+4
flutter_mobx: ^1.1.0+2
```

**Comment by pr-1** [comment]
Can you share widget's code ? I am using this same way and it is working for me . without the autorun

**Comment by gianlucampos** [comment]
I got a smilar problem, here is the snippet:

MapController Store:
```dart
  @observable
  ObservableSet<Marker> markers = ObservableSet<Marker>();

  @action
  void addMarker(CustomPlaceholder point) {
    final marker = Marker(
      markerId: MarkerId(point.name),
      position: LatLng(point.latitude, point.longitude),
    );
    markers.add(marker);
  }

``` 

Widget:
```dart
  final controller = MapController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: appKey,
      body: Observer(builder: (_) {
        return GoogleMap(
          initialCameraPosition: CameraPosition(
            target: controller.coordenates,
            zoom: 18,
          ),
          zoomControlsEnabled: true,
          myLocationEnabled: true,
          mapType: MapType.terrain,
          markers: controller.markers,
          onMapCreated: controller.onMapCreated,
          onTap: onTap,
        );
      }),
    );
  }

  void onTap(LatLng coordenates) {
    final placeholder = CustomPlaceholder(
      name: 'Posto GT - Rede Rodoil ${Random().nextInt(100)}',
      adress: 'R. João Negrão, 1072 - Rebouças - Centro, Curitiba - PR',
      image:
          'https://lh5.googleusercontent.com/p/AF1QipP_xnSi5-sp9slSuMpSx-JlmvwvHGL1VJ_JcOGX=w408-h306-k-no',
      latitude: coordenates.latitude,
      longitude: coordenates.longitude,
    );
    controller.addMarker(placeholder);
  }
```

**Comment by buraktahap** [comment]
Any update for this? I am having the same problem.
