### ISSUE TITLE
Updating to latest flutter_mobx libraries has issues with computed values

### ISSUE THREAD

**Issue by billysmt** [mobxjs/mobx.dart#664]
I've got an app that we just started bringing pubspec up to date with and when updating libraries to latest and running build_runner we noticed an issue with computed values getting flagged with null-safety warnings.  We've not upgraded app to be null-safe yet and are in the process of doing so.  So far everything has worked out fine except for in a couple places where we use computed as follow.
```
  @computed
  String get personName => _login?.personName;

  @computed
  String get username => _login?.username;

  @computed
  String get email => profile?.email;

  @computed
  String get phoneNumber => profile?.phoneNumber;

  @computed
  String get profilePicture => _login?.profilePicture;

  @computed
  int get businessID => _login?.businessID;

  @computed
  String get password => profile?.password;
```
  
  When Code generation runs on these they each show up as follows. and show the following error on the leading ? of
   `Computed<String>?`
  
`This requires the 'non-nullable' language feature to be enabled.  Try updating your pubspec.yaml to set the minimum SDK constraint to 2.12.0 or higher, and running 'pub get'.`
  
  ```
Computed<String>? _$personNameComputed;

  @override
  String get personName =>
      (_$personNameComputed ??= Computed<String>(() => super.personName,
              name: '_ProfileViewControllerBase.personName'))
          .value;
  Computed<String>? _$usernameComputed;

  @override
  String get username =>
      (_$usernameComputed ??= Computed<String>(() => super.username,
              name: '_ProfileViewControllerBase.username'))
          .value;
  Computed<String>? _$emailComputed;

  @override
  String get email => (_$emailComputed ??= Computed<String>(() => super.email,
          name: '_ProfileViewControllerBase.email'))
      .value;
  Computed<String>? _$phoneNumberComputed;

  @override
  String get phoneNumber =>
      (_$phoneNumberComputed ??= Computed<String>(() => super.phoneNumber,
              name: '_ProfileViewControllerBase.phoneNumber'))
          .value;
  Computed<String>? _$profilePictureComputed;

  @override
  String get profilePicture =>
      (_$profilePictureComputed ??= Computed<String>(() => super.profilePicture,
              name: '_ProfileViewControllerBase.profilePicture'))
          .value;
  Computed<int>? _$businessIDComputed;

  @override
  int get businessID =>
      (_$businessIDComputed ??= Computed<int>(() => super.businessID,
              name: '_ProfileViewControllerBase.businessID'))
          .value;
  Computed<String>? _$passwordComputed;

  @override
  String get password =>
      (_$passwordComputed ??= Computed<String>(() => super.password,
              name: '_ProfileViewControllerBase.password'))
          .value;
```

Was unsure if this was a bug or expected.  I've updated our code to not use computed for the time being and everything seems to be happy now but figured I'd let you know just in case.

We're running pubspec version `  sdk: ">=2.2.2 <3.0.0"` atm and are working to   `sdk: ">=2.12.0 <3.0.0"` as recommended in the error.

**Comment by pavanpodila** [comment]
For null safety, the min sdk version is `2.12.0`

**Comment by alanrubin** [comment]
I'm experiencing this issue... if my app doesn't work with null safety, which version of mobx/mobx_codegen I should use? Or there is an option on mobx_codegen to generate without null-safety?

**Comment by neokree** [comment]
I'm also experiencing this issue, we have a big app that uses mobX and It's impossible for us to migrate it all the way to null-safety in one shot. 

We are trying our best to modularize and make all new modules null safe but in the meanwhile we need a way to allow mobx_codegen to generate Stores without non-nullable language features at it's latest version and under Flutter 2.2.

Is there a way to do so?

**Comment by neokree** [comment]
For anyone having the same problem, I have forked the project from `mobx_codegen: 1.1.2` and upgraded all dependencies to work with Flutter 2. This way the generated code doesn't use null-safety features and you can migrate your code incrementally.

So now you can import mobx: 2.0.0 and use this for `mobx_codegen`:
```
dev_dependencies:
    mobx_codegen:
        git:
          url: https://github.com/neokree/mobx.dart.git
          ref: flutter-2-without-null-safety
          path: mobx_codegen
```

Tested with Flutter 2.2.2
