### ISSUE TITLE
initState and setState() or markNeedsBuild() called during build exception

### ISSUE THREAD

**Issue by ChessMax** [mobxjs/mobx.dart#667]
In several places of our app there are exceptions like this:
```The following MobXCaughtException was thrown:
setState() or markNeedsBuild() called during build.
This Observer widget cannot be marked as needing to build because the framework is already in the
process of building widgets.  A widget can be marked as needing to be built during the build phase
only if one of its ancestors is currently building. This exception is allowed because the framework
builds parent widgets before children, which means a dirty descendant will always be built.
Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Observer
The widget which was currently being built when the offending call was made was:
  Builder

When the exception was thrown, this was the stack:
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      ObserverElementMixin.invalidate (package:flutter_mobx/src/observer_widget_mixin.dart:70:24)
#3      ReactionImpl._run (package:mobx/src/core/reaction.dart:119:22)
#4      ReactiveContext._runReactionsInternal (package:mobx/src/core/context.dart:345:18)
#5      ReactiveContext.runReactions (package:mobx/src/core/context.dart:319:5)
#6      ReactiveContext.endBatch (package:mobx/src/core/context.dart:149:7)
#7      ActionController.endAction (package:mobx/src/core/action.dart:107:9)
#8      _$CatalogState.changeCatalogIndex (package:my_app/catalog/state/catalog_state.g.dart:37:43)
#9      _CatalogViewState.initState (package:my_app/catalog/catalog_view.dart:277:19)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
...     Normal element mounting (112 frames)


```
Sometimes it's possible to avoid such an error by deferring state modification with `SchedulerBinding.instance.addPostFrameCallback`. And I don't fond of such a solution, but at least no error. But there are places in code where this hack doesn't work. I really want to understand how to deal with it without hacks. The problem is I couldn't provide a reproducible code, because I can't reproduce this behavior in a simple demo app. And I have no idea why. `_CatalogViewState` looks like that:

```
class _CatalogViewState extends State<CatalogView> {
  PageController _pageController;
  TabController _tabController;

  ProductsState _productsState;
  FarmersState _farmersState;
  ToursState _toursState;
  DishesState _dishesState;
  CatalogState _catalogState;
  CategoriesState _categoriesState;
  FiltersState _filtersState;
  GeoState _geoState;

  int get _index() => _catalogState.catalogIndex;

  // ...
 
  @override
  void initState() {
    super.initState();
    _productsState = Provider.of<ProductsState>(context, listen: false);
    _farmersState = Provider.of<FarmersState>(context, listen: false);
    _toursState = Provider.of<ToursState>(context, listen: false);
    _dishesState = Provider.of<DishesState>(context, listen: false);
    _catalogState = Provider.of<CatalogState>(context, listen: false);
    _categoriesState = Provider.of<CategoriesState>(context, listen: false);
    _filtersState = Provider.of<FiltersState>(context, listen: false);
    _geoState = Provider.of<GeoState>(context, listen: false);
    if (widget.defaultCategorySlug != null) {
      SchedulerBinding.instance.addPostFrameCallback((_) => _initDefaultSelectedCategory());
    }
    _clearEmptyDishesCategories(); 
    _catalogState.changeCatalogIndex(widget.defaultIndex);
    _pageController = PageController(initialPage: _index);
    _pageController.addListener(_switchTabColor);
  }

  // ...
}
```
and CatalogState like that:
```
class CatalogState = _CatalogStateBase with _$CatalogState;

abstract class _CatalogStateBase with Store {
  @observable
  int catalogIndex = 0;

  @action
  void changeCatalogIndex(int index) {
    catalogIndex = index;
  }
}
```
The strange thing is the error doesn't throw when I just opening CatalogView, but it happens if I open the catalog view item, then on the item details page, I return to the catalog view page. Flutter creates a fresh new CatalogView in that case and an error constantly appears.

Somewhere found that I should change store only during the reaction. But in this case what reaction should I choose? Besides I need to run this code only once. I've tried autorun reaction, but it just breaks the code and nothing is working as it should.

If I can't mutate store in `initState` (despite of the fact that in most cases it works well) then where is the alternative place for it?

Also, I've tried this:

```
autorun((_) => _catalogState.catalogIndex, (int index){
   _catalogState.changeCatalogIndex(widget.defaultIndex);
});
```
and this:
```
untracked(() {
  _catalogState.changeCatalogIndex(widget.defaultIndex);
});
```
but no luck(.

Any help or idea on how to debug it and fix is appreciated.

**Comment by Rudiksz** [comment]
> _catalogState.changeCatalogIndex(widget.defaultIndex);

this call in your initState is what is most likely causing the error. You probably have an Observer widget in your build method that is observing the catalogIndex, and causes exactly what the error says.

Try to move that call to didChangeDependencies method which is called a bit later in the build phase.

**Comment by ChessMax** [comment]
Thank you. I'll give it a try. I didn't even think about such an opportunity. If it works the only thing is to check not to execute the code several times, due to the fact that didChangeDependencies runs multiple times. It looks better then SchedulerBinding.instance.addPostFrameCallback.

**Comment by ChessMax** [comment]
Sorry to say, but `didChangeDependencies` produces the same error.

**Comment by tomwyr** [comment]
Does it mean there's no way to do any store initialization work before first build?
