### ISSUE TITLE
Reaction in Mobx is getting triggered more than once

### ISSUE THREAD

**Issue by vip20** [mobxjs/mobx.dart#671]
I am trying to show a snackbar when there is an error in API. 
I am initializing reactions in _**build()**_ method.
The snackbar triggers more than once. I also tried calling them in _**didChangeDependencies()**_.

Has anyone faced the same issue.

Below is a code template, that I am trying.
```
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _disposers = <ReactionDisposer>[reaction((_) => _userStore.status == Status.error, (_) {
    // Show snackbar
    })];
  }


  @override
  void dispose() {
    super.dispose();
    if (_disposers != null) {
      _disposers?.forEach((d) => d());
    }
  }
```

**Comment by vip20** [comment]
Seems like the condition has to be re-written inside the function as well. Not sure if this is an issue or my understanding might be wrong. Closing this.

**Comment by vip20** [comment]
When I restart the `flutter run` this issue pops up.

**Comment by bogdanmarinescu** [comment]
usually reactions must be declared in initState. 
https://mobx.netlify.app/examples/connectivity

**Comment by vip20** [comment]
> usually reactions must be declared in initState. 
> https://mobx.netlify.app/examples/connectivity

I've initialized store in didChangeDependencies(). So that the changes in store can be captured. Am I doing this wrong? 

In the example you've shared, the store is passed as a parameter to the widget

**Comment by bogdanmarinescu** [comment]
> > usually reactions must be declared in initState.
> > https://mobx.netlify.app/examples/connectivity
> 
> I've initialized store in didChangeDependencies(). So that the changes in store can be captured. Am I doing this wrong?
> 
> In the example you've shared, the store is passed as a parameter to the widget

once you setup up a reaction you don't need to refresh it. the callback will be triggered every time the observer changes.

**Comment by vip20** [comment]
> > > usually reactions must be declared in initState.
> > > https://mobx.netlify.app/examples/connectivity
> > 
> > I've initialized store in didChangeDependencies(). So that the changes in store can be captured. Am I doing this wrong?
> > 
> > In the example you've shared, the store is passed as a parameter to the widget
> 
> once you setup up a reaction you don't need to refresh it. the callback will be triggered every time the observer changes.  

I was mentioning about initializing store within the State widget.

**Comment by bogdanmarinescu** [comment]
> > > > usually reactions must be declared in initState.
> > > > https://mobx.netlify.app/examples/connectivity
> > > 
> > > 
> > > I've initialized store in didChangeDependencies(). So that the changes in store can be captured. Am I doing this wrong?
> > > In the example you've shared, the store is passed as a parameter to the widget
> > 
> > 
> > once you setup up a reaction you don't need to refresh it. the callback will be triggered every time the observer changes.
> 
> I was mentioning about initializing store within the State widget.

my bad. in your case you can initialize the store and the reactions in initState.

**Comment by bogdanmarinescu** [comment]
in didChangeDependencies you have multiple reactions to the same observable you must dispose the previous one and set up a new one

**Comment by vip20** [comment]
One thing that worked for me is re test the condition within the reaction.

Do you mean that I've to write a separate disposer for each reaction?

**Comment by bogdanmarinescu** [comment]
based on your code every time didChangeDependencies is called you are instantiating a new reaction. correct? do you dispose the previous one?

**Comment by vip20** [comment]
> in didChangeDependencies you have multiple reactions to the same observable you must dispose the previous one and set up a new one 

I get it. I'll try this out and close this issue

**Comment by vip20** [comment]
- Cannot initialize MobxStore in init as it need to run after init state and before Widget build
- Tried disposing the reactions before trying again, this is also triggering the reaction twice.

Only workaround I could come up is that set the currentState of the variable within the Widget and check whether it has changed and show the snackbar.

I know this is a dirty workaround, but I couldn't find any solution as for now.

**Comment by gab07** [comment]
didChangeDependencies: [Called when a dependency of this State object changes](https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html)

I'm guessing that **didChangeDependencies()** gets called multiples times without a single call to **dispose()**

If my guess is right, you're losing references to previous reactions with this line:

`_disposers = <ReactionDisposer>[reaction((_) => _userStore.status == Status.error, (_) {
    // Show snackbar
    })];`

You're creating a new list every time **didChangeDependencies** gets called
