### ISSUE TITLE
ObservableStream.value does not report consecutive equal values from the stream

### ISSUE THREAD

**Issue by dev00111** [mobxjs/mobx.dart#679]
If I take the RandomStore example
```
  _RandomStore() {
    _streamController = StreamController<int>();

    _timer = Timer.periodic(const Duration(seconds: 1),
        (_) => _streamController.add(_random.nextInt(100)));

    randomStream = ObservableStream(_streamController.stream);
  }

```

and change the argument of _random.nextInt(100) to 6, to simulate a dice roll, my observer only rebuilds when an integer added to the stream is different from the previously added value.
```
            Observer(
              builder: (_) {
                final value = store.randomStream.value;

                return Text(
                  '${value == null ? '---' : value}',
                  style: TextStyle(fontSize: 96),
                );
              },
```
My expectation would be that a new value added to observable stream is always reported regardless of the equality to the previous value (could be wrong expectation, but when I read a stream of zeroes I receive as many zeroes as was written and not a single zero). For example, I would like to modify the example to make an animation of a rolling dice every time I receive a new value from the stream. It will not trigger observer builder function when random return several equal integers in a row, so will skip the animation. Also, I don't find an obvious way in the documentation on how to achieve the desired behavior.

The behavior can be changed in observable_stream.dart by adding   ```_data.reportChanged();```
```
  void _onData(T data) {
    final actionInfo = _actions.startAction();
    try {
      _status.value = StreamStatus.active;
      _valueType.value = _ValueType.value;
      _data.value = data;
      _data.reportChanged();
    } finally {
      _actions.endAction(actionInfo);
    }
  }
```

**Comment by amondnet** [comment]
@dev00111 

https://github.com/mobxjs/mobx.dart/blob/f8677da98b2077ae22b536abe3ea11be2ba8050e/mobx/lib/src/api/async/observable_stream.dart#L439

https://github.com/mobxjs/mobx.dart/blob/f8677da98b2077ae22b536abe3ea11be2ba8050e/mobx/lib/src/core/observable.dart#L62

https://github.com/mobxjs/mobx.dart/blob/f8677da98b2077ae22b536abe3ea11be2ba8050e/mobx/lib/src/core/observable.dart#L106

The observable doesn't fire a notification because the value(6) hasn't changed.
