### ISSUE TITLE
ObservableStream.value throws Exception when data is null

### ISSUE THREAD

**Issue by moritz-weber** [mobxjs/mobx.dart#681]
First of all: Thank you for your work :)

I stumbled across an error when migrating to null-safety.
The problematic code is in `mobx/lib/src/api/async/observable_stream.dart` (around line 42):

    /// Current value or null if waiting and no initialValue, or null if data is an error.
    @override
    T? get value =>
        _controller.valueType == _ValueType.value ? _controller.data as T : null;

In my case, no error has occurred so `valueType == value` but `data` is null.
Therefore, mobx tries to cast null to T and throws an ugly error.
I could manually check for `waiting` before accessing `value`, but I'm lazy and think this should be fixed here ;)

**Comment by pavanpodila** [comment]
How about a PR?

**Comment by moritz-weber** [comment]
Just created the PR. Let me know if this works for you. I don't contribute code to other projects very often.

**Comment by windrunner414** [comment]
hi, when will a release contain this PR? The latest version was released 3 months ago. I also faced this issue and now I have to use dependency_overrides to let it work

**Comment by pavanpodila** [comment]
Hi, my laptop had to be changed and I'll take a day or two to get it back. Should be published this week.

**Comment by pavanpodila** [comment]
@windrunner414 this is now published: https://pub.dev/packages/mobx
