### ISSUE TITLE
Upgrade to analyzer 2.0.0

### ISSUE THREAD

**Issue by carlosfiori** [mobxjs/mobx.dart#688]
Please upgrade to the newest version, I'm having this issue:
`Because no versions of mobx_codegen match >2.0.1+3 <3.0.0 and mobx_codegen 2.0.1+3 depends on analyzer ^1.4.0, mobx_codegen ^2.0.1+3 requires analyzer ^1.4.0.
And because json_serializable >=5.0.0 depends on analyzer ^2.0.0, mobx_codegen ^2.0.1+3 is incompatible with json_serializable >=5.0.0.`

**Comment by hdn-luan** [comment]
Not just json_serializable, dart freezed is another package whose latest version needs analyzer version 2.0.0 and we cannot use the previous version because of the null safety update

**Comment by carlosfiori** [comment]
#688
