### ISSUE TITLE
Libraries should be plain Dart/Flutter packages instead of a plugin

### ISSUE THREAD

**Issue by roughike** [mobxjs/mobx.dart#69]
By looking at the folders inside `mobx_codegen`, `flutter_mobx`, and `mobx`, you can see `android` and `ios` folders there. As far as I can tell, none of these packages need to be plugins. 

To me, it seems that the projects have been originally created using the Flutter plugin template project, but the pubspec files have been since cleaned out from Flutter plugin stuff. If this is the case, it should be fine to just remove the `android` and `ios` folders and call it a day. It shouldn't matter anyway, but it might be confusing to look at the source for some.

**Comment by pavanpodila** [comment]
Agree @roughike. I just removed the `ios` and `android` folders.
