### ISSUE TITLE
Code generation is too long

### ISSUE THREAD

**Issue by subzero911** [mobxjs/mobx.dart#690]
Hi. I really like MobX and I used it in my project. But the larger the project becomes, more time it takes for build_runner to generate the code (up to several minutes). And I heared about the cases on really big projects, when it takes 40 minutes on every VSCode launch!
Any ideas how to get rid of code generation? Or at least to reduce its time?

**Comment by pavanpodila** [comment]
One option is to avoid using annotations and skip the whole code-generation part. However it does add a bit of boilerplate, which can be avoided by some text-macros in the IDE. I've seen some folks do that. 

In the future, once there are better macro facilities in Dart, the whole code-generation story can be much better.

**Comment by bogdanmarinescu** [comment]
try to use a build.yaml to restrict the code gen
