### ISSUE TITLE
More linter rules

### ISSUE THREAD

**Issue by katis** [mobxjs/mobx.dart#7]
I think that the project would benefit from adding more analysis rules, and now at the beginning of the project is probably a good place to do it.

https://www.dartlang.org/guides/language/analysis-options#the-analysis-options-file

I'd be willing to work on this, adding rules and fixing their suggestions.
I think I could start by adding the ` prefer_final_locals` rule, and replacing `var`s with `final`s.

**Comment by pavanpodila** [comment]
Yes that would be great @katis . Agree now is a good time to enforce these rules

**Comment by katis** [comment]
Implemented in https://github.com/mobxjs/mobx.dart/pull/8
