### ISSUE TITLE
Flutter hooks integration

### ISSUE THREAD

**Issue by rrousselGit** [mobxjs/mobx.dart#70]
A discussion specific to `flutter_hooks` integration, as I think there's a lot to talk about.

The current candidates:

- useObserver
- useWhen
- useReaction
- useAction
- useAutorun

____

# useObserver

I see two potential usages:

```dart
useObserver();
someStore.field; // subscribed to field
```

And

```dart
final result = useObserver.scoped(() {
  someStore.field; // listen to field
  return 42;
});
someStore.otherField; // outside of the scope, not listened
```

`useObserver` is used when we want to rebuild a widget based on a mobx store.

The scoped version can be useful for custom hooks published to pub. We may not want to observe the entire build method in that case. 

____

Specs of others coming soon~

____

I think what should really be discussed of is how do we want to handle rebuild and hot reload.

One thing that `flutter_hooks` allows is dynamically changing the callback passed to a `useAction` and similar.

Depending on how we implement it, the behavior may be unexpected.

**Comment by pavanpodila** [comment]
I would suggest renaming `scoped` to `untracked` as that's the nomenclature in the MobX world. So by default everything inside `build()` would be tracked and parts which should be "untracked" are wrapped inside **`untracked`**. So, it's inverted in the usage and behavior.

Also, a **`useAutorun()`** would be needed.

**Comment by rrousselGit** [comment]
Agreed

About hot-reload, a concrete example:

`useAutorun` syntax will likely be as followed:

```dart
useAutorun(() {
  // do something
});
```

This is very common to use closures instead of static functions for hooks. Which means the instance of the closure may change between calls of `build` method

In theory, we can just ignore the callback on subsequent renders.


But then it's not ideal when we want to change the implementation of the callback through hot-reload.

What do we want in that situation?

**Comment by katis** [comment]
Ignoring the callback change with `useAutorun` seems the only way to make it work like it's supposed to. Could hot reload dispose the autorun and make the hook recreate it when the widget gets re-rendered?

**Comment by katis** [comment]
Is the `scoped`/`untracked` necessary, since you can do your non-tracked stuff before calling `useObserver`?

**Comment by pavanpodila** [comment]
You might still need it if you want to read an observable but not track it inside the reaction. Doing it outside might be too soon and won't have the correct value at the time the reaction runs.

**Comment by rrousselGit** [comment]
> Is the scoped/untracked necessary

Yes, because we can make custom hooks and share them on pub.

It would be unideal for a hook to use `useObserver` in a non-scoped manner, and this leak on the full build method.

**Comment by rrousselGit** [comment]
> Could hot reload dispose the autorun and make the hook recreate it when the widget gets re-rendered?

Right now, no. With some changes on `flutter_hooks`, it should be doable though. 

I can add a `didReassemble(Hook previousHook)`. This should be enough for `HookState` to trigger custom logic

**Comment by rrousselGit** [comment]
What can we do to support live updates of fields such as `name` or `delay`/`timeout`? 

Currently, the only way is to destroy the previous reaction and build a new one.
But that's not ideal, as it will trigger predicates again, which may produce undesired side-effects.

**Comment by pavanpodila** [comment]
@rrousselGit Could you take a look at this failing test on Travis: https://travis-ci.com/mobxjs/mobx.dart/jobs/176522522#L713. I merged the code into master since it was passing on branch

**Comment by rrousselGit** [comment]
As said on the PR, this is not a problem. It is due to hooks relying on master channel of Flutter, where `reassemble` used to be private and I made it public.

That's why the CI have been modified to run for both beta and master channel and that `flutter_mobx_hooks` is purposefully allowed to failed on `beta` channel (but not on master)

**Comment by pavanpodila** [comment]
Ah missed that part. Thanks for clarifying.

**Comment by rrousselGit** [comment]
I don't think we should close this. There are still some questions about updates and prototypes.

For example, the implementation of `useObserver` that @katis made do not expose `onError` and `name`. Is this desired?

If so, then we should remove them from other hooks (which exposes them rn). 
If not, then we should add it to `useObserver`.

And there are some more advanced topics:

- What do we do when a widget is rebuilt and sends a different `timeout` to `useWhen`? 
- Same, but for `delay` and `useAutorun`/`useReaction`?

Currently the only solution is to dispose the previous reaction and create a new one. It shouldn't cause issues with `useWhen`, but for `useAutorun` it's definitely not desired.

**Comment by rrousselGit** [comment]
Temporary close. I'm overloaded and can't work on this. 

@pavanpodila should I extract it outside of Mobx repo? It's not even published right now.

**Comment by pavanpodila** [comment]
Ya not a bad idea. It probably fits better inside your hooks repo.

**Comment by smiLLe** [comment]
@rrousselGit you already started a new repo for this? perhaps i can be of some help?

**Comment by rrousselGit** [comment]
I haven't. Feel free to do so! Let's speak about it there: https://github.com/rrousselGit/flutter_hooks/issues/83

@pavanpodila You can delete it anytime you want. I still have my fork with the sources

**Comment by pavanpodila** [comment]
Cool. Thanks for the heads up!
