### ISSUE TITLE
using AnimatedSwitcher with Observer

### ISSUE THREAD

**Issue by DJafari** [mobxjs/mobx.dart#703]
is possible use `AnimatedSwitcher` inside `Observer` widget to animate change when some variable changed ?

i test but animation not work. do you have any solution ?

**Comment by LoAlex** [comment]
@DJafari  I have the same problem too, how you solve this problem?

**Comment by DJafari** [comment]
@LoAlex check [this](https://stackoverflow.com/questions/54606771/animate-show-or-hide-widgets-with-flutter/62779504#62779504)

**Comment by LoAlex** [comment]
> @LoAlex check [this](https://stackoverflow.com/questions/54606771/animate-show-or-hide-widgets-with-flutter/62779504#62779504)
> 
> using `Key` is important

thanks for your tips, finally fixed.
