### ISSUE TITLE
How to convert a `Observable` (or `Computed`) to a `Listenable`?

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#712]
Hi thanks for the lib! Flutter has a built-in `Listenable` class, and it is widely used (e.g. for CustomPainter). Thus, I wonder how can I integrate mobx's system into that? Thanks!

**Comment by subzero911** [comment]
The idea lying on the surface is to have a Store `with ChangeNotifier` and to add a Reaction on observable change, and call notifyListeners() inside.
