### ISSUE TITLE
Make example readme beginner friendly

### ISSUE THREAD

**Issue by DomiR** [mobxjs/mobx.dart#72]
I'm a beginner in flutter, coming from react-native mobx and need more instructions on how to get the examples and generators running. Now that the android and ios folders have been removed I'm not able to use `flutter run` any more and I would like it for other beginners not struggle as much as I'm currently doing...

First I got this error as soon as I added the current mobx to a new project from `flutter create`.
```bash
Because every version of flutter_test from sdk depends on meta 1.1.6 and mobx >=0.0.24 depends on meta ^1.1.7, flutter_test from sdk is incompatible with mobx >=0.0.24.
```
... so I had to figured out how to use dependency_overrides, which is hopefully the right way to resolve this.
```yaml
dependency_overrides:
    meta: ^1.1.7`
```

Now I'm stuck with the generators. I've pasted the store from the example to my newly created project with `build_runner` and `mobx_codegen` as dev dependencies and according to the readme I should be able to call `flutter packages pub run build_runner build` but nothing is being generated. After some googling I figured out that I need a `build.yaml` and I found one in the mobx_codegen I'm trying to steal from it, but I can't figure out how to make it work 😢 

All in all, it would be really helpful to have the readme in the example written in such a way, that a beginner like me can get started and dabble around a bit much faster 👍Please add a **requirement** section to the example readme with links to the flutter install page and a **getting started** section with a list of all commands necessary to make a fresh clone from this repository run on a simulator including every command required to re-generate/rebuild stuff after code edits.

Thank you so much for your huge efforts. I've been having a blast following the progress of this repo and I'm very much excited to get my hands dirty with flutter+mobx.

**Comment by pavanpodila** [comment]
That's exactly what we are working on next 👍. We should have something early next week or even before. I'll make sure to address all the points you raised. Will ping back on this thread for you to try it the new getting started guide

**Comment by rrousselGit** [comment]
For the "flutter run" issue, you can still do it:

```dart
flutter create .
flutter run
```

**Comment by pavanpodila** [comment]
BTW, @DomiR we are building a website where "Getting Started" is one of the pages. You can track the progress here or even leave comments: #71

**Comment by pavanpodila** [comment]
@DomiR Can you check this out: https://mobx-dart.netlify.com/getting-started. Closing this for now. Feel free to reopen if you find something missing.
