### ISSUE TITLE
(Willing to contribute) (With trivial short reproducible code) All `autorun`/`reaction` are silently NOT executed as long as one exception happens in one autorun/reaction - thus app becomes unusable as long as one (caught) exception occurs

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#720]
Hi thanks for the wonderful lib! There is a problem as described in title. This makes app unusable as long as one (caught) exception occurs

Reproducible code:

```
import 'package:mobx/mobx.dart';

void main() async {
  mainContext.config = ReactiveConfig(disableErrorBoundaries: true);

  print('outside 1');
  autorun((_) {
    print('inside 1');
  });

  print('outside 2');
  reaction((_) => 42, (_) {
    print('inside 2');
  }, fireImmediately: true);

  try {
    print('outside 3');
    autorun((_) {
      print('inside 3');
      throw Exception('deliberate error');
    });
  } catch (e) {
    print('catch 3: e=$e');
  }

  print('outside 4');
  autorun((_) {
    print('inside 4');
  });

  print('outside 5');
  reaction((_) => 42, (_) {
    print('inside 5');
  }, fireImmediately: true);

  print('outside 6');
}
```

Output

```
flutter: outside 1
flutter: inside 1
flutter: outside 2
flutter: inside 2
flutter: outside 3
flutter: inside 3
flutter: catch 3: e=MobXCaughtException: Exception: deliberate error
flutter: outside 4
flutter: outside 5
flutter: outside 6
```

Expect: the `inside 4/inside 5` should be printed. But they are not.

Hi @pavanpodila I am willing to make a pr.

**Comment by pavanpodila** [comment]
This is be design as per the original mobx spec. See the mobx docs: https://www.mobxjs.com/refguide/api.html#configure

**Comment by fzyzcjy** [comment]
@pavanpodila Thanks for the reply!

I seem not to see "resetGlobalState": https://github.com/mobxjs/mobx.dart/search?q=resetGlobalState ... So do we have it in Dart?

**Comment by pavanpodila** [comment]
Ya it's missing. Never had this use case until now😉. I'll try to patch this in a day or so.

**Comment by fzyzcjy** [comment]
@pavanpodila Moreover, I wonder what is the *correct way* of dealing with exceptions in mobx dart? From that doc, I guess I should set `disableErrorBoundaries` to false. But then, when and where should I report error to sentry?

**Comment by fzyzcjy** [comment]
> Never had this use case until now😉

If the correct way you suggest does not need this, then no need for patch ;)

**Comment by fzyzcjy** [comment]
I have read the source code and get confused. Here is my naive guess:

* set `disableErrorBoundaries` to false (default value)
* use `mainContext.onReactionError = ...` to have a hook when `reaction` has error. (Question: does it also capture `autorun`, `when`, `asyncWhen`, etc?)
* Then what about `@computed`? Seems that it does not expose anything :(
* And what about `@action`? :(

**Comment by fzyzcjy** [comment]
@pavanpodila I am willing to make a PR. Could you please provide some suggestions?

**Comment by fzyzcjy** [comment]
All right. Let me assume the dart version just mimics the js version, and I just follow the js guide ;)
