### ISSUE TITLE
directly accesible private fields marked with @readonly annotation

### ISSUE THREAD

**Issue by VenturaLorenzo** [mobxjs/mobx.dart#729]
I'm experimenting with state management solutions in Flutter framework and i'm currently working with MobX. I really like the its approach but i'm a bit concerned in the way it handles the state's changes. There is the possibility to customize the strict-mode to avoid changing the state outside actions. However ,using the code generator, ad hoc actions are created for observable values. It is just fine that every state change happends into an action and I think it was the aim when automatically created setter and getter were introduced but, how can we force the state to be changed only by predefined actions now? And here comes my questions. I want to find a way to allow state changes only through predefined actions. For example, I would like to create a counter store where the counter value can be incremented only by 1. I read the documetantion about MobX for Flutter framework quite in dept and I found that @readonly fields should provide the behaviour I was looking for.
I set up a simple example using the code provided in the documentation
```
class Counter = _Counter with _$Counter;

abstract class _Counter with Store {
  @readonly
  int _value = 0;

  @action
  void increment() {
    _value++;
  }
}

final Counter counter = Counter(); // Instantiate the store

void main() {
  mainContext.config = mainContext.config
      .clone(isSpyEnabled: true, writePolicy: ReactiveWritePolicy.always); //Set the strict mode to always
  mainContext.spy((event) { //Use the spy function to detect actions
    print("event name : " + event.name);
    print("event type : " + event.type);
  });
  counter._value = 10; // Directly setting the _value to 10
  print(counter._value);
}
```
I previously set the strict-mode to always , also if it wasn't necessary , just to be sure. I don't get why the _value field is still directly accessible even if it is annotated with @readonly. 

What I tried:
I tried to achive the same task using MobX with React and , in that scenario , I fullfilled my goal using the solution provided in this issue :
https://github.com/mobxjs/mobx/issues/2497
I read the issue about the introduction of the @readonly annotation 
https://github.com/mobxjs/mobx.dart/issues/220
I opened up a question on stackoverflow 
https://stackoverflow.com/questions/70519835/forcing-the-mobx-state-to-be-changed-through-declared-actions-only-in-the-flutte
Is the @readonly annotation not working as intended or am I doing something wrong?

**Comment by Ascenio** [comment]
> I previously set the strict-mode to always , also if it wasn't necessary , just to be sure. I don't get why the _value field is still directly accessible even if it is annotated with @readonly.
That is a Dart limitation (maybe feature?). What happens is that when you declare something as private, it's only private for external files but visible for another functions/classes in same file. So, to make `Counter._value` **really** private you must extract it to its own file.

**Comment by VenturaLorenzo** [comment]
Oh , clear! All working as intended then. Thanks!
