### ISSUE TITLE
Async action reports to spy hundreds of times on each run

### ISSUE THREAD

**Issue by makstheimba** [mobxjs/mobx.dart#734]
Hi! We've added a spy for mobx so we can see in console what is happening with our stores. However it's not really usable for us because for some reasons async actions report to spy hundreds of times during a coarse of single action. I was able to reproduce this issue using [HackerNews](https://github.com/mobxjs/mobx.dart/tree/master/mobx_examples/lib/hackernews) example from mobx tutorial.

To reproduce:
1.  Replace HackerNewsStore in [news_store.dart](https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/lib/hackernews/news_store.dart) with the one that has async action instead of `FutureObserver`:
```
abstract class _HackerNewsStore with Store {
  final _hnApi = HNApi();

  @observable
  List<FeedItem> latestItems = [];

  @action
  Future<void> loadNews(FeedType type) async {
    if (type == FeedType.latest) {
      latestItems = await _hnApi.newest();
    } else if (type == FeedType.top) {
      topItems = await _hnApi.top();
    }
  }
```
2. Replace `FeedItemsView` from [news_widgets.dart](https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/lib/hackernews/news_widgets.dart) to use only `latestItems` from store for simplicity of example:
```
class FeedItemsView extends StatelessWidget {
  const FeedItemsView(this.store, this.type, {Key? key}) : super(key: key);

  final HackerNewsStore store;
  final FeedType type;

  @override
  // ignore: missing_return
  Widget build(BuildContext context) => Observer(builder: (_) {
        final List<FeedItem> items = store.latestItems;
        return ListView.builder(
            physics: const AlwaysScrollableScrollPhysics(),
            itemCount: items.length,
            itemBuilder: (_, index) {
              final item = items[index];
              return ListTile(
                leading: Text(
                  '${item.score}',
                  style: const TextStyle(fontSize: 20),
                ),
                title: Text(
                  item.title,
                  style: const TextStyle(fontWeight: FontWeight.bold),
                ),
                subtitle: Text('- ${item.author}'),
                onTap: () => store.openUrl(item.url),
              );
            });
      });
}
```
3. Enable Spying in [main.dart](https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/lib/main.dart):
```
mainContext.config = mainContext.config.clone(
    isSpyEnabled: true,
  );
```
4. Run codegen - `flutter packages pub run build_runner watch --delete-conflicting-outputs`
5. Run the project

**Expectation:**
`loadNews` action in HackerNewsStore runs only once and reports to spy about running once on Start and once on End.

**Reality:**
`loadNews` action in HackerNewsStore indeed runs only once (I can even test it by adding `print` statement inside async action) but reports to spy 450 (!) times about it's Start and End
![image](https://user-images.githubusercontent.com/6356324/149900779-086f6bde-6c5d-4ed7-b310-f1d2e6851c46.png)

Using:
flutter_mobx: 2.0.3
mobx: 2.0.6

**Comment by pavanpodila** [comment]
Ya this definitely needs to be fixed. I am currently running short on bandwidth. I am happy to take a PR if you can and review and help you over there. Let me know if we can collaborate to fix this over a PR.

**Comment by makstheimba** [comment]
Thanks for response. I'll see if I have enough motivation to dig into this on the weekends :)

**Comment by roitalpaz** [comment]
is this in any roadmap to be fixed?
this renders the spy a bit useless for us :(

**Comment by pavanpodila** [comment]
Let's get a PR rolling. I can review and we can put in the fix.

**Comment by s0nerik** [comment]
Here's the fix: https://github.com/mobxjs/mobx.dart/pull/784

The issue was (the way I understand it) that the action zone's `run` and `runUnary` were overridden in a way that was treating each "continuation" (the synchronous part between two `await`s) as a separate action, which is wrong - all "continuations" are just parts of the same async action and can happen really deep inside some library (in my case it was a single gRPC call that triggered lots of "buffer processing continuations" giving me a huge amount of unnecessary action events).

Nonetheless, I think it might be useful to have a (disabled by default) option to spy on these "continuations" as well. But in order to do that, a new kind of event has to be introduced, which must be traceable to the original action that triggered it. Since it looks like there's no easy way to achieve that right now, I'll just leave it as an idea for the future.

**Comment by danteCarvalho** [comment]
is this related to #791 ?
