### ISSUE TITLE
Why should I use Provider in Mobx Flutter?

### ISSUE THREAD

**Issue by coolswood** [mobxjs/mobx.dart#738]
The official Mobx documentation for Flutter says that in order to transfer data correctly, you must use a Provider and refer to the context to retrieve the data.

But why can't I just call the Mobx class at the root of the application and access the global variable to get the data?

```
CbtStore cbt = CbtStore();

void main() async {
runApp(const MyApp());
}
```
Why should I be doing this?

```
void main() async {
runApp(MultiProvider(
         providers: [
           Provider<CbtStore>(create: (_) => CbtStore()),
           ],
      child: MyApp()));
}
```

And how do I refer to Mobx inside the widget methods in that case, for example, if I want to call the action in the Mobx class in initState method? Now I do it in the following way. But when using Provider in initState there is no context.

```
@override
  void initState() {
    cbt.init();
    super.initState();
  }
```

**Comment by pr-1** [comment]
There is no need to use provider. All you need is a singleton for your store. The reason is Store should be the single source of truth for your data. 
Provider is just a way of achieving that.
global variables are another way of achieving that.

**Comment by coolswood** [comment]
@pr-1 Thanks for clarifying!
