### ISSUE TITLE
@action not throwing exception

### ISSUE THREAD

**Issue by fernando-s97** [mobxjs/mobx.dart#745]
If I remove the @action, this code will still executes normally, but the docs says if @action is mission, this would throw.

```dart
import 'package:mobx/mobx.dart';

part 'home_controller.g.dart';

class HomeController = _HomeController with _$HomeController;

abstract class _HomeController with Store {
  @readonly
  bool _shouldShowOnlyUndoneTasks = false;
  @readonly
  DateTime? _selectedDateForWeekFilter;

  @action
  void toggleShowOnlyUndoneTasks() {
    _shouldShowOnlyUndoneTasks = !_shouldShowOnlyUndoneTasks;
  }

  @action
  void setDateForWeekFilter(DateTime date) {
    _selectedDateForWeekFilter = date;
  }
}
```

**Comment by amondnet** [comment]
@fernando-s97 https://mobx.netlify.app/api/context/#reactive-policies

The write-policy ensures there are no stray mutations of observables. These are applicable for all observables including, singular Observable and collections like ObservableList, ObservableSet and ObservableMap.

- always: Always enforce the writes to happen inside an Action.
- never: Never enforce the write-policy. This means mutations can happen everywhere. We discourage this option as it can result in stray-writes and they lack the benefits of an Action.
- observed: Enforce the mutation to happen inside an Action, only if the observable being mutated is being observed in a Reaction. This is a middle ground between the always and never option. If the observable is not being observed, we allow the mutation and consider it safe. This is the **default** value.

**Comment by fernando-s97** [comment]
Got it. Thanks!
