### ISSUE TITLE
Willing to become a maintainer

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#755]
> We are looking for maintainers. Reach out on Discord or GitHub Issues!

Thus I reach out using this issue :)

**Comment by fzyzcjy** [comment]
@pavanpodila

**Comment by pavanpodila** [comment]
Awesome. Why don't you pick some of the issues as a first step.

**Comment by fzyzcjy** [comment]
Good idea. Maybe https://github.com/mobxjs/mobx.dart/pull/756 could be firstly merged

**Comment by pavanpodila** [comment]
done and you are now a core member of this project :-)

**Comment by fzyzcjy** [comment]
🎉  Going to contribute an enhancement about setState bug in a few days
