### ISSUE TITLE
Add fine-tuning options for `autorun`, `reaction` and `when`

### ISSUE THREAD

**Issue by amondnet** [mobxjs/mobx.dart#782]
`mobx.js` has a option for `autorun`, `reaction` and `when`. I would like to add it to `mobx.dart` as well.

https://mobx.js.org/reactions.html#options-

> ## Options {🚀}
> 
> The behavior of `autorun`, `reaction` and `when` can be further fine-tuned by passing in an `options` argument as shown in the usages above.
> 
> ### `name`
> 
> This string is used as a debug name for this reaction in the [Spy event listeners](analyzing-reactivity.md#spy) and [MobX developer tools](https://github.com/mobxjs/mobx-devtools).
> 
> ### `fireImmediately` _(reaction)_
> 
> Boolean indicating that the _effect_ function should immediately be triggered after the first run of the _data_ function. `false` by default.
> 
> ### `delay` _(autorun, reaction)_
> 
> Number of milliseconds that can be used to throttle the effect function. If zero (default), no throttling happens.
> 
> ### `timeout` _(when)_
> 
> Set a limited amount of time that `when` will wait for. If the deadline passes, `when` will reject / throw.
> 
> ### `onError`
> 
> By default, any exception thrown inside an reaction will be logged, but not further thrown. This is to make sure that an exception in one reaction does not prevent the scheduled execution of other, possibly unrelated reactions. This also allows reactions to recover from exceptions. Throwing an exception does not break the tracking done by MobX, so subsequent runs of the reaction might complete normally again if the cause for the exception is removed. This option allows overriding that behavior. It is possible to set a global error handler or to disable catching errors completely using [configure](configuration.md#disableerrorboundaries-boolean).
> 
> ### `scheduler` _(autorun, reaction)_
> 
> Set a custom scheduler to determine how re-running the autorun function should be scheduled. It takes a function that should be invoked at some point in the future, for example: `{ scheduler: run => { setTimeout(run, 1000) }}`
> 
> ### `equals`: (reaction)
> 
> Set to `comparer.default` by default. If specified, this comparer function is used to compare the previous and next values produced by the _data_ function. The _effect_ function is only invoked if this function returns false.
> 
> Check out the [Built-in comparers](computeds.md#built-in-comparers) section.

related issues: https://github.com/mobxjs/mobx.dart/issues/774

**Comment by amondnet** [comment]
`mobx.dart` already has that feature.

**Comment by subzero911** [comment]
@amondnet what is `fireImmediately`? 
Is it the same to autorun?
