### ISSUE TITLE
Finish documentation for all public API

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#80]
- [ ] Document all the API
- [ ] Get the readme and the website in sync with all the publicly exposed API. 
- [ ] Add examples to the website
- [ ] Add links to the API on pub

**Comment by hazzabee** [comment]
Hi @pavanpodila 
I'm a Technical Writer and keen to get experience in API documentation – please let me know if I can help.
Thanks!
Harriet

**Comment by pavanpodila** [comment]
Hello @hazzabee, it would be fantastic to have you on the project. I suggest you to go through the website: https://mobx.pub and start filling in the **API Overview** section. Feel free to reach out over a PR to get any questions answered.

![image](https://user-images.githubusercontent.com/156846/52637407-27234980-2ef5-11e9-8042-1421a338e5b7.png)


On the site, you can see an "Edit Page" button on top left. You can click on that to create a fork and then send in the PR. Look forward to working with you.

**Comment by hazzabee** [comment]
Hi @pavanpodila thanks for that. Is it a REST API?

**Comment by pavanpodila** [comment]
No, it's a library for managing the reactive state on the client side. Please take a look at the website to learn more.

**Comment by pavanpodila** [comment]
Most of the docs are now on the [API Overview](http://127.0.0.1:3000/api/action) page.
