### ISSUE TITLE
flutter_mobx with version 2.0.5+1 cannot pass build on flutter 2.x

### ISSUE THREAD

**Issue by laohyx** [mobxjs/mobx.dart#814]
Hi team, 

After upgrading `flutter_mobx` from `2.0.5` to `2.0.5+1`, our app build failed.

Here is the details:

## Build error message
/E:/softwares/flutter-2.8.1/.pub-cache/hosted/pub.flutter-io.cn/flutter_mobx-2.0.5+1/lib/src/observer_widget_mixin.dart(92,54): error G19C36D48: **Property 'schedulerPhase' cannot be accessed on 'SchedulerBinding?'** because it is potentially null. [E:\workspace\huaji_app\build\windows\flutter\flutter_assemble.vcxproj]
/E:/softwares/flutter-2.8.1/.pub-cache/hosted/pub.flutter-io.cn/flutter_mobx-2.0.5+1/lib/src/observer_widget_mixin.dart(106,39): error G19C36D48: **Property 'endOfFrame' cannot be accessed on 'SchedulerBinding?' because it is potentially null**. [E:\workspace\huaji_app\build\windows\flutter\flutter_assemble.vcxproj]

```bash
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
[!] Android Studio (version 2020.3)
    X Unable to find bundled Java version.
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.67.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

In flutter 2.10, it seems a optional variable. 

Thanks!

![image](https://user-images.githubusercontent.com/1221508/168405011-f885e9a2-290f-4692-a70d-be90e902a9b0.png)

## Solution
Seems to use `_ambiguate` to make it compatible through 2.x to 3.x
https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0

**Comment by pavanpodila** [comment]
thanks, this is now fixed and available on pub.dev: https://pub.dev/packages/flutter_mobx/changelog
