### ISSUE TITLE
mobx-codegen

### ISSUE THREAD

**Issue by Romavic** [mobxjs/mobx.dart#825]
Since when I upgrade my flutter to version  3.0.1.
I'm using  mobx_codegen: ^2.0.7
The mobx codegen, generate the g.dart classes, but on terminal show;

**[SEVERE] mobx_codegen:mobx_generator on lib/app/ui/resources/themes/dark_theme.dart (cached):**
**InconsistentAnalysisException: Requested result might be inconsistent with previously returned results**
**[SEVERE] Failed after 6.6s**

_I check  flutter doctor -v:_

[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale pt-PT)
    • Flutter version 3.0.1 at /Users/romavicdosanjos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (à 9 dias), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/romavicdosanjos/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.41.20220516

[✓] Connected device (3 available)
    • SM A127F (mobile) • adb-RZ8RA1MTACA-6oEWdi._adb-tls-connect._tcp. • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos                                         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome                                        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by pavanpodila** [comment]
try running the builder with the `--delete-conflicting-outputs` option: https://mobx.netlify.app/guides/output#starting-a-clean-build

**Comment by blaugold** [comment]
@pavanpodila Just FYI, `InconsistentAnalysisException` is an exception that is thrown by the `analyzer` and clients need to retry whatever request they were making. I don't think `--delete-conflicting-outputs` does anything to help with this issue.
