### ISSUE TITLE
Create a PR to send the MobX example to Brian Egan's flutter-samples

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#83]
Brian has a [nice collection of example code](https://github.com/brianegan/flutter_architecture_samples) for various state-management frameworks, all building  TODOMVC. Let's submit one for MobX as well 🥇.

**Comment by rrousselGit** [comment]
I'll soon work on one for `flutter_hooks` and another yet to be released project of mine.

At that time if nobody started it, I can do it for mobx too.

**Comment by rrousselGit** [comment]
I started something [here](https://github.com/rrousselGit/flutter_architecture_samples/tree/mobx)

A good chunk of it is done already. Feel free to have a look! 😄

**Comment by pavanpodila** [comment]
Awesome @rrousselGit. I think we should have a **plain vanilla MobX** as well along with **MobX with Hooks** version

**Comment by rrousselGit** [comment]
Sure. The changes shouldn't be too hard.
I'll make it when I have one that pass all tests

**Comment by brianegan** [comment]
Mobx is looking great -- happy to receive PRs :)

**Comment by pavanpodila** [comment]
> Mobx is looking great -- happy to receive PRs :)

Wow, what an encouraging comment to receive! I am sure one of us will pick it up ASAP!

**Comment by rrousselGit** [comment]
Sorry I have too many things going on right now. If anybody wants to, feel free to continue. 
My work progress is available here: https://github.com/rrousselGit/flutter_architecture_samples/tree/mobx

Otherwise, I'll continue this as soon as I get a bit of time to do so.

**Comment by brianegan** [comment]
Truly, no stress or rush from my side! Whenever you all have the time.

**Comment by pavanpodila** [comment]
@brianegan I have created the TODOMVC example with source code, accompanied with an article on [mobx.pub](https://mobx.pub/examples/todos). Can I make a README.md file and send in a PR? The README will link to the article and the source, which is inside [mobx_examples](https://github.com/mobxjs/mobx.dart/tree/master/mobx_examples/lib/todos).

**Comment by brianegan** [comment]
Heya @pavanpodila! For the Flutter Arch Samples, it would be best to if the app complied with the spec: https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md

IMO, it would be hard to compare what you've got with the other samples, since it does not include include several features: Persistence, Routing, Testing, etc.

**Comment by pavanpodila** [comment]
That does make sense @brianegan. I'll make one as per the spec. Thanks for the clarification!

**Comment by pavanpodila** [comment]
Work is underway here: https://github.com/pavanpodila/flutter_architecture_samples

**Comment by kush3107** [comment]
@pavanpodila I can help you with this flutter architecture example.

**Comment by pavanpodila** [comment]
Why don't you pick up from this repo, where I've made a sizeable set of changes: https://github.com/pavanpodila/flutter_architecture_samples. You can fork and send me a PR on that. All the code is in the mobx folder

**Comment by kush3107** [comment]
Ok thanks I will do that.

**Comment by andesappal** [comment]
Hey could @brianegan 's project also list the pros, cons, and best use cases for each option?

**Comment by MaikuB** [comment]
@pavanpodila it got merged recently so I believe we can close this now right?

**Comment by pavanpodila** [comment]
Good call @MaikuB. This is now available at https://github.com/brianegan/flutter_architecture_samples/tree/master/mobx
