### ISSUE TITLE
Observer not reacting to changes

### ISSUE THREAD

**Issue by ejdoming** [mobxjs/mobx.dart#836]
I'm invoking an action in form onchange event, and the action is doing ok. But the observer is not triggering the build method. Anyone have experienced this issue?

code in the widgets tree:
```
Form(
                key: _formKey,
                onChanged: () {
                  var ok = _formKey.currentState!.validate();
                  _vm.setFormOK(ok);
                },

....

Observer(
                        builder: (_) => MxButton(_vm.formOK.toString(),
                            _vm.formOK == true ? _vm.logar : null))

```
code in Store class:
```
  @observable
  bool formOK = false;
  @action
  void setFormOK(bool value) => formOK = value;

```
code in .g file (code behind)
```
@override
  bool get formOK {
    _$formOKAtom.reportRead();
    return super.formOK;
  }

  @override
  set formOK(bool value) {
    _$formOKAtom.reportWrite(value, super.formOK, () {
      super.formOK = value;
    });
  }

  late final _$_LoginPageVMActionController =
      ActionController(name: '_LoginPageVM', context: context);

  @override
  void setFormOK(bool value) {
    final _$actionInfo = _$_LoginPageVMActionController.startAction(
        name: '_LoginPageVM.setFormOK');
    try {
      return super.setFormOK(value);
    } finally {
      _$_LoginPageVMActionController.endAction(_$actionInfo);
    }
  }
```

[login_page.dart.txt](https://github.com/mobxjs/mobx.dart/files/8951655/login_page.dart.txt)
[login_page_vm.dart.txt](https://github.com/mobxjs/mobx.dart/files/8951656/login_page_vm.dart.txt)
[login_page_vm.g.dart.txt](https://github.com/mobxjs/mobx.dart/files/8951657/login_page_vm.g.dart.txt)

**Comment by ejdoming** [comment]
New update for this issue. After upgrade, no Observer are triggering builder method anymore.

**Comment by ejdoming** [comment]
I have solved the issue downgrading version of mobx to 2.0.7+2

**Comment by quanghd96** [comment]
Same issue with version 2.0.7+3. I must downgrade to version 2.0.7

**Comment by quanghd96** [comment]
It seems to only happen on some devices like virtual machines, some phones,...

**Comment by amondnet** [comment]
#834

**Comment by gabrielscr** [comment]
same problem here

**Comment by gabrielscr** [comment]
I thoughted it was a problem with my app, but seens like's not.

**Comment by gabrielscr** [comment]
@pavanpodila pls

**Comment by phanvanluan94** [comment]
The same issue.
I have to downgrade 2.0.7+2

**Comment by gabrielscr** [comment]
Guys, i solved.

Just remove the @action anottation and run the build runner, then, you see what happens.

**Comment by ejdoming** [comment]
> Guys, i solved.
> 
> Just remove the @action anottation and run the build runner, then, you see what happens.

I didn't understand. Its @action is necessary there, it's not?

**Comment by Eugene-Lam** [comment]
same issue, have to downgrade to 2.0.7+2
