### ISSUE TITLE
Avoid unnecessary observable notifications of `@observable` fields of `Store`s

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#855]
## Question

Is it a deliberate/intended feature? If not, I will PR and fix it.

## Description

Say we have a toy store:

<details>

```
class UserSettingStore = _UserSettingStore with _$UserSettingStore;

abstract class _UserSettingStore with Store {
  @observable
  String setting = 'hello';
}

// auto generated

mixin _$UserSettingStore on _UserSettingStore, Store {
  late final _$settingAtom =
      Atom(name: '_UserSettingStore.setting', context: context);

  @override
  String get setting {
    _$settingAtom.reportRead();
    return super.setting;
  }

  @override
  set setting(String value) {
    _$settingAtom.reportWrite(value, super.setting, () {
      super.setting = value;
    });
  }
}
```

</details>

Notice that, if we assign the same value to it, say, `store.setting = 'hello'; store.setting = 'hello';`, it will *still* trigger notifications to downstreams. This is very insufficient.

On the contrary, IMHO if we have Observable or Computeds, it will auto notice the content it unchanged, and thus not notify any downstream.

--- 

Hi I wonder whether this is deliberately designed like that, or there is a reason why we need the current behavior? Thanks!

Not sure whom to cc, but based on ownership and activities, maybe /cc @pavanpodila @amondnet

**Comment by fzyzcjy** [comment]
Hi I wonder whether this is deliberately designed like that, or there is a reason why we need the current behavior? Thanks!

Not sure whom to cc, but based on ownership and activities, maybe /cc @pavanpodila @amondnet

**Comment by radzish** [comment]
I noticed this too: https://github.com/mobxjs/mobx.dart/issues/849

**Comment by fzyzcjy** [comment]
PR implemented
