### ISSUE TITLE
meta version conflict with Flutter master and dev branch

### ISSUE THREAD

**Issue by piyushmaurya23** [mobxjs/mobx.dart#86]
Error: 
```
Because every version of flutter_test from sdk depends on meta 1.1.6 and mobx >=0.0.24 depends on meta ^1.1.7, flutter_test from sdk is incompatible with mobx >=0.0.24.
```
@pavanpodila Should we downgrade meta dependency to version 1.1.6 in mobx or do we need to raise an issue in flutter repo for upgrading meta version.
Version:
```
mobx: 0.0.33
flutter_mobx: 0.0.8
mobx_codegen: 0.0.4
```

Tested it on flutter master and dev branch, same issue.

**Comment by rrousselGit** [comment]
You can use `dependency_overrides` temporarily:

```yaml
dependency_overrides:
  meta: 1.1.6
```

**Comment by pavanpodila** [comment]
Closing the issue for now.
