### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by subzero911** [mobxjs/mobx.dart#888]
When I go to https://mobx.netlify.net/
it tells "please turn off your adblock"
then it redirects to http://ww1.netlify.net/
then to:

![image](https://user-images.githubusercontent.com/12999702/209511896-b61419b2-53c9-42b8-aaed-7635c2ad27bb.png)

**Comment by fzyzcjy** [comment]
I can confirm this

![image](https://user-images.githubusercontent.com/5236035/209513647-52ef3bd0-eaef-40f7-b129-d4162de28a24.png)

**Comment by ujas-m-simformsolutions** [comment]
isn't site is this -> [https://mobx.netlify.app/](https://mobx.netlify.app/) and it opens fine for me

**Comment by fzyzcjy** [comment]
@ujas-m-simformsolutions You are right, that also works fine for me

**Comment by subzero911** [comment]
Wow, I probably have mixed up the domain.
Yes, this URL does well.
