### ISSUE TITLE
`autorun` isn't triggered on state mutation.

### ISSUE THREAD

**Issue by wiseaidev** [mobxjs/mobx.dart#895]
Hey awesome mobx maintainers,

I have been using this package for the past two days and I have discovered a behavior that I wasn't expecting. The `autorun` method triggers only once when the component is initialized, and then not anymore, even when the observable object has changed. 

## Intended outcome:

`autorun` should react to observables changes.

![mobx-screenshot-state-mutation](https://user-images.githubusercontent.com/62179149/215152759-56815019-19e8-4095-889f-fce2692a8d3d.PNG)

## Actual outcome:

`autorun` is not fired when observables changes.

![mobx-screenshot](https://user-images.githubusercontent.com/62179149/215152872-f072f390-0807-42fc-a133-8ba7be187473.PNG)

## How to reproduce the issue:

I am wondering why such behavior exists and would like to know if there is a fix for it or if this is intended behavior. I've created [a minimal reproducible example](https://github.com/wiseaidev/flutter-mobx-autorun-issue) to narrow down the issue.

If there is an issue in my code, it would be great if you could help me figure out what it is.

Thank you for your time and consideration!

**Comment by amondnet** [comment]
Hi, @wiseaidev 

https://mobx.netlify.app/guides/when-does-mobx-react#rules-of-reactivity
https://mobx.netlify.app/api/observers#reactionbuilder-widget

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      debugShowCheckedModeBanner: false,
      home: ReactionBuilder(
        builder: (context) {
          return reaction(
          (_) =>  context.read<AppState>().currentPage , (v) => print('New value: $v')

            },
          );
        },
        child: Observer(
          name: "CurrentScreen",
          builder: (context) {
            switch (context.read<AppState>().currentPage) {
              case AppPage.splash:
                return const MySplashPage(title: "Splash Page");
              case AppPage.home:
                return const MySplashPage(title: "Home Page");
              case AppPage.login:
                return const Placeholder();
            }
          },
        ),
      ),
    );
  }
}
```

**Comment by amondnet** [comment]
@wiseaidev Please reopen if you have more questions.

**Comment by wiseaidev** [comment]
Hey @amondnet,

Thanks for the response. I will try your suggestion and get back in an hour or so cause I am AFK at the moment(using gh mobile).

**Comment by wiseaidev** [comment]
Hey @amondnet,

I have just tried both examples, but the problem still exists.

![11](https://user-images.githubusercontent.com/62179149/215166967-3f703243-6d79-4b05-a441-ff97acdf451f.PNG)

I think you are using an older version of flutter. My specs:

![112](https://user-images.githubusercontent.com/62179149/215167115-3123e8bd-be9d-4eb6-85b0-2abd585effb9.PNG)

Therefore, I am going to reopen the issue.

**Comment by wiseaidev** [comment]
Hey @amondnet,

After lil speculation, I found that the problem exists on `SDK > 2.18` (but probably on `SDK >2.17` as well):
![1](https://user-images.githubusercontent.com/62179149/215178479-dffdfc9b-417e-4ecc-96e1-edaafb195215.PNG)

I tried SDK 2.16.8, and the problem is gone. So, it seems like the issue exists on in the newer versions (`SDK > 2.17`).
