### ISSUE TITLE
Observer throws false MobXCaughtException on any exceptions thrown within its scope

### ISSUE THREAD

**Issue by subzero911** [mobxjs/mobx.dart#905]
Example:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/12999702/222943331-1d2b8f75-0b62-436e-b083-c7dbe3cf7a17.png">

Here, the error reason is a bad GoRouter configuration, but MobX wraps it into MobXCaughtException.
This makes debugging difficult.

**Comment by fzyzcjy** [comment]
You can catch MobXCaughtException and read its .exception field

**Comment by subzero911** [comment]
I can't imagine wrapping every Observer into try-catch.
The only thing that comes to my mind is to use root `catcher` or `runZonedGuarded` and check if it's a MobXCaughtException and log to console its inner exception and stacktrace. But do we ever need this MobXCaughtException, if I always unwrap it at the end?
Is it possible to turn off this exception in a config?

**Comment by amondnet** [comment]
@subzero911 
https://mobx.netlify.app/api/context#reactiveconfig

disableErrorBoundaries: When `true`, MobX will not guard against exceptions thrown during reactions. By default, it is `false`, which means MobX will catch unhandled exceptions and ensure the **consistency of the reactive system**.
