### ISSUE TITLE
Support for analyzer 6.0.0

### ISSUE THREAD

**Issue by kishangohel** [mobxjs/mobx.dart#928]

**Comment by subzero911** [comment]
+1
not compatible to `freezed`
<img width="982" alt="image" src="https://github.com/mobxjs/mobx.dart/assets/12999702/4d4be984-0672-4c64-afd6-0ec16ae8b807">

**Comment by yacineblr** [comment]
do you have any news about this please ?

**Comment by pgulegin** [comment]
+1
