### ISSUE TITLE
Create a Hackernews clone 

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#94]
Title says all :-). [Go here for some inspiration](https://hnpwa.com/).

**Comment by feelfreelinux** [comment]
Can help with it in ~5 days

**Comment by chimon2000** [comment]
I started working on something [here](https://github.com/chimon2000/hn_flutter) based off https://play.google.com/store/apps/details?id=com.fynally.hackernews

Didn't see @feelfreelinux comments.

**Comment by feelfreelinux** [comment]
@chimon2000 You can finish working on it, no problem :) I'm not able to anything for next few days anyways. Thanks!

**Comment by pavanpodila** [comment]
Aditya Soni has already made a simple version and blogged it here: https://blog.geekyants.com/mobx-for-state-management-in-flutter-apps-part-2-844bf9b97869

**Comment by pavanpodila** [comment]
We also have a simple version uploaded on https://mobx.pub/examples/hacker-news
