### ISSUE TITLE
How to properly share state between widgets without using props?

### ISSUE THREAD

**Issue by csharad** [mobxjs/mobx.dart#95]
There are use-cases where we need to connect two different components that are not accessible directly. I looked into the examples but it only shows sharing MobX state via props.

As I have seen, we can use a global variable to share state between widgets but it is weird sharing state like that. Is there an ergonomic way and if there is, an example would be awesome. :+1:

**Comment by rrousselGit** [comment]
That's what `InheritedWidget` is here for.

If you don't want to make your own or don't know how these works, I authored one generic `InheritedWIdget` here: https://pub.dartlang.org/packages/provider

**Comment by csharad** [comment]
Awesome! Didn't know about that. Thanks for the help.
