### ISSUE TITLE
[Question] No observables detected when checking in a ternary operator inside of a child parameter

### ISSUE THREAD

**Issue by subzero911** [mobxjs/mobx.dart#953]
I use an Observer like this:
<img width="630" alt="image" src="https://github.com/mobxjs/mobx.dart/assets/12999702/d3423d8f-839f-41c7-9a7e-6d72d69bced2">

Where `viewedAt` is an Observable inside a Task model:
<img width="365" alt="image" src="https://github.com/mobxjs/mobx.dart/assets/12999702/fcd389cb-f5fc-4a38-be58-f4854f3b1c73">

But Observer can't see it for some reason:
<img width="1037" alt="image" src="https://github.com/mobxjs/mobx.dart/assets/12999702/24a4be92-8a3d-4b0f-b4f7-e305b6be8e53">

This error disappears though, if I do reading right in the Observer body:
<img width="651" alt="image" src="https://github.com/mobxjs/mobx.dart/assets/12999702/266412a9-9826-47fd-8c32-0d4420663f8f">

Why is this line `style: task.viewedAt.value == null ? styleA : styleB` treated like a non-immediate context execution?
Does a ternary operator implicitly unfolds into the anonymous function by the compiler?

**Comment by subzero911** [comment]
Probably, the question is more like: why is this string `style: showUnseen && task.viewedAt.value == null ? X : Y` treated like a non-immediate context execution?
Is a ternary operator implicitly unfolds into the anonymous nested function by the compiler?

**Comment by amondnet** [comment]
@subzero911 

This is because `showUnseen` is not an `Observable`. If `showUnseen` is `false`, conditions after `&&` are not checked.

```dart
style: false && store.viewedAt.value != null // store.viewedAt.value is not used
              ? const TextStyle()
              : const TextStyle()
```

`style: showUnseen && store.viewedAt.value != null` -> `style:  store.viewedAt.value != null && showUnseen`
