### ISSUE TITLE
late reactions not working

### ISSUE THREAD

**Issue by subzero911** [mobxjs/mobx.dart#960]
If you initialize a late reaction right in the Store, it will never fire:
```dart
abstract class _FilteredTasksControllerBase with Store {

    @observable
    var tasks = ObservableList<Task>();

    late final r = reaction((_) => tasks.length, (len) async {
      log.wtf('reaction fired');
      await markAsSeen();
      await taskController.fetchTaskStats();
    });

}
```

But if you just declare it in the Store body and initialize in the constructor, it will do. Magic?

```dart
late final ReactionDisposer r;

_FilteredTasksControllerBase({
    required this.taskController,
    required this.currentStatus,
  }) {
    r = reaction((_) => tasks.length, (len) async {
      log.wtf('reaction fired');
     
      await markAsSeen();
      await taskController.fetchTaskStats();
    });
  }
```

**Comment by fzyzcjy** [comment]
IIRC it is because `late final` fields are lazy. If you never read them, then they will never be initialized.

**Comment by subzero911** [comment]
That's crazy.

**Comment by fzyzcjy** [comment]
It's a dart feature

**Comment by amondnet** [comment]
https://dart.dev/null-safety/understanding-null-safety#lazy-initialization

**Comment by subzero911** [comment]
So if I initialize a reaction at declaration, it's considered to be a lazy initialization.
But if I do it in the class constructor, it's considered as an assignment, and won't be lazy.
