### ISSUE TITLE
Can't use nullable type alias in computed; `null check operator used on null value`

### ISSUE THREAD

**Issue by clangenb** [mobxjs/mobx.dart#968]
I have a `@computed` defined like this:

```dart
typedef BlockHash = Uint8List;

@computed
BlockHash? get latestHash {
  // Workaround for https://dart.dev/tools/non-promotion-reasons#property.
  final hash = latestHashHex;
  if (hash != null) {
    // return null;
    return BlockHash.fromList(hex.decode(hash.replaceFirst('0x', '')));
  } else {
    return null;
  }
} 
```

When I ran the build runner, it gave me a `null check operator used on null value` error. However, when I fill in the original type `Uint8List` it works.

Even more interestingly, if I replace the `Uint8List` with the `BlockHash` after a successful build, it works, but it keeps the `Uint8List` in the generated file.

**Comment by amondnet** [comment]
@clangenb The code is generated without any issues. Could you please provide a reproducible code?

**Comment by clangenb** [comment]
Ok, I see. Interesting. I have assumed that my code is minimal enough to rule out that this error is from something else. I will revisit this soon, but close this issue now under the assumption that the error is due to my code.
