### ISSUE TITLE
What's remaining for a 0.1 release?

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#97]
I think feature wise, it's looking solid. Curious if there is anything sorely pending for a 0.1 release. At this point I see only the following:

- [x] Finalize features for 0.1 and harden them with more tests
- [x] Update Readme
- [x] Update the website with API docs and guidance for building larger apps
- [x] Add few more examples
- [ ] Anything else...

What say @katis, @rrousselGit ?

**Comment by smiLLe** [comment]
Hey guys. i am actively following this repo for a while and i am pretty sure, as soon as people start using mobx and especially @rrousselGit hooks implementation one of these question will pop up:
"how to navigate/show dialog/show snackbar", "am i allowed to use context" .... [in (use)autorun, (use)when].

**Comment by rrousselGit** [comment]
State change of mobx stores are made when the widget tree is unlocked (not building).
As such, listeners (and therefore hooks) can freely call `setState` and use the context API.

Like so:

```dart
Widget build(BuildContext context) {
  final store = Store.of(context);
  useReaction(() => store.currentRoute, () {
    Navigator.pushNamed(context, store.currentRoute);
  });

  return Container();
}
```

**Comment by katis** [comment]
We could also do a `0.0.x-dev` release before documentation is done, so that the bravest can easily test the packages with their own code. I found a weird case in my own app that made the whole thing lock up, but I could not reliably repeat it, or find the minimal test case and it would be good to see if anyone else runs into that issue before we do the real release.

**Comment by pavanpodila** [comment]
A lock up could have happened if you have some cyclic dependency. May be diagnose the dependency tree? We should also catch that  in code. Right now, we are missing this check. I'll add an issue for that

**Comment by marcoms** [comment]
Currently it doesn't seem clear how to create observables from non-primitive values. I've figured out from the examples that I can use `ObservableList` for lists (couldn't regular `List`s be wrapped automatically by `@observable` [as in MobX.js?](https://mobx.js.org/refguide/observable.html)), but I'm not sure how I would do this for custom types.

**Comment by pavanpodila** [comment]
For custom types, you could just create a `Store`, like we do for the [Todos example](https://github.com/mobxjs/mobx.dart/tree/master/mobx_examples/lib/todos). You can mark the properties you want as `@observable`.

You can have a plain `List` as `@observable`, in which case it will react only when the reference to the list changes. With an `ObservableList`, it will also react when the length changes, when items are added/removed. We deliberately don't convert a `List` to an `ObservableList` when you mark a `List` as `@Observable`

**Comment by pcegarra** [comment]
Is this feature available?
Pass { deep: false } as 3rd argument to disable the auto conversion of property values

**Comment by pavanpodila** [comment]
These are not needed in the dart world. By default all observables are shallow and by reference.

**Comment by pavanpodila** [comment]
I am planning to push a `0.1` release soon. The website and docs are mostly in place. There will be ongoing additions. However I feel the community is ready to consume the packages. Please share any concerns. @katis , @rrousselGit ?

**Comment by pavanpodila** [comment]
0.1 has been published.
